import type { Bilingual } from "@/types/lesson";

export interface GlossaryEntry {
  term: string;
  def: Bilingual;
  chapter: string;
}

export const GLOSSARY: GlossaryEntry[] = [
  { term: "Testing / Prueba", def: { es: "Conjunto de actividades para descubrir defectos y evaluar la calidad de artefactos de software.", en: "Set of activities to discover defects and evaluate the quality of software artifacts." }, chapter: "1" },
  { term: "Defecto / Bug / Fault", def: { es: "Imperfección en un componente o sistema que puede causar que el componente o sistema falle en realizar su función requerida.", en: "Imperfection in a component or system that can cause it to fail to perform its required function." }, chapter: "1" },
  { term: "Error / Mistake", def: { es: "Acción humana que produce un resultado incorrecto, que introduce un defecto en el sistema.", en: "Human action that produces an incorrect result, introducing a defect into the system." }, chapter: "1" },
  { term: "Fallo / Failure", def: { es: "Evento en el cual un componente o sistema no realiza una función requerida dentro de los límites especificados.", en: "Event in which a component or system does not perform a required function within specified limits." }, chapter: "1" },
  { term: "Causa raíz / Root cause", def: { es: "Razón fundamental por la que ocurre un problema. La eliminación de la causa raíz evita la recurrencia del defecto.", en: "Fundamental reason why a problem occurs. Removing the root cause prevents defect recurrence." }, chapter: "1" },
  { term: "Calidad / Quality", def: { es: "Grado en el que un componente o sistema satisface las necesidades indicadas e implícitas de sus partes interesadas.", en: "Degree to which a component or system satisfies the stated and implied needs of its stakeholders." }, chapter: "1" },
  { term: "Aseguramiento de calidad / QA", def: { es: "Actividades que se centran en proporcionar confianza en que los requisitos de calidad se cumplirán.", en: "Activities focused on providing confidence that quality requirements will be fulfilled." }, chapter: "1" },
  { term: "Verificación / Verification", def: { es: "Confirmación de que el software cumple con los requisitos especificados.", en: "Confirmation that software meets specified requirements." }, chapter: "1" },
  { term: "Validación / Validation", def: { es: "Confirmación de que el software satisface las necesidades y expectativas del usuario o cliente.", en: "Confirmation that software satisfies the needs and expectations of the user or customer." }, chapter: "1" },
  { term: "Testware", def: { es: "Artefactos producidos durante el proceso de prueba: planes, casos, scripts, datos, informes.", en: "Artifacts produced during the test process: plans, cases, scripts, data, reports." }, chapter: "1" },
  { term: "Trazabilidad / Traceability", def: { es: "Capacidad de identificar relaciones entre productos de trabajo de testing y requisitos u otros artefactos.", en: "Ability to identify relationships between test work products and requirements or other artifacts." }, chapter: "1" },
  { term: "Prueba de componente / Unit test", def: { es: "Nivel de prueba que verifica componentes individuales del software en aislamiento.", en: "Test level that verifies individual software components in isolation." }, chapter: "2" },
  { term: "Prueba de integración / Integration test", def: { es: "Nivel de prueba que verifica la interacción entre componentes o sistemas integrados.", en: "Test level that verifies the interaction between integrated components or systems." }, chapter: "2" },
  { term: "Prueba de sistema / System test", def: { es: "Nivel de prueba que verifica el comportamiento del sistema completo de extremo a extremo.", en: "Test level that verifies the behavior of the complete system end-to-end." }, chapter: "2" },
  { term: "Prueba de aceptación / UAT", def: { es: "Nivel de prueba realizado para determinar si el sistema cumple con los criterios de aceptación del negocio.", en: "Test level performed to determine if the system meets business acceptance criteria." }, chapter: "2" },
  { term: "Testing funcional", def: { es: "Pruebas que verifican lo que el sistema HACE, basadas en las funciones requeridas.", en: "Tests that verify what the system DOES, based on required functions." }, chapter: "2" },
  { term: "Testing no funcional", def: { es: "Pruebas que verifican cómo se comporta el sistema (rendimiento, usabilidad, seguridad, fiabilidad).", en: "Tests that verify how the system behaves (performance, usability, security, reliability)." }, chapter: "2" },
  { term: "Testing de regresión", def: { es: "Pruebas que verifican que los cambios no han introducido nuevos defectos en áreas que funcionaban correctamente.", en: "Tests that verify changes haven't introduced new defects in areas that previously worked correctly." }, chapter: "2" },
  { term: "Testing de humo / Smoke test", def: { es: "Conjunto básico de pruebas que verifican las funcionalidades más críticas para confirmar que el sistema puede ser probado más a fondo.", en: "Basic set of tests verifying the most critical functionalities to confirm the system can be further tested." }, chapter: "2" },
  { term: "Alpha testing", def: { es: "Prueba de aceptación realizada por usuarios en el sitio del desarrollador.", en: "Acceptance testing performed by users at the developer's site." }, chapter: "2" },
  { term: "Beta testing", def: { es: "Prueba de aceptación realizada por usuarios en su propio entorno antes del lanzamiento general.", en: "Acceptance testing performed by users in their own environment before general release." }, chapter: "2" },
  { term: "Revisión / Review", def: { es: "Proceso estático que evalúa los productos de trabajo de software para encontrar defectos antes de la ejecución.", en: "Static process evaluating software work products to find defects before execution." }, chapter: "3" },
  { term: "Inspección / Inspection", def: { es: "Tipo más formal de revisión estática, con roles definidos, métricas y criterios de entrada/salida.", en: "Most formal type of static review, with defined roles, metrics and entry/exit criteria." }, chapter: "3" },
  { term: "Walkthrough", def: { es: "Tipo de revisión guiada por el autor, donde el equipo sigue la lógica del producto paso a paso.", en: "Review type guided by the author, where the team follows the product logic step by step." }, chapter: "3" },
  { term: "Análisis estático / Static analysis", def: { es: "Evaluación automatizada del código sin ejecutarlo, para detectar defectos de código y violaciones de estándares.", en: "Automated evaluation of code without executing it, to detect code defects and standard violations." }, chapter: "3" },
  { term: "Partición de equivalencia / EP", def: { es: "Técnica de caja negra que divide las entradas en particiones donde todos los valores se comportan igual.", en: "Black-box technique dividing inputs into partitions where all values behave the same." }, chapter: "4" },
  { term: "Análisis de valor límite / BVA", def: { es: "Técnica de caja negra que prueba los valores en los bordes de las particiones de equivalencia.", en: "Black-box technique testing values at the edges of equivalence partitions." }, chapter: "4" },
  { term: "Tabla de decisión / Decision table", def: { es: "Técnica de caja negra para probar combinaciones de condiciones lógicas y sus acciones resultantes.", en: "Black-box technique for testing combinations of logical conditions and their resulting actions." }, chapter: "4" },
  { term: "Transición de estado / State transition", def: { es: "Técnica de caja negra para probar sistemas cuyo comportamiento depende del estado actual y del evento recibido.", en: "Black-box technique for testing systems whose behavior depends on the current state and received event." }, chapter: "4" },
  { term: "Prueba de sentencia / Statement coverage", def: { es: "Técnica de caja blanca que mide el porcentaje de sentencias ejecutables ejecutadas por los tests.", en: "White-box technique measuring the percentage of executable statements executed by tests." }, chapter: "4" },
  { term: "Prueba de rama / Branch coverage", def: { es: "Técnica de caja blanca que mide el porcentaje de ramas del flujo de control ejecutadas (más fuerte que statement coverage).", en: "White-box technique measuring the percentage of control flow branches executed (stronger than statement coverage)." }, chapter: "4" },
  { term: "Testing exploratorio", def: { es: "Técnica basada en experiencia donde el diseño y la ejecución de pruebas ocurren simultáneamente, sin scripts predefinidos.", en: "Experience-based technique where test design and execution happen simultaneously, without predefined scripts." }, chapter: "4" },
  { term: "Error guessing / Adivinanza de errores", def: { es: "Técnica basada en experiencia donde el tester usa intuición y experiencia para anticipar tipos de errores comunes.", en: "Experience-based technique where the tester uses intuition and experience to anticipate common error types." }, chapter: "4" },
  { term: "ATDD", def: { es: "Acceptance Test-Driven Development: técnica donde los tests de aceptación se crean antes del desarrollo con participación de todo el equipo.", en: "Acceptance Test-Driven Development: technique where acceptance tests are created before development with full team participation." }, chapter: "4" },
  { term: "Plan de pruebas / Test plan", def: { es: "Documento que describe el enfoque, recursos, alcance, criterios y actividades de testing para un proyecto.", en: "Document describing the testing approach, resources, scope, criteria and activities for a project." }, chapter: "5" },
  { term: "Riesgo de producto / Product risk", def: { es: "Posibilidad de que el producto de software no cumpla con su función esperada o los requisitos de calidad.", en: "Possibility that the software product won't fulfill its expected function or quality requirements." }, chapter: "5" },
  { term: "Riesgo de proyecto / Project risk", def: { es: "Posibilidad de que el proyecto no logre sus objetivos de alcance, tiempo o presupuesto.", en: "Possibility that the project won't achieve its scope, time or budget objectives." }, chapter: "5" },
  { term: "Criterios de entrada / Entry criteria", def: { es: "Condiciones que deben cumplirse para iniciar una actividad de testing.", en: "Conditions that must be met to start a testing activity." }, chapter: "5" },
  { term: "Criterios de salida / Exit criteria", def: { es: "Condiciones que deben cumplirse para completar una actividad de testing.", en: "Conditions that must be met to complete a testing activity." }, chapter: "5" },
  { term: "Métricas de prueba / Test metrics", def: { es: "Medidas cuantitativas usadas para gestionar y controlar el proceso de testing (cobertura, densidad de defectos, etc.).", en: "Quantitative measures used to manage and control the test process (coverage, defect density, etc.)." }, chapter: "5" },
  { term: "Gestión de configuración / Config management", def: { es: "Disciplina para controlar y registrar la evolución de los artefactos de software y testware a lo largo del proyecto.", en: "Discipline for controlling and recording the evolution of software and testware artifacts throughout the project." }, chapter: "5" },
  { term: "Severidad / Severity", def: { es: "Grado de impacto técnico que tiene un defecto sobre el sistema.", en: "Degree of technical impact a defect has on the system." }, chapter: "5" },
  { term: "Prioridad / Priority", def: { es: "Urgencia con la que debe corregirse un defecto.", en: "Urgency with which a defect must be fixed." }, chapter: "5" },
  { term: "Gestión de defectos / Defect management", def: { es: "Proceso de capturar, investigar, resolver y cerrar los defectos encontrados durante el testing.", en: "Process of capturing, investigating, resolving and closing defects found during testing." }, chapter: "5" },
  { term: "Testing de rendimiento / Performance testing", def: { es: "Pruebas que evalúan la velocidad, escalabilidad y estabilidad del sistema bajo diferentes cargas.", en: "Tests that evaluate the speed, scalability and stability of the system under different loads." }, chapter: "2" },
  { term: "Shift-left testing", def: { es: "Enfoque donde el testing comienza lo antes posible en el SDLC para detectar defectos temprano y reducir costos.", en: "Approach where testing starts as early as possible in the SDLC to detect defects early and reduce costs." }, chapter: "2" },
  { term: "DevOps", def: { es: "Conjunto de prácticas que combina desarrollo de software y operaciones de TI para acortar el ciclo de vida del desarrollo.", en: "Set of practices combining software development and IT operations to shorten the development lifecycle." }, chapter: "2" },
  { term: "CI/CD", def: { es: "Integración Continua / Entrega Continua: prácticas de automatización que permiten integrar y desplegar cambios frecuentemente.", en: "Continuous Integration / Continuous Delivery: automation practices enabling frequent integration and deployment of changes." }, chapter: "2" },
  { term: "Herramienta de testing / Test tool", def: { es: "Producto de software que da soporte a una o más actividades de prueba, como planificación, diseño, ejecución, análisis estático o medición.", en: "Software product that supports one or more test activities, such as planning, design, execution, static analysis or measurement." }, chapter: "6" },
  { term: "Herramienta de gestión de pruebas / Test management tool", def: { es: "Herramienta que gestiona casos, ejecuciones, trazabilidad y defectos a lo largo del proceso de testing (p. ej. Jira con Xray, Azure Test Plans, TestRail).", en: "Tool that manages cases, executions, traceability and defects throughout the test process (e.g. Jira with Xray, Azure Test Plans, TestRail)." }, chapter: "6" },
  { term: "Herramienta de gestión de defectos / Defect management tool", def: { es: "Herramienta para registrar, seguir y gestionar el ciclo de vida de los defectos encontrados durante el testing.", en: "Tool for recording, tracking and managing the lifecycle of defects found during testing." }, chapter: "6" },
  { term: "Herramienta de ejecución de pruebas / Test execution tool", def: { es: "Herramienta que ejecuta casos de prueba de forma automatizada y compara los resultados reales con los esperados.", en: "Tool that runs test cases automatically and compares actual results against expected ones." }, chapter: "6" },
  { term: "Herramienta de medición de cobertura / Coverage tool", def: { es: "Herramienta que instrumenta el código y reporta qué porcentaje de sentencias o ramas se ejecuta durante las pruebas.", en: "Tool that instruments the code and reports what percentage of statements or branches is executed during testing." }, chapter: "6" },
  { term: "Automatización de pruebas / Test automation", def: { es: "Uso de software para controlar la ejecución de pruebas, comparar resultados y generar informes, reduciendo el esfuerzo manual repetitivo.", en: "Use of software to control test execution, compare results and report, reducing repetitive manual effort." }, chapter: "6" },
  { term: "Herramienta de análisis estático / Static analysis tool", def: { es: "Herramienta que examina el código fuente sin ejecutarlo para detectar defectos, code smells y violaciones de estándares (p. ej. linters, SonarQube).", en: "Tool that examines source code without executing it to detect defects, code smells and standard violations (e.g. linters, SonarQube)." }, chapter: "6" },
  { term: "Herramienta de preparación de datos / Test data tool", def: { es: "Herramienta que genera, gestiona o anonimiza datos de prueba para alimentar la ejecución de casos.", en: "Tool that generates, manages or anonymizes test data to feed test case execution." }, chapter: "6" },
  { term: "ROI de la automatización / Automation ROI", def: { es: "Retorno de inversión de automatizar: el ahorro acumulado debe superar la inversión inicial más el coste de mantenimiento de los scripts.", en: "Return on investment of automation: accumulated savings must exceed the initial investment plus the cost of maintaining the scripts." }, chapter: "6" },

  /* ---------- QA Fundamentals — Módulo 1 ---------- */
  { term: "Control de calidad / QC", def: { es: "Actividades orientadas al producto para detectar defectos, comprobando el producto contra criterios definidos.", en: "Product-oriented activities to detect defects, checking the product against defined criteria." }, chapter: "qaf-1" },
  { term: "Mentalidad de testing / Testing mindset", def: { es: "Combinación de curiosidad, escepticismo profesional y atención al detalle, sin perder la colaboración.", en: "Combination of curiosity, professional skepticism and attention to detail, without losing collaboration." }, chapter: "qaf-1" },

  /* ---------- QA Fundamentals — Módulo 2 ---------- */
  { term: "SQuaRE / ISO 25010", def: { es: "Familia de normas ISO/IEC para requisitos y evaluación de calidad del software; 25010 define el modelo de calidad de producto.", en: "ISO/IEC family of standards for software quality requirements and evaluation; 25010 defines the product quality model." }, chapter: "qaf-2" },
  { term: "Adecuación funcional / Functional suitability", def: { es: "Característica de calidad que evalúa si las funciones del sistema hacen lo correcto.", en: "Quality characteristic evaluating whether the system's functions do the right thing." }, chapter: "qaf-2" },
  { term: "Usabilidad / Usability", def: { es: "Característica de calidad que evalúa la facilidad de aprendizaje y uso del sistema.", en: "Quality characteristic evaluating the system's ease of learning and use." }, chapter: "qaf-2" },
  { term: "Fiabilidad / Reliability", def: { es: "Característica de calidad relativa a la disponibilidad y la tolerancia a fallos del sistema.", en: "Quality characteristic regarding system availability and fault tolerance." }, chapter: "qaf-2" },
  { term: "Mantenibilidad / Maintainability", def: { es: "Característica de calidad que evalúa la facilidad para modificar y corregir el sistema.", en: "Quality characteristic evaluating how easily the system can be modified and fixed." }, chapter: "qaf-2" },
  { term: "Portabilidad / Portability", def: { es: "Característica de calidad que evalúa la adaptación del sistema a distintos entornos.", en: "Quality characteristic evaluating the system's adaptation to different environments." }, chapter: "qaf-2" },
  { term: "Coste de la calidad / Cost of quality", def: { es: "Coste de prevención y evaluación frente al coste de los fallos cuando el defecto llega al usuario.", en: "Cost of prevention and appraisal versus the cost of failures when the defect reaches the user." }, chapter: "qaf-2" },

  /* ---------- QA Fundamentals — Módulo 3 (SDLC y STLC) ---------- */
  { term: "Modelo en cascada / Waterfall model", def: { es: "Modelo de SDLC secuencial y lineal en el que cada fase (requisitos, diseño, desarrollo, pruebas, mantenimiento) se completa antes de iniciar la siguiente.", en: "Sequential, linear SDLC model where each phase (requirements, design, development, testing, maintenance) is completed before the next begins." }, chapter: "qaf-3" },
  { term: "Modelo en V / V-model", def: { es: "Modelo de SDLC en el que cada fase de desarrollo tiene asociado un nivel de prueba correspondiente, planificado y diseñado en paralelo a esa fase.", en: "SDLC model in which each development phase has a corresponding test level, planned and designed in parallel with that phase." }, chapter: "qaf-3" },
  { term: "Modelo iterativo-incremental / Iterative-incremental model", def: { es: "Modelo de SDLC en el que el software se construye y prueba en ciclos cortos y repetidos, entregando incrementos funcionales cada vez.", en: "SDLC model in which software is built and tested in short, repeated cycles, delivering functional increments each time." }, chapter: "qaf-3" },
  { term: "STLC / Ciclo de Vida del Testing", def: { es: "Secuencia de fases específicas del testing (análisis, diseño, implementación, ejecución, evaluación de criterios de salida y cierre) que ocurren dentro del SDLC.", en: "Sequence of testing-specific phases (analysis, design, implementation, execution, exit criteria evaluation and closure) that occur within the SDLC." }, chapter: "qaf-3" },
  { term: "Retest / Re-test", def: { es: "Repetición de una prueba que falló previamente para confirmar que el defecto corregido ya no se reproduce.", en: "Re-running a test that previously failed to confirm that the fixed defect no longer occurs." }, chapter: "qaf-3" },
  { term: "Análisis de pruebas / Test analysis", def: { es: "Fase del STLC en la que se determina QUÉ probar, identificando condiciones de prueba a partir de la base de pruebas.", en: "STLC phase in which it is determined WHAT to test, identifying test conditions from the test basis." }, chapter: "qaf-3" },
  { term: "Diseño de pruebas / Test design", def: { es: "Fase del STLC en la que se determina CÓMO probar: se diseñan los casos de prueba y se identifican los datos necesarios.", en: "STLC phase in which it is determined HOW to test: test cases are designed and the necessary data is identified." }, chapter: "qaf-3" },

  /* ---------- QA Fundamentals — Módulo 4 (Análisis de Requisitos) ---------- */
  { term: "Requisito funcional / Functional requirement", def: { es: "Especifica QUÉ debe hacer el sistema: una función, característica o comportamiento concreto.", en: "Specifies WHAT the system must do: a concrete function, feature or behavior." }, chapter: "qaf-4" },
  { term: "Requisito no funcional / Non-functional requirement", def: { es: "Especifica CÓMO debe comportarse el sistema: rendimiento, usabilidad, seguridad, fiabilidad, etc.", en: "Specifies HOW the system must behave: performance, usability, security, reliability, etc." }, chapter: "qaf-4" },
  { term: "Historia de usuario / User story", def: { es: "Descripción breve de una funcionalidad desde la perspectiva del usuario, habitualmente en formato 'Como... quiero... para...'.", en: "Short description of a feature from the user's perspective, typically in the format 'As a... I want... so that...'." }, chapter: "qaf-4" },
  { term: "Criterios de aceptación / Acceptance criteria", def: { es: "Condiciones específicas y verificables que una historia de usuario debe cumplir para considerarse correctamente implementada.", en: "Specific, verifiable conditions a user story must meet to be considered correctly implemented." }, chapter: "qaf-4" },
  { term: "Gherkin (Dado/Cuando/Entonces)", def: { es: "Lenguaje estructurado para escribir criterios de aceptación en formato Given/When/Then (Dado/Cuando/Entonces).", en: "Structured language for writing acceptance criteria in Given/When/Then format." }, chapter: "qaf-4" },
  { term: "Matriz de trazabilidad / Traceability matrix", def: { es: "Documento que relaciona cada requisito con sus casos de prueba correspondientes, para detectar requisitos sin cobertura.", en: "Document that relates each requirement to its corresponding test cases, to detect requirements without coverage." }, chapter: "qaf-4" },

  /* ---------- QA Fundamentals — Módulo 5 (Diseño de Casos de Prueba) ---------- */
  { term: "Caso de prueba / Test case", def: { es: "Conjunto de precondiciones, datos de entrada, pasos de ejecución y resultado esperado diseñado para verificar un objetivo de prueba concreto.", en: "Set of preconditions, input data, execution steps and expected result designed to verify a specific test objective." }, chapter: "qaf-5" },
  { term: "Precondición / Precondition", def: { es: "Estado o condición que debe cumplirse antes de ejecutar los pasos de un caso de prueba (p. ej. 'usuario con sesión iniciada').", en: "State or condition that must exist before running the steps of a test case (e.g. 'logged-in user')." }, chapter: "qaf-5" },
  { term: "Resultado esperado / Expected result", def: { es: "Salida o comportamiento que el sistema debería producir si funciona correctamente, definido antes de ejecutar la prueba.", en: "Output or behavior the system should produce if it works correctly, defined before the test is executed." }, chapter: "qaf-5" },
  { term: "Datos de prueba / Test data", def: { es: "Conjunto de valores de entrada necesarios para ejecutar un caso de prueba.", en: "Set of input values needed to execute a test case." }, chapter: "qaf-5" },
  { term: "Datos sintéticos / Synthetic data", def: { es: "Datos de prueba generados artificialmente, sin información real de clientes, usados por privacidad y disponibilidad.", en: "Artificially generated test data, without real customer information, used for privacy and availability reasons." }, chapter: "qaf-5" },

  /* ---------- QA Fundamentals — Módulo 6 (Ejecución y Gestión de Defectos) ---------- */
  { term: "Reporte de defecto / Bug report", def: { es: "Documento que describe un defecto encontrado: pasos para reproducir, resultado esperado, resultado real y evidencias.", en: "Document describing a found defect: steps to reproduce, expected result, actual result and evidence." }, chapter: "qaf-6" },
  { term: "Ciclo de vida del defecto / Defect lifecycle", def: { es: "Secuencia de estados por los que pasa un defecto desde que se reporta (nuevo) hasta que se cierra.", en: "Sequence of states a defect goes through from being reported (new) to being closed." }, chapter: "qaf-6" },
  { term: "Pasos para reproducir / Steps to reproduce", def: { es: "Secuencia mínima y precisa de acciones necesarias para que el defecto vuelva a manifestarse.", en: "Minimal, precise sequence of actions needed to make the defect occur again." }, chapter: "qaf-6" },
  { term: "Estado 'Bloqueado' / Blocked status", def: { es: "Estado de una prueba que no se pudo ejecutar por una causa externa, como un entorno caído o una dependencia no disponible.", en: "Status of a test that could not be run due to an external cause, such as a down environment or unavailable dependency." }, chapter: "qaf-6" },
  { term: "Tasa de fuga de defectos / Defect leakage", def: { es: "Métrica que mide los defectos no detectados durante el testing que llegan a producción.", en: "Metric that measures defects not caught during testing that reach production." }, chapter: "qaf-6" },

  /* ---------- QA Fundamentals — Módulo 7 (Metodologías Ágiles) ---------- */
  { term: "Manifiesto Ágil / Agile Manifesto", def: { es: "Declaración de cuatro valores y doce principios que guían el desarrollo de software ágil, publicada en 2001.", en: "Declaration of four values and twelve principles guiding agile software development, published in 2001." }, chapter: "qaf-7" },
  { term: "Scrum", def: { es: "Marco de trabajo ágil ligero, basado en sprints cortos, con roles, eventos y artefactos definidos.", en: "Lightweight agile framework based on short sprints, with defined roles, events and artifacts." }, chapter: "qaf-7" },
  { term: "Sprint", def: { es: "Periodo de tiempo fijo (normalmente entre 1 y 4 semanas) en el que el equipo Scrum crea un incremento de producto.", en: "Fixed time period (typically 1 to 4 weeks) in which the Scrum team creates a product increment." }, chapter: "qaf-7" },
  { term: "Retrospectiva del Sprint / Sprint Retrospective", def: { es: "Evento de Scrum al final del sprint donde el equipo inspecciona su forma de trabajar y planifica mejoras.", en: "Scrum event at the end of the sprint where the team inspects how it works and plans improvements." }, chapter: "qaf-7" },
  { term: "Kanban", def: { es: "Método de gestión del flujo de trabajo basado en visualizar el trabajo en un tablero y limitar el trabajo en curso (WIP).", en: "Workflow management method based on visualizing work on a board and limiting work in progress (WIP)." }, chapter: "qaf-7" },
  { term: "Límite WIP / WIP limit", def: { es: "Número máximo de elementos que pueden estar en una columna del tablero Kanban a la vez, para mejorar el flujo y revelar cuellos de botella.", en: "Maximum number of items allowed in a Kanban board column at a time, to improve flow and reveal bottlenecks." }, chapter: "qaf-7" },
  { term: "Definición de Terminado / Definition of Done (DoD)", def: { es: "Conjunto de criterios, incluido el testing, que una historia debe cumplir para considerarse completada.", en: "Set of criteria, including testing, that a story must meet to be considered complete." }, chapter: "qaf-7" },
  { term: "Definición de Preparado / Definition of Ready (DoR)", def: { es: "Conjunto de criterios que una historia debe cumplir antes de entrar en un sprint, para asegurar que es comprensible y estimable.", en: "Set of criteria a story must meet before entering a sprint, to ensure it is understandable and estimable." }, chapter: "qaf-7" },

  /* ---------- QA Fundamentals — Módulo 8 (Herramientas para QA Manual) ---------- */
  { term: "Jira", def: { es: "Herramienta de Atlassian para la gestión de issues (incluidos bugs), workflows y proyectos ágiles.", en: "Atlassian tool for managing issues (including bugs), workflows and agile projects." }, chapter: "qaf-8" },
  { term: "JQL (Jira Query Language)", def: { es: "Lenguaje de consulta de Jira para buscar y filtrar issues mediante criterios precisos.", en: "Jira's query language for searching and filtering issues with precise criteria." }, chapter: "qaf-8" },
  { term: "Confluence", def: { es: "Herramienta de Atlassian para documentación colaborativa: planes de prueba, estrategias y checklists.", en: "Atlassian tool for collaborative documentation: test plans, strategies and checklists." }, chapter: "qaf-8" },
  { term: "Azure Test Plans", def: { es: "Herramienta de Azure DevOps para gestionar planes, suites y casos de prueba manuales, y registrar su ejecución.", en: "Azure DevOps tool for managing manual test plans, suites and cases, and recording their execution." }, chapter: "qaf-8" },
  { term: "Test Suite (Azure Test Plans)", def: { es: "Conjunto de casos de prueba relacionados, agrupados dentro de un Test Plan en Azure Test Plans.", en: "Set of related test cases, grouped within a Test Plan in Azure Test Plans." }, chapter: "qaf-8" },

  /* ---------- QA Fundamentals — Módulo 9 (Testing Web y Mobile Manual) ---------- */
  { term: "DevTools (herramientas de desarrollador)", def: { es: "Conjunto de herramientas integradas en el navegador para inspeccionar elementos, consola, red y rendimiento.", en: "Set of tools built into the browser to inspect elements, console, network and performance." }, chapter: "qaf-9" },
  { term: "Testing cross-browser / Cross-browser testing", def: { es: "Comprobación de que un sitio web funciona y se ve correctamente en distintos navegadores.", en: "Checking that a website works and looks correct across different browsers." }, chapter: "qaf-9" },
  { term: "Diseño responsive / Responsive design", def: { es: "Diseño que adapta la interfaz a distintos tamaños de pantalla: móvil, tablet y escritorio.", en: "Design that adapts the interface to different screen sizes: mobile, tablet and desktop." }, chapter: "qaf-9" },
  { term: "Testing mobile / Mobile testing", def: { es: "Pruebas específicas de aplicaciones móviles: gestos táctiles, interrupciones, permisos y conectividad cambiante.", en: "Testing specific to mobile applications: touch gestures, interruptions, permissions and changing connectivity." }, chapter: "qaf-9" },
  { term: "WCAG (Pautas de Accesibilidad)", def: { es: "Web Content Accessibility Guidelines: estándar internacional de accesibilidad web, organizado en los principios POUR.", en: "Web Content Accessibility Guidelines: international web accessibility standard, organized around the POUR principles." }, chapter: "qaf-9" },
  { term: "POUR (Perceptible, Operable, Comprensible, Robusto)", def: { es: "Los cuatro principios en los que se organizan las WCAG: Perceptible, Operable, Comprensible y Robusto.", en: "The four principles WCAG is organized around: Perceivable, Operable, Understandable and Robust." }, chapter: "qaf-9" },

  /* ---------- QA Fundamentals — Módulo 10 (IA aplicada al QA) ---------- */
  { term: "IA generativa / Generative AI", def: { es: "Inteligencia artificial capaz de crear contenido nuevo (texto, código, datos) a partir de instrucciones (prompts).", en: "Artificial intelligence capable of creating new content (text, code, data) from instructions (prompts)." }, chapter: "qaf-10" },
  { term: "Prompt", def: { es: "Instrucción o conjunto de instrucciones dado a un modelo de IA para obtener una respuesta concreta.", en: "Instruction or set of instructions given to an AI model to obtain a specific response." }, chapter: "qaf-10" },
  { term: "Alucinación (IA) / Hallucination", def: { es: "Información plausible pero incorrecta o inventada generada por un modelo de IA.", en: "Plausible but incorrect or invented information generated by an AI model." }, chapter: "qaf-10" },
  { term: "'IA para QA' vs 'QA de IA' / 'AI for QA' vs 'QA of AI'", def: { es: "'IA para QA' usa la IA como herramienta para probar mejor; 'QA de IA' consiste en probar sistemas basados en IA.", en: "'AI for QA' uses AI as a tool to test better; 'QA of AI' means testing AI-based systems." }, chapter: "qaf-10" },
  { term: "Revisión humana / Human review", def: { es: "Verificación por parte de una persona del contenido generado por IA antes de usarlo; salvaguarda clave frente a alucinaciones y sesgos.", en: "A person's verification of AI-generated content before use; the key safeguard against hallucinations and bias." }, chapter: "qaf-10" },
  { term: "Dossier de QA / QA dossier", def: { es: "Conjunto de entregables de un proyecto de QA (análisis, casos, ejecución, defectos, informe) reunidos como evidencia del trabajo realizado.", en: "Set of deliverables from a QA project (analysis, cases, execution, defects, report) gathered as evidence of the work done." }, chapter: "qaf-10" },

  /* ---------- Automation — Módulo 1 (TypeScript Foundations) ---------- */
  { term: "Tipado estático / Static typing", def: { es: "Verificación de tipos en tiempo de compilación que detecta errores en los datos y parámetros de un test antes de ejecutarlo.", en: "Type checking at compile time that catches errors in test data and parameters before running the test." }, chapter: "auto-1" },
  { term: "Interface (TypeScript)", def: { es: "Contrato que define la forma de un objeto, usado para modelar datos de prueba de forma explícita y verificable.", en: "Contract defining the shape of an object, used to model test data explicitly and verifiably." }, chapter: "auto-1" },
  { term: "Enum (TypeScript)", def: { es: "Conjunto de valores nombrados y finitos, útil para modelar estados conocidos en los tests (p. ej. estados de un pedido).", en: "Finite set of named values, useful for modeling known states in tests (e.g. order statuses)." }, chapter: "auto-1" },
  { term: "Async/Await", def: { es: "Sintaxis de JavaScript/TypeScript para escribir código asíncrono de forma secuencial; Playwright la usa para esperar automáticamente a que los elementos estén listos.", en: "JavaScript/TypeScript syntax for writing asynchronous code sequentially; Playwright uses it to automatically wait for elements to be ready." }, chapter: "auto-1" },
  { term: "Promise", def: { es: "Objeto que representa la finalización (con éxito o error) futura de una operación asíncrona, como una petición de red.", en: "Object representing the future completion (success or failure) of an asynchronous operation, such as a network request." }, chapter: "auto-1" },
  { term: "Arrow function", def: { es: "Función con sintaxis compacta que no tiene su propio binding de 'this', evitando errores comunes al definir callbacks en los tests.", en: "Function with compact syntax that has no own 'this' binding, avoiding common errors when defining callbacks in tests." }, chapter: "auto-1" },

  /* ---------- Automation — Módulo 2 (Playwright Fundamentals) ---------- */
  { term: "Playwright", def: { es: "Framework de automatización de pruebas end-to-end de Microsoft, con soporte nativo multi-navegador y auto-waiting.", en: "Microsoft's end-to-end test automation framework, with native multi-browser support and auto-waiting." }, chapter: "auto-2" },
  { term: "Auto-waiting", def: { es: "Mecanismo por el que Playwright espera automáticamente a que un elemento esté visible, habilitado y estable antes de actuar sobre él.", en: "Mechanism by which Playwright automatically waits for an element to be visible, enabled and stable before acting on it." }, chapter: "auto-2" },
  { term: "Test runner (Playwright)", def: { es: "Motor que descubre, organiza y ejecuta los archivos de test mediante bloques 'describe', 'test', 'beforeEach' y 'afterEach'.", en: "Engine that discovers, organizes and runs test files via 'describe', 'test', 'beforeEach' and 'afterEach' blocks." }, chapter: "auto-2" },
  { term: "Modo headless", def: { es: "Ejecución de un navegador sin interfaz gráfica visible; más rápido y el modo por defecto en entornos de CI/CD.", en: "Running a browser without a visible GUI; faster, and the default mode in CI/CD environments." }, chapter: "auto-2" },
  { term: "Motor de navegador / Browser engine", def: { es: "Cada uno de los tres motores (Chromium, Firefox, WebKit) que Playwright soporta de forma nativa para ejecutar la misma suite de pruebas.", en: "Each of the three engines (Chromium, Firefox, WebKit) that Playwright natively supports for running the same test suite." }, chapter: "auto-2" },

  /* ---------- Automation — Módulo 3 (Locators and Selectors) ---------- */
  { term: "Locator (Playwright)", def: { es: "Objeto que representa cómo encontrar uno o varios elementos en la página en cualquier momento, sin apuntar a un nodo del DOM fijo.", en: "Object representing how to find one or more elements on the page at any time, without pointing to a fixed DOM node." }, chapter: "auto-3" },
  { term: "getByRole", def: { es: "Forma de localizar elementos recomendada por Playwright, basada en su rol ARIA implícito o explícito; favorece la accesibilidad.", en: "Playwright's recommended way to locate elements, based on their implicit or explicit ARIA role; favors accessibility." }, chapter: "auto-3" },
  { term: "getByText / getByLabel / getByPlaceholder", def: { es: "Localizadores que encuentran elementos por su texto visible, su etiqueta o su placeholder, igual que lo haría un usuario real.", en: "Locators that find elements by their visible text, label or placeholder, the same way a real user would." }, chapter: "auto-3" },
  { term: "Selector CSS/XPath", def: { es: "Mecanismo de localización de bajo nivel basado en la estructura del DOM; se recomienda evitarlo cuando existe una alternativa más semántica.", en: "Low-level locating mechanism based on DOM structure; recommended to avoid when a more semantic alternative exists." }, chapter: "auto-3" },
  { term: "Encadenamiento de localizadores", def: { es: "Técnica de combinar '.locator().locator()' para acotar la búsqueda de un elemento dentro de otro ya localizado.", en: "Technique of combining '.locator().locator()' to narrow the search for an element within another already-located one." }, chapter: "auto-3" },
  { term: "Filtrado de localizadores (.filter()/.nth())", def: { es: "Métodos para refinar un conjunto de elementos coincidentes hasta quedarse con uno específico.", en: "Methods for refining a set of matching elements down to one specific element." }, chapter: "auto-3" },

  /* ---------- Automation — Módulo 4 (Actions and Assertions) ---------- */
  { term: "expect() (Playwright)", def: { es: "Función de aserción que valida el estado esperado de la aplicación: visibilidad, texto, valor o atributos de un elemento.", en: "Assertion function that validates the application's expected state: an element's visibility, text, value or attributes." }, chapter: "auto-4" },
  { term: "Soft assertion", def: { es: "Aserción ('expect.soft()') que registra un fallo pero permite que el test siga ejecutándose en vez de detenerse en el primer error.", en: "Assertion ('expect.soft()') that records a failure but lets the test keep running instead of stopping at the first error." }, chapter: "auto-4" },
  { term: "Auto-waiting en aserciones", def: { es: "Comportamiento por el que 'expect()' reintenta automáticamente una condición hasta que se cumple o expira su timeout, sin esperas manuales.", en: "Behavior by which 'expect()' automatically retries a condition until it's met or its timeout expires, with no manual waits." }, chapter: "auto-4" },
  { term: "fill() vs type()", def: { es: "fill() rellena un campo de una vez; type() simula pulsaciones de teclado una a una, útil para probar autocompletados o validaciones en vivo.", en: "fill() fills a field in one go; type() simulates keystrokes one by one, useful for testing autocomplete or live validation." }, chapter: "auto-4" },
  { term: "Timeout de aserción", def: { es: "Tiempo máximo que 'expect()' reintenta una condición antes de fallar el test, configurable de forma independiente al timeout de las acciones.", en: "Maximum time 'expect()' retries a condition before failing the test, configurable independently from the action timeout." }, chapter: "auto-4" },

  /* ---------- Automation — Módulo 5 (Page Object Model) ---------- */
  { term: "Page Object Model (POM)", def: { es: "Patrón de diseño que encapsula los selectores y acciones de una página en una clase reutilizable, separando el 'qué' del 'cómo' en los tests.", en: "Design pattern that encapsulates a page's selectors and actions in a reusable class, separating the 'what' from the 'how' in tests." }, chapter: "auto-5" },
  { term: "Page class", def: { es: "Clase de TypeScript que representa una página o componente de la aplicación bajo prueba, exponiendo métodos de alto nivel en vez de selectores.", en: "TypeScript class representing a page or component of the application under test, exposing high-level methods instead of raw selectors." }, chapter: "auto-5" },
  { term: "Composición de Page Objects", def: { es: "Técnica por la que un page object devuelve otro page object, modelando de forma fluida la navegación entre páginas.", en: "Technique by which a page object returns another page object, fluently modeling navigation between pages." }, chapter: "auto-5" },
  { term: "POM con interfaces de TypeScript", def: { es: "Uso de interfaces para definir contratos claros entre los page objects y los tests que los consumen.", en: "Use of interfaces to define clear contracts between page objects and the tests that consume them." }, chapter: "auto-5" },
  { term: "Selectores encapsulados", def: { es: "Principio de POM por el que ningún test accede directamente a un selector: siempre pasa por un método del page object.", en: "POM principle by which no test accesses a selector directly: it always goes through a page object method." }, chapter: "auto-5" },

  /* ---------- Automation — Módulo 6 (Configuration and Environments) ---------- */
  { term: "playwright.config.ts", def: { es: "Archivo central de configuración de un proyecto Playwright: timeout, retries, workers, reporter y proyectos de navegador/dispositivo.", en: "Central configuration file of a Playwright project: timeout, retries, workers, reporter, and browser/device projects." }, chapter: "auto-6" },
  { term: "Proyecto (Playwright)", def: { es: "Configuración independiente definida en 'playwright.config.ts', típicamente asociada a un navegador o dispositivo concreto.", en: "Independent configuration defined in 'playwright.config.ts', typically tied to a specific browser or device." }, chapter: "auto-6" },
  { term: "Retries", def: { es: "Número de reintentos automáticos de un test fallido antes de marcarlo como definitivamente fallido; útil para mitigar flakiness en CI.", en: "Number of automatic re-runs of a failed test before marking it as definitively failed; useful for mitigating flakiness in CI." }, chapter: "auto-6" },
  { term: "Workers", def: { es: "Número de procesos que ejecutan tests en paralelo; más workers reducen el tiempo total de ejecución de la suite.", en: "Number of processes running tests in parallel; more workers reduce the suite's total execution time." }, chapter: "auto-6" },
  { term: "Variable de entorno (testing)", def: { es: "Valor externo (URL, credenciales, flags) inyectado en tiempo de ejecución, en vez de hardcodeado, para adaptar los tests a cada entorno (dev, staging, prod).", en: "External value (URL, credentials, flags) injected at runtime instead of hardcoded, to adapt tests to each environment (dev, staging, prod)." }, chapter: "auto-6" },

  /* ---------- Automation — Módulo 7 (API Testing with Playwright) ---------- */
  { term: "APIRequestContext", def: { es: "Cliente HTTP integrado de Playwright para realizar peticiones API directamente, sin necesidad de librerías externas.", en: "Playwright's built-in HTTP client for making API requests directly, without needing external libraries." }, chapter: "auto-7" },
  { term: "Petición HTTP (GET/POST/PUT/DELETE)", def: { es: "Las cuatro operaciones básicas para interactuar con una API REST, verificables en Playwright junto con sus códigos de estado y cuerpos de respuesta.", en: "The four basic operations for interacting with a REST API, verifiable in Playwright along with their status codes and response bodies." }, chapter: "auto-7" },
  { term: "Test híbrido UI+API", def: { es: "Test que combina interacciones de interfaz con llamadas API en el mismo flujo, para escenarios end-to-end más rápidos y fiables.", en: "Test that combines UI interactions with API calls in the same flow, for faster and more reliable end-to-end scenarios." }, chapter: "auto-7" },
  { term: "Mocking de respuestas (route.fulfill())", def: { es: "Técnica para simular la respuesta de un backend con 'route.fulfill()', permitiendo probar escenarios de error sin depender del servidor real.", en: "Technique for simulating a backend's response with 'route.fulfill()', allowing error scenarios to be tested without depending on the real server." }, chapter: "auto-7" },
  { term: "Código de estado HTTP", def: { es: "Valor numérico (200, 404, 500...) que indica el resultado de una petición API y que se verifica habitualmente en las aserciones del test.", en: "Numeric value (200, 404, 500...) indicating the result of an API request, commonly verified in the test's assertions." }, chapter: "auto-7" },

  /* ---------- Automation — Módulo 8 (CI/CD and Reporting) ---------- */
  { term: "Pipeline de CI/CD", def: { es: "Flujo automatizado que construye, prueba y despliega una aplicación en cada push o pull request.", en: "Automated flow that builds, tests and deploys an application on every push or pull request." }, chapter: "auto-8" },
  { term: "HTML Reporter", def: { es: "Informe nativo de Playwright con trazas, capturas de pantalla y vídeos de cada ejecución de test, especialmente útil para depurar fallos.", en: "Playwright's native report with traces, screenshots and videos of each test run, especially useful for debugging failures." }, chapter: "auto-8" },
  { term: "Trace Viewer", def: { es: "Herramienta para inspeccionar paso a paso la ejecución de un test fallido, incluso cuando se ejecutó en un pipeline de CI.", en: "Tool for inspecting a failed test's execution step by step, even when it ran in a CI pipeline." }, chapter: "auto-8" },
  { term: "Allure Reporter", def: { es: "Herramienta externa de generación de reportes con histórico de ejecuciones, gráficos de tendencia y categorización de fallos.", en: "External reporting tool with execution history, trend charts and failure categorization." }, chapter: "auto-8" },
  { term: "GitHub Actions", def: { es: "Servicio de CI/CD integrado en GitHub, usado para ejecutar la suite de tests automáticamente en cada cambio del repositorio.", en: "CI/CD service built into GitHub, used to automatically run the test suite on every repository change." }, chapter: "auto-8" },
];

export const CHAPTER_TITLES: Record<string, { es: string; en: string }> = {
  "1": { es: "Fundamentos del Testing", en: "Fundamentals of Testing" },
  "2": { es: "Testing a lo Largo del SDLC", en: "Testing Throughout the SDLC" },
  "3": { es: "Testing Estático", en: "Static Testing" },
  "4": { es: "Análisis y Diseño de Pruebas", en: "Test Analysis and Design" },
  "5": { es: "Gestión de Actividades de Prueba", en: "Managing Test Activities" },
  "6": { es: "Soporte de Herramientas al Testing", en: "Tool Support for Testing" },
  "qaf-1": { es: "Introducción al QA", en: "Introduction to QA" },
  "qaf-2": { es: "Calidad de Software", en: "Software Quality" },
  "qaf-3": { es: "SDLC y STLC", en: "SDLC and STLC" },
  "qaf-4": { es: "Análisis de Requisitos", en: "Requirements Analysis" },
  "qaf-5": { es: "Diseño de Casos de Prueba", en: "Test Case Design" },
  "qaf-6": { es: "Ejecución y Gestión de Defectos", en: "Test Execution and Defect Management" },
  "qaf-7": { es: "Metodologías Ágiles", en: "Agile Methodologies" },
  "qaf-8": { es: "Herramientas de QA Manual", en: "Manual QA Tools" },
  "qaf-9": { es: "Testing Web y Mobile", en: "Web and Mobile Testing" },
  "qaf-10": { es: "IA aplicada al QA", en: "AI Applied to QA" },
  "auto-1": { es: "Fundamentos de TypeScript para QA", en: "TypeScript Foundations for QA" },
  "auto-2": { es: "Fundamentos de Playwright", en: "Playwright Fundamentals" },
  "auto-3": { es: "Localizadores y Selectores", en: "Locators and Selectors" },
  "auto-4": { es: "Acciones y Aserciones", en: "Actions and Assertions" },
  "auto-5": { es: "Page Object Model", en: "Page Object Model" },
  "auto-6": { es: "Configuración y Entornos", en: "Configuration and Environments" },
  "auto-7": { es: "API Testing con Playwright", en: "API Testing with Playwright" },
  "auto-8": { es: "CI/CD y Reportes", en: "CI/CD and Reporting" },
};

export const GLOSSARY_CHAPTERS_BY_CAMPUS: Record<string, string[]> = {
  qaFundamentals: ["qaf-1", "qaf-2", "qaf-3", "qaf-4", "qaf-5", "qaf-6", "qaf-7", "qaf-8", "qaf-9", "qaf-10"],
  istqb: ["1", "2", "3", "4", "5", "6"],
  automation: ["auto-1", "auto-2", "auto-3", "auto-4", "auto-5", "auto-6", "auto-7", "auto-8"],
};
