import type { Bilingual } from "@/types/lesson";

export interface GlossaryEntry {
  term: string;
  def: Bilingual;
  chapter: string;
}

export const GLOSSARY: GlossaryEntry[] = [
  { term: "Testing / Prueba", def: { es: "Conjunto de actividades para descubrir defectos y evaluar la calidad de artefactos de software.", en: "Set of activities to discover defects and evaluate the quality of software artifacts." }, chapter: "1" },
  { term: "Defecto / Bug / Fault", def: { es: "Imperfección en un componente o sistema que puede causar que el componente o sistema falle en realizar su función requerida.", en: "Imperfection in a component or system that can cause it to fail to perform its required function." }, chapter: "1" },
  { term: "Error / Mistake", def: { es: "Acción humana que produce un resultado incorrecto, que introduce un defecto en el sistema.", en: "Human action that produces an incorrect result, introducing a defect into the system." }, chapter: "1" },
  { term: "Fallo / Failure", def: { es: "Evento en el cual un componente o sistema no realiza una función requerida dentro de los límites especificados.", en: "Event in which a component or system does not perform a required function within specified limits." }, chapter: "1" },
  { term: "Causa raíz / Root cause", def: { es: "Razón fundamental por la que ocurre un problema. La eliminación de la causa raíz evita la recurrencia del defecto.", en: "Fundamental reason why a problem occurs. Removing the root cause prevents defect recurrence." }, chapter: "1" },
  { term: "Calidad / Quality", def: { es: "Grado en el que un componente o sistema satisface las necesidades indicadas e implícitas de sus partes interesadas.", en: "Degree to which a component or system satisfies the stated and implied needs of its stakeholders." }, chapter: "1" },
  { term: "Aseguramiento de calidad / QA", def: { es: "Actividades que se centran en proporcionar confianza en que los requisitos de calidad se cumplirán.", en: "Activities focused on providing confidence that quality requirements will be fulfilled." }, chapter: "1" },
  { term: "Verificación / Verification", def: { es: "Confirmación de que el software cumple con los requisitos especificados.", en: "Confirmation that software meets specified requirements." }, chapter: "1" },
  { term: "Validación / Validation", def: { es: "Confirmación de que el software satisface las necesidades y expectativas del usuario o cliente.", en: "Confirmation that software satisfies the needs and expectations of the user or customer." }, chapter: "1" },
  { term: "Testware", def: { es: "Artefactos producidos durante el proceso de prueba: planes, casos, scripts, datos, informes.", en: "Artifacts produced during the test process: plans, cases, scripts, data, reports." }, chapter: "1" },
  { term: "Trazabilidad / Traceability", def: { es: "Capacidad de identificar relaciones entre productos de trabajo de testing y requisitos u otros artefactos.", en: "Ability to identify relationships between test work products and requirements or other artifacts." }, chapter: "1" },
  { term: "Prueba de componente / Unit test", def: { es: "Nivel de prueba que verifica componentes individuales del software en aislamiento.", en: "Test level that verifies individual software components in isolation." }, chapter: "2" },
  { term: "Prueba de integración / Integration test", def: { es: "Nivel de prueba que verifica la interacción entre componentes o sistemas integrados.", en: "Test level that verifies the interaction between integrated components or systems." }, chapter: "2" },
  { term: "Prueba de sistema / System test", def: { es: "Nivel de prueba que verifica el comportamiento del sistema completo de extremo a extremo.", en: "Test level that verifies the behavior of the complete system end-to-end." }, chapter: "2" },
  { term: "Prueba de aceptación / UAT", def: { es: "Nivel de prueba realizado para determinar si el sistema cumple con los criterios de aceptación del negocio.", en: "Test level performed to determine if the system meets business acceptance criteria." }, chapter: "2" },
  { term: "Testing funcional", def: { es: "Pruebas que verifican lo que el sistema HACE, basadas en las funciones requeridas.", en: "Tests that verify what the system DOES, based on required functions." }, chapter: "2" },
  { term: "Testing no funcional", def: { es: "Pruebas que verifican cómo se comporta el sistema (rendimiento, usabilidad, seguridad, fiabilidad).", en: "Tests that verify how the system behaves (performance, usability, security, reliability)." }, chapter: "2" },
  { term: "Testing de regresión", def: { es: "Pruebas que verifican que los cambios no han introducido nuevos defectos en áreas que funcionaban correctamente.", en: "Tests that verify changes haven't introduced new defects in areas that previously worked correctly." }, chapter: "2" },
  { term: "Testing de humo / Smoke test", def: { es: "Conjunto básico de pruebas que verifican las funcionalidades más críticas para confirmar que el sistema puede ser probado más a fondo.", en: "Basic set of tests verifying the most critical functionalities to confirm the system can be further tested." }, chapter: "2" },
  { term: "Alpha testing", def: { es: "Prueba de aceptación realizada por usuarios en el sitio del desarrollador.", en: "Acceptance testing performed by users at the developer's site." }, chapter: "2" },
  { term: "Beta testing", def: { es: "Prueba de aceptación realizada por usuarios en su propio entorno antes del lanzamiento general.", en: "Acceptance testing performed by users in their own environment before general release." }, chapter: "2" },
  { term: "Revisión / Review", def: { es: "Proceso estático que evalúa los productos de trabajo de software para encontrar defectos antes de la ejecución.", en: "Static process evaluating software work products to find defects before execution." }, chapter: "3" },
  { term: "Inspección / Inspection", def: { es: "Tipo más formal de revisión estática, con roles definidos, métricas y criterios de entrada/salida.", en: "Most formal type of static review, with defined roles, metrics and entry/exit criteria." }, chapter: "3" },
  { term: "Walkthrough", def: { es: "Tipo de revisión guiada por el autor, donde el equipo sigue la lógica del producto paso a paso.", en: "Review type guided by the author, where the team follows the product logic step by step." }, chapter: "3" },
  { term: "Análisis estático / Static analysis", def: { es: "Evaluación automatizada del código sin ejecutarlo, para detectar defectos de código y violaciones de estándares.", en: "Automated evaluation of code without executing it, to detect code defects and standard violations." }, chapter: "3" },
  { term: "Partición de equivalencia / EP", def: { es: "Técnica de caja negra que divide las entradas en particiones donde todos los valores se comportan igual.", en: "Black-box technique dividing inputs into partitions where all values behave the same." }, chapter: "4" },
  { term: "Análisis de valor límite / BVA", def: { es: "Técnica de caja negra que prueba los valores en los bordes de las particiones de equivalencia.", en: "Black-box technique testing values at the edges of equivalence partitions." }, chapter: "4" },
  { term: "Tabla de decisión / Decision table", def: { es: "Técnica de caja negra para probar combinaciones de condiciones lógicas y sus acciones resultantes.", en: "Black-box technique for testing combinations of logical conditions and their resulting actions." }, chapter: "4" },
  { term: "Transición de estado / State transition", def: { es: "Técnica de caja negra para probar sistemas cuyo comportamiento depende del estado actual y del evento recibido.", en: "Black-box technique for testing systems whose behavior depends on the current state and received event." }, chapter: "4" },
  { term: "Prueba de sentencia / Statement coverage", def: { es: "Técnica de caja blanca que mide el porcentaje de sentencias ejecutables ejecutadas por los tests.", en: "White-box technique measuring the percentage of executable statements executed by tests." }, chapter: "4" },
  { term: "Prueba de rama / Branch coverage", def: { es: "Técnica de caja blanca que mide el porcentaje de ramas del flujo de control ejecutadas (más fuerte que statement coverage).", en: "White-box technique measuring the percentage of control flow branches executed (stronger than statement coverage)." }, chapter: "4" },
  { term: "Testing exploratorio", def: { es: "Técnica basada en experiencia donde el diseño y la ejecución de pruebas ocurren simultáneamente, sin scripts predefinidos.", en: "Experience-based technique where test design and execution happen simultaneously, without predefined scripts." }, chapter: "4" },
  { term: "Error guessing / Adivinanza de errores", def: { es: "Técnica basada en experiencia donde el tester usa intuición y experiencia para anticipar tipos de errores comunes.", en: "Experience-based technique where the tester uses intuition and experience to anticipate common error types." }, chapter: "4" },
  { term: "ATDD", def: { es: "Acceptance Test-Driven Development: técnica donde los tests de aceptación se crean antes del desarrollo con participación de todo el equipo.", en: "Acceptance Test-Driven Development: technique where acceptance tests are created before development with full team participation." }, chapter: "4" },
  { term: "Plan de pruebas / Test plan", def: { es: "Documento que describe el enfoque, recursos, alcance, criterios y actividades de testing para un proyecto.", en: "Document describing the testing approach, resources, scope, criteria and activities for a project." }, chapter: "5" },
  { term: "Riesgo de producto / Product risk", def: { es: "Posibilidad de que el producto de software no cumpla con su función esperada o los requisitos de calidad.", en: "Possibility that the software product won't fulfill its expected function or quality requirements." }, chapter: "5" },
  { term: "Riesgo de proyecto / Project risk", def: { es: "Posibilidad de que el proyecto no logre sus objetivos de alcance, tiempo o presupuesto.", en: "Possibility that the project won't achieve its scope, time or budget objectives." }, chapter: "5" },
  { term: "Criterios de entrada / Entry criteria", def: { es: "Condiciones que deben cumplirse para iniciar una actividad de testing.", en: "Conditions that must be met to start a testing activity." }, chapter: "5" },
  { term: "Criterios de salida / Exit criteria", def: { es: "Condiciones que deben cumplirse para completar una actividad de testing.", en: "Conditions that must be met to complete a testing activity." }, chapter: "5" },
  { term: "Métricas de prueba / Test metrics", def: { es: "Medidas cuantitativas usadas para gestionar y controlar el proceso de testing (cobertura, densidad de defectos, etc.).", en: "Quantitative measures used to manage and control the test process (coverage, defect density, etc.)." }, chapter: "5" },
  { term: "Gestión de configuración / Config management", def: { es: "Disciplina para controlar y registrar la evolución de los artefactos de software y testware a lo largo del proyecto.", en: "Discipline for controlling and recording the evolution of software and testware artifacts throughout the project." }, chapter: "5" },
  { term: "Severidad / Severity", def: { es: "Grado de impacto técnico que tiene un defecto sobre el sistema.", en: "Degree of technical impact a defect has on the system." }, chapter: "5" },
  { term: "Prioridad / Priority", def: { es: "Urgencia con la que debe corregirse un defecto.", en: "Urgency with which a defect must be fixed." }, chapter: "5" },
  { term: "Gestión de defectos / Defect management", def: { es: "Proceso de capturar, investigar, resolver y cerrar los defectos encontrados durante el testing.", en: "Process of capturing, investigating, resolving and closing defects found during testing." }, chapter: "5" },
  { term: "Testing de rendimiento / Performance testing", def: { es: "Pruebas que evalúan la velocidad, escalabilidad y estabilidad del sistema bajo diferentes cargas.", en: "Tests that evaluate the speed, scalability and stability of the system under different loads." }, chapter: "2" },
  { term: "Shift-left testing", def: { es: "Enfoque donde el testing comienza lo antes posible en el SDLC para detectar defectos temprano y reducir costos.", en: "Approach where testing starts as early as possible in the SDLC to detect defects early and reduce costs." }, chapter: "2" },
  { term: "DevOps", def: { es: "Conjunto de prácticas que combina desarrollo de software y operaciones de TI para acortar el ciclo de vida del desarrollo.", en: "Set of practices combining software development and IT operations to shorten the development lifecycle." }, chapter: "2" },
  { term: "CI/CD", def: { es: "Integración Continua / Entrega Continua: prácticas de automatización que permiten integrar y desplegar cambios frecuentemente.", en: "Continuous Integration / Continuous Delivery: automation practices enabling frequent integration and deployment of changes." }, chapter: "2" },
];

export const CHAPTER_TITLES: Record<string, { es: string; en: string }> = {
  "1": { es: "Fundamentos del Testing", en: "Fundamentals of Testing" },
  "2": { es: "Testing a lo Largo del SDLC", en: "Testing Throughout the SDLC" },
  "3": { es: "Testing Estático", en: "Static Testing" },
  "4": { es: "Análisis y Diseño de Pruebas", en: "Test Analysis and Design" },
  "5": { es: "Gestión de Actividades de Prueba", en: "Managing Test Activities" },
  "6": { es: "Soporte de Herramientas al Testing", en: "Tool Support for Testing" },
};
