import type { Bilingual } from "@/types/lesson";

export interface GlossaryEntry {
  term: string;
  def: Bilingual;
  chapter: string;
}

export const GLOSSARY: GlossaryEntry[] = [
  { term: "Testing / Prueba", def: { es: "Conjunto de actividades para descubrir defectos y evaluar la calidad de artefactos de software.", en: "Set of activities to discover defects and evaluate the quality of software artifacts." }, chapter: "1" },
  { term: "Defecto / Bug / Fault", def: { es: "Imperfección en un componente o sistema que puede causar que el componente o sistema falle en realizar su función requerida.", en: "Imperfection in a component or system that can cause it to fail to perform its required function." }, chapter: "1" },
  { term: "Error / Mistake", def: { es: "Acción humana que produce un resultado incorrecto, que introduce un defecto en el sistema.", en: "Human action that produces an incorrect result, introducing a defect into the system." }, chapter: "1" },
  { term: "Fallo / Failure", def: { es: "Evento en el cual un componente o sistema no realiza una función requerida dentro de los límites especificados.", en: "Event in which a component or system does not perform a required function within specified limits." }, chapter: "1" },
  { term: "Causa raíz / Root cause", def: { es: "Razón fundamental por la que ocurre un problema. La eliminación de la causa raíz evita la recurrencia del defecto.", en: "Fundamental reason why a problem occurs. Removing the root cause prevents defect recurrence." }, chapter: "1" },
  { term: "Calidad / Quality", def: { es: "Grado en el que un componente o sistema satisface las necesidades indicadas e implícitas de sus partes interesadas.", en: "Degree to which a component or system satisfies the stated and implied needs of its stakeholders." }, chapter: "1" },
  { term: "Aseguramiento de calidad / QA", def: { es: "Actividades que se centran en proporcionar confianza en que los requisitos de calidad se cumplirán.", en: "Activities focused on providing confidence that quality requirements will be fulfilled." }, chapter: "1" },
  { term: "Verificación / Verification", def: { es: "Confirmación de que el software cumple con los requisitos especificados.", en: "Confirmation that software meets specified requirements." }, chapter: "1" },
  { term: "Validación / Validation", def: { es: "Confirmación de que el software satisface las necesidades y expectativas del usuario o cliente.", en: "Confirmation that software satisfies the needs and expectations of the user or customer." }, chapter: "1" },
  { term: "Testware", def: { es: "Artefactos producidos durante el proceso de prueba: planes, casos, scripts, datos, informes.", en: "Artifacts produced during the test process: plans, cases, scripts, data, reports." }, chapter: "1" },
  { term: "Trazabilidad / Traceability", def: { es: "Capacidad de identificar relaciones entre productos de trabajo de testing y requisitos u otros artefactos.", en: "Ability to identify relationships between test work products and requirements or other artifacts." }, chapter: "1" },
  { term: "Prueba de componente / Unit test", def: { es: "Nivel de prueba que verifica componentes individuales del software en aislamiento.", en: "Test level that verifies individual software components in isolation." }, chapter: "2" },
  { term: "Prueba de integración / Integration test", def: { es: "Nivel de prueba que verifica la interacción entre componentes o sistemas integrados.", en: "Test level that verifies the interaction between integrated components or systems." }, chapter: "2" },
  { term: "Prueba de sistema / System test", def: { es: "Nivel de prueba que verifica el comportamiento del sistema completo de extremo a extremo.", en: "Test level that verifies the behavior of the complete system end-to-end." }, chapter: "2" },
  { term: "Prueba de aceptación / UAT", def: { es: "Nivel de prueba realizado para determinar si el sistema cumple con los criterios de aceptación del negocio.", en: "Test level performed to determine if the system meets business acceptance criteria." }, chapter: "2" },
  { term: "Testing funcional", def: { es: "Pruebas que verifican lo que el sistema HACE, basadas en las funciones requeridas.", en: "Tests that verify what the system DOES, based on required functions." }, chapter: "2" },
  { term: "Testing no funcional", def: { es: "Pruebas que verifican cómo se comporta el sistema (rendimiento, usabilidad, seguridad, fiabilidad).", en: "Tests that verify how the system behaves (performance, usability, security, reliability)." }, chapter: "2" },
  { term: "Testing de regresión", def: { es: "Pruebas que verifican que los cambios no han introducido nuevos defectos en áreas que funcionaban correctamente.", en: "Tests that verify changes haven't introduced new defects in areas that previously worked correctly." }, chapter: "2" },
  { term: "Testing de humo / Smoke test", def: { es: "Conjunto básico de pruebas que verifican las funcionalidades más críticas para confirmar que el sistema puede ser probado más a fondo.", en: "Basic set of tests verifying the most critical functionalities to confirm the system can be further tested." }, chapter: "2" },
  { term: "Alpha testing", def: { es: "Prueba de aceptación realizada por usuarios en el sitio del desarrollador.", en: "Acceptance testing performed by users at the developer's site." }, chapter: "2" },
  { term: "Beta testing", def: { es: "Prueba de aceptación realizada por usuarios en su propio entorno antes del lanzamiento general.", en: "Acceptance testing performed by users in their own environment before general release." }, chapter: "2" },
  { term: "Revisión / Review", def: { es: "Proceso estático que evalúa los productos de trabajo de software para encontrar defectos antes de la ejecución.", en: "Static process evaluating software work products to find defects before execution." }, chapter: "3" },
  { term: "Inspección / Inspection", def: { es: "Tipo más formal de revisión estática, con roles definidos, métricas y criterios de entrada/salida.", en: "Most formal type of static review, with defined roles, metrics and entry/exit criteria." }, chapter: "3" },
  { term: "Walkthrough", def: { es: "Tipo de revisión guiada por el autor, donde el equipo sigue la lógica del producto paso a paso.", en: "Review type guided by the author, where the team follows the product logic step by step." }, chapter: "3" },
  { term: "Análisis estático / Static analysis", def: { es: "Evaluación automatizada del código sin ejecutarlo, para detectar defectos de código y violaciones de estándares.", en: "Automated evaluation of code without executing it, to detect code defects and standard violations." }, chapter: "3" },
  { term: "Partición de equivalencia / EP", def: { es: "Técnica de caja negra que divide las entradas en particiones donde todos los valores se comportan igual.", en: "Black-box technique dividing inputs into partitions where all values behave the same." }, chapter: "4" },
  { term: "Análisis de valor límite / BVA", def: { es: "Técnica de caja negra que prueba los valores en los bordes de las particiones de equivalencia.", en: "Black-box technique testing values at the edges of equivalence partitions." }, chapter: "4" },
  { term: "Tabla de decisión / Decision table", def: { es: "Técnica de caja negra para probar combinaciones de condiciones lógicas y sus acciones resultantes.", en: "Black-box technique for testing combinations of logical conditions and their resulting actions." }, chapter: "4" },
  { term: "Transición de estado / State transition", def: { es: "Técnica de caja negra para probar sistemas cuyo comportamiento depende del estado actual y del evento recibido.", en: "Black-box technique for testing systems whose behavior depends on the current state and received event." }, chapter: "4" },
  { term: "Prueba de sentencia / Statement coverage", def: { es: "Técnica de caja blanca que mide el porcentaje de sentencias ejecutables ejecutadas por los tests.", en: "White-box technique measuring the percentage of executable statements executed by tests." }, chapter: "4" },
  { term: "Prueba de rama / Branch coverage", def: { es: "Técnica de caja blanca que mide el porcentaje de ramas del flujo de control ejecutadas (más fuerte que statement coverage).", en: "White-box technique measuring the percentage of control flow branches executed (stronger than statement coverage)." }, chapter: "4" },
  { term: "Testing exploratorio", def: { es: "Técnica basada en experiencia donde el diseño y la ejecución de pruebas ocurren simultáneamente, sin scripts predefinidos.", en: "Experience-based technique where test design and execution happen simultaneously, without predefined scripts." }, chapter: "4" },
  { term: "Error guessing / Adivinanza de errores", def: { es: "Técnica basada en experiencia donde el tester usa intuición y experiencia para anticipar tipos de errores comunes.", en: "Experience-based technique where the tester uses intuition and experience to anticipate common error types." }, chapter: "4" },
  { term: "ATDD", def: { es: "Acceptance Test-Driven Development: técnica donde los tests de aceptación se crean antes del desarrollo con participación de todo el equipo.", en: "Acceptance Test-Driven Development: technique where acceptance tests are created before development with full team participation." }, chapter: "4" },
  { term: "Plan de pruebas / Test plan", def: { es: "Documento que describe el enfoque, recursos, alcance, criterios y actividades de testing para un proyecto.", en: "Document describing the testing approach, resources, scope, criteria and activities for a project." }, chapter: "5" },
  { term: "Riesgo de producto / Product risk", def: { es: "Posibilidad de que el producto de software no cumpla con su función esperada o los requisitos de calidad.", en: "Possibility that the software product won't fulfill its expected function or quality requirements." }, chapter: "5" },
  { term: "Riesgo de proyecto / Project risk", def: { es: "Posibilidad de que el proyecto no logre sus objetivos de alcance, tiempo o presupuesto.", en: "Possibility that the project won't achieve its scope, time or budget objectives." }, chapter: "5" },
  { term: "Criterios de entrada / Entry criteria", def: { es: "Condiciones que deben cumplirse para iniciar una actividad de testing.", en: "Conditions that must be met to start a testing activity." }, chapter: "5" },
  { term: "Criterios de salida / Exit criteria", def: { es: "Condiciones que deben cumplirse para completar una actividad de testing.", en: "Conditions that must be met to complete a testing activity." }, chapter: "5" },
  { term: "Métricas de prueba / Test metrics", def: { es: "Medidas cuantitativas usadas para gestionar y controlar el proceso de testing (cobertura, densidad de defectos, etc.).", en: "Quantitative measures used to manage and control the test process (coverage, defect density, etc.)." }, chapter: "5" },
  { term: "Gestión de configuración / Config management", def: { es: "Disciplina para controlar y registrar la evolución de los artefactos de software y testware a lo largo del proyecto.", en: "Discipline for controlling and recording the evolution of software and testware artifacts throughout the project." }, chapter: "5" },
  { term: "Severidad / Severity", def: { es: "Grado de impacto técnico que tiene un defecto sobre el sistema.", en: "Degree of technical impact a defect has on the system." }, chapter: "5" },
  { term: "Prioridad / Priority", def: { es: "Urgencia con la que debe corregirse un defecto.", en: "Urgency with which a defect must be fixed." }, chapter: "5" },
  { term: "Gestión de defectos / Defect management", def: { es: "Proceso de capturar, investigar, resolver y cerrar los defectos encontrados durante el testing.", en: "Process of capturing, investigating, resolving and closing defects found during testing." }, chapter: "5" },
  { term: "Testing de rendimiento / Performance testing", def: { es: "Pruebas que evalúan la velocidad, escalabilidad y estabilidad del sistema bajo diferentes cargas.", en: "Tests that evaluate the speed, scalability and stability of the system under different loads." }, chapter: "2" },
  { term: "Shift-left testing", def: { es: "Enfoque donde el testing comienza lo antes posible en el SDLC para detectar defectos temprano y reducir costos.", en: "Approach where testing starts as early as possible in the SDLC to detect defects early and reduce costs." }, chapter: "2" },
  { term: "DevOps", def: { es: "Conjunto de prácticas que combina desarrollo de software y operaciones de TI para acortar el ciclo de vida del desarrollo.", en: "Set of practices combining software development and IT operations to shorten the development lifecycle." }, chapter: "2" },
  { term: "CI/CD", def: { es: "Integración Continua / Entrega Continua: prácticas de automatización que permiten integrar y desplegar cambios frecuentemente.", en: "Continuous Integration / Continuous Delivery: automation practices enabling frequent integration and deployment of changes." }, chapter: "2" },

  /* ---------- QA Fundamentals — Módulo 1 ---------- */
  { term: "Control de calidad / QC", def: { es: "Actividades orientadas al producto para detectar defectos, comprobando el producto contra criterios definidos.", en: "Product-oriented activities to detect defects, checking the product against defined criteria." }, chapter: "qaf-1" },
  { term: "Mentalidad de testing / Testing mindset", def: { es: "Combinación de curiosidad, escepticismo profesional y atención al detalle, sin perder la colaboración.", en: "Combination of curiosity, professional skepticism and attention to detail, without losing collaboration." }, chapter: "qaf-1" },

  /* ---------- QA Fundamentals — Módulo 2 ---------- */
  { term: "SQuaRE / ISO 25010", def: { es: "Familia de normas ISO/IEC para requisitos y evaluación de calidad del software; 25010 define el modelo de calidad de producto.", en: "ISO/IEC family of standards for software quality requirements and evaluation; 25010 defines the product quality model." }, chapter: "qaf-2" },
  { term: "Adecuación funcional / Functional suitability", def: { es: "Característica de calidad que evalúa si las funciones del sistema hacen lo correcto.", en: "Quality characteristic evaluating whether the system's functions do the right thing." }, chapter: "qaf-2" },
  { term: "Usabilidad / Usability", def: { es: "Característica de calidad que evalúa la facilidad de aprendizaje y uso del sistema.", en: "Quality characteristic evaluating the system's ease of learning and use." }, chapter: "qaf-2" },
  { term: "Fiabilidad / Reliability", def: { es: "Característica de calidad relativa a la disponibilidad y la tolerancia a fallos del sistema.", en: "Quality characteristic regarding system availability and fault tolerance." }, chapter: "qaf-2" },
  { term: "Mantenibilidad / Maintainability", def: { es: "Característica de calidad que evalúa la facilidad para modificar y corregir el sistema.", en: "Quality characteristic evaluating how easily the system can be modified and fixed." }, chapter: "qaf-2" },
  { term: "Portabilidad / Portability", def: { es: "Característica de calidad que evalúa la adaptación del sistema a distintos entornos.", en: "Quality characteristic evaluating the system's adaptation to different environments." }, chapter: "qaf-2" },
  { term: "Coste de la calidad / Cost of quality", def: { es: "Coste de prevención y evaluación frente al coste de los fallos cuando el defecto llega al usuario.", en: "Cost of prevention and appraisal versus the cost of failures when the defect reaches the user." }, chapter: "qaf-2" },

  /* ---------- QA Fundamentals — Módulo 3 (SDLC y STLC) ---------- */
  { term: "Modelo en cascada / Waterfall model", def: { es: "Modelo de SDLC secuencial y lineal en el que cada fase (requisitos, diseño, desarrollo, pruebas, mantenimiento) se completa antes de iniciar la siguiente.", en: "Sequential, linear SDLC model where each phase (requirements, design, development, testing, maintenance) is completed before the next begins." }, chapter: "qaf-3" },
  { term: "Modelo en V / V-model", def: { es: "Modelo de SDLC en el que cada fase de desarrollo tiene asociado un nivel de prueba correspondiente, planificado y diseñado en paralelo a esa fase.", en: "SDLC model in which each development phase has a corresponding test level, planned and designed in parallel with that phase." }, chapter: "qaf-3" },
  { term: "Modelo iterativo-incremental / Iterative-incremental model", def: { es: "Modelo de SDLC en el que el software se construye y prueba en ciclos cortos y repetidos, entregando incrementos funcionales cada vez.", en: "SDLC model in which software is built and tested in short, repeated cycles, delivering functional increments each time." }, chapter: "qaf-3" },
  { term: "STLC / Ciclo de Vida del Testing", def: { es: "Secuencia de fases específicas del testing (análisis, diseño, implementación, ejecución, evaluación de criterios de salida y cierre) que ocurren dentro del SDLC.", en: "Sequence of testing-specific phases (analysis, design, implementation, execution, exit criteria evaluation and closure) that occur within the SDLC." }, chapter: "qaf-3" },
  { term: "Retest / Re-test", def: { es: "Repetición de una prueba que falló previamente para confirmar que el defecto corregido ya no se reproduce.", en: "Re-running a test that previously failed to confirm that the fixed defect no longer occurs." }, chapter: "qaf-3" },
  { term: "Análisis de pruebas / Test analysis", def: { es: "Fase del STLC en la que se determina QUÉ probar, identificando condiciones de prueba a partir de la base de pruebas.", en: "STLC phase in which it is determined WHAT to test, identifying test conditions from the test basis." }, chapter: "qaf-3" },
  { term: "Diseño de pruebas / Test design", def: { es: "Fase del STLC en la que se determina CÓMO probar: se diseñan los casos de prueba y se identifican los datos necesarios.", en: "STLC phase in which it is determined HOW to test: test cases are designed and the necessary data is identified." }, chapter: "qaf-3" },

  /* ---------- QA Fundamentals — Módulo 4 (Análisis de Requisitos) ---------- */
  { term: "Requisito funcional / Functional requirement", def: { es: "Especifica QUÉ debe hacer el sistema: una función, característica o comportamiento concreto.", en: "Specifies WHAT the system must do: a concrete function, feature or behavior." }, chapter: "qaf-4" },
  { term: "Requisito no funcional / Non-functional requirement", def: { es: "Especifica CÓMO debe comportarse el sistema: rendimiento, usabilidad, seguridad, fiabilidad, etc.", en: "Specifies HOW the system must behave: performance, usability, security, reliability, etc." }, chapter: "qaf-4" },
  { term: "Historia de usuario / User story", def: { es: "Descripción breve de una funcionalidad desde la perspectiva del usuario, habitualmente en formato 'Como... quiero... para...'.", en: "Short description of a feature from the user's perspective, typically in the format 'As a... I want... so that...'." }, chapter: "qaf-4" },
  { term: "Criterios de aceptación / Acceptance criteria", def: { es: "Condiciones específicas y verificables que una historia de usuario debe cumplir para considerarse correctamente implementada.", en: "Specific, verifiable conditions a user story must meet to be considered correctly implemented." }, chapter: "qaf-4" },
  { term: "Gherkin (Dado/Cuando/Entonces)", def: { es: "Lenguaje estructurado para escribir criterios de aceptación en formato Given/When/Then (Dado/Cuando/Entonces).", en: "Structured language for writing acceptance criteria in Given/When/Then format." }, chapter: "qaf-4" },
  { term: "Matriz de trazabilidad / Traceability matrix", def: { es: "Documento que relaciona cada requisito con sus casos de prueba correspondientes, para detectar requisitos sin cobertura.", en: "Document that relates each requirement to its corresponding test cases, to detect requirements without coverage." }, chapter: "qaf-4" },

  /* ---------- QA Fundamentals — Módulo 5 (Diseño de Casos de Prueba) ---------- */
  { term: "Caso de prueba / Test case", def: { es: "Conjunto de precondiciones, datos de entrada, pasos de ejecución y resultado esperado diseñado para verificar un objetivo de prueba concreto.", en: "Set of preconditions, input data, execution steps and expected result designed to verify a specific test objective." }, chapter: "qaf-5" },
  { term: "Precondición / Precondition", def: { es: "Estado o condición que debe cumplirse antes de ejecutar los pasos de un caso de prueba (p. ej. 'usuario con sesión iniciada').", en: "State or condition that must exist before running the steps of a test case (e.g. 'logged-in user')." }, chapter: "qaf-5" },
  { term: "Resultado esperado / Expected result", def: { es: "Salida o comportamiento que el sistema debería producir si funciona correctamente, definido antes de ejecutar la prueba.", en: "Output or behavior the system should produce if it works correctly, defined before the test is executed." }, chapter: "qaf-5" },
  { term: "Datos de prueba / Test data", def: { es: "Conjunto de valores de entrada necesarios para ejecutar un caso de prueba.", en: "Set of input values needed to execute a test case." }, chapter: "qaf-5" },
  { term: "Datos sintéticos / Synthetic data", def: { es: "Datos de prueba generados artificialmente, sin información real de clientes, usados por privacidad y disponibilidad.", en: "Artificially generated test data, without real customer information, used for privacy and availability reasons." }, chapter: "qaf-5" },

  /* ---------- QA Fundamentals — Módulo 6 (Ejecución y Gestión de Defectos) ---------- */
  { term: "Reporte de defecto / Bug report", def: { es: "Documento que describe un defecto encontrado: pasos para reproducir, resultado esperado, resultado real y evidencias.", en: "Document describing a found defect: steps to reproduce, expected result, actual result and evidence." }, chapter: "qaf-6" },
  { term: "Ciclo de vida del defecto / Defect lifecycle", def: { es: "Secuencia de estados por los que pasa un defecto desde que se reporta (nuevo) hasta que se cierra.", en: "Sequence of states a defect goes through from being reported (new) to being closed." }, chapter: "qaf-6" },
  { term: "Pasos para reproducir / Steps to reproduce", def: { es: "Secuencia mínima y precisa de acciones necesarias para que el defecto vuelva a manifestarse.", en: "Minimal, precise sequence of actions needed to make the defect occur again." }, chapter: "qaf-6" },
  { term: "Estado 'Bloqueado' / Blocked status", def: { es: "Estado de una prueba que no se pudo ejecutar por una causa externa, como un entorno caído o una dependencia no disponible.", en: "Status of a test that could not be run due to an external cause, such as a down environment or unavailable dependency." }, chapter: "qaf-6" },
  { term: "Tasa de fuga de defectos / Defect leakage", def: { es: "Métrica que mide los defectos no detectados durante el testing que llegan a producción.", en: "Metric that measures defects not caught during testing that reach production." }, chapter: "qaf-6" },

  /* ---------- QA Fundamentals — Módulo 7 (Metodologías Ágiles) ---------- */
  { term: "Manifiesto Ágil / Agile Manifesto", def: { es: "Declaración de cuatro valores y doce principios que guían el desarrollo de software ágil, publicada en 2001.", en: "Declaration of four values and twelve principles guiding agile software development, published in 2001." }, chapter: "qaf-7" },
  { term: "Scrum", def: { es: "Marco de trabajo ágil ligero, basado en sprints cortos, con roles, eventos y artefactos definidos.", en: "Lightweight agile framework based on short sprints, with defined roles, events and artifacts." }, chapter: "qaf-7" },
  { term: "Sprint", def: { es: "Periodo de tiempo fijo (normalmente entre 1 y 4 semanas) en el que el equipo Scrum crea un incremento de producto.", en: "Fixed time period (typically 1 to 4 weeks) in which the Scrum team creates a product increment." }, chapter: "qaf-7" },
  { term: "Retrospectiva del Sprint / Sprint Retrospective", def: { es: "Evento de Scrum al final del sprint donde el equipo inspecciona su forma de trabajar y planifica mejoras.", en: "Scrum event at the end of the sprint where the team inspects how it works and plans improvements." }, chapter: "qaf-7" },
  { term: "Kanban", def: { es: "Método de gestión del flujo de trabajo basado en visualizar el trabajo en un tablero y limitar el trabajo en curso (WIP).", en: "Workflow management method based on visualizing work on a board and limiting work in progress (WIP)." }, chapter: "qaf-7" },
  { term: "Límite WIP / WIP limit", def: { es: "Número máximo de elementos que pueden estar en una columna del tablero Kanban a la vez, para mejorar el flujo y revelar cuellos de botella.", en: "Maximum number of items allowed in a Kanban board column at a time, to improve flow and reveal bottlenecks." }, chapter: "qaf-7" },
  { term: "Definición de Terminado / Definition of Done (DoD)", def: { es: "Conjunto de criterios, incluido el testing, que una historia debe cumplir para considerarse completada.", en: "Set of criteria, including testing, that a story must meet to be considered complete." }, chapter: "qaf-7" },
  { term: "Definición de Preparado / Definition of Ready (DoR)", def: { es: "Conjunto de criterios que una historia debe cumplir antes de entrar en un sprint, para asegurar que es comprensible y estimable.", en: "Set of criteria a story must meet before entering a sprint, to ensure it is understandable and estimable." }, chapter: "qaf-7" },

  /* ---------- QA Fundamentals — Módulo 8 (Herramientas para QA Manual) ---------- */
  { term: "Jira", def: { es: "Herramienta de Atlassian para la gestión de issues (incluidos bugs), workflows y proyectos ágiles.", en: "Atlassian tool for managing issues (including bugs), workflows and agile projects." }, chapter: "qaf-8" },
  { term: "JQL (Jira Query Language)", def: { es: "Lenguaje de consulta de Jira para buscar y filtrar issues mediante criterios precisos.", en: "Jira's query language for searching and filtering issues with precise criteria." }, chapter: "qaf-8" },
  { term: "Confluence", def: { es: "Herramienta de Atlassian para documentación colaborativa: planes de prueba, estrategias y checklists.", en: "Atlassian tool for collaborative documentation: test plans, strategies and checklists." }, chapter: "qaf-8" },
  { term: "Azure Test Plans", def: { es: "Herramienta de Azure DevOps para gestionar planes, suites y casos de prueba manuales, y registrar su ejecución.", en: "Azure DevOps tool for managing manual test plans, suites and cases, and recording their execution." }, chapter: "qaf-8" },
  { term: "Test Suite (Azure Test Plans)", def: { es: "Conjunto de casos de prueba relacionados, agrupados dentro de un Test Plan en Azure Test Plans.", en: "Set of related test cases, grouped within a Test Plan in Azure Test Plans." }, chapter: "qaf-8" },

  /* ---------- QA Fundamentals — Módulo 9 (Testing Web y Mobile Manual) ---------- */
  { term: "DevTools (herramientas de desarrollador)", def: { es: "Conjunto de herramientas integradas en el navegador para inspeccionar elementos, consola, red y rendimiento.", en: "Set of tools built into the browser to inspect elements, console, network and performance." }, chapter: "qaf-9" },
  { term: "Testing cross-browser / Cross-browser testing", def: { es: "Comprobación de que un sitio web funciona y se ve correctamente en distintos navegadores.", en: "Checking that a website works and looks correct across different browsers." }, chapter: "qaf-9" },
  { term: "Diseño responsive / Responsive design", def: { es: "Diseño que adapta la interfaz a distintos tamaños de pantalla: móvil, tablet y escritorio.", en: "Design that adapts the interface to different screen sizes: mobile, tablet and desktop." }, chapter: "qaf-9" },
  { term: "Testing mobile / Mobile testing", def: { es: "Pruebas específicas de aplicaciones móviles: gestos táctiles, interrupciones, permisos y conectividad cambiante.", en: "Testing specific to mobile applications: touch gestures, interruptions, permissions and changing connectivity." }, chapter: "qaf-9" },
  { term: "WCAG (Pautas de Accesibilidad)", def: { es: "Web Content Accessibility Guidelines: estándar internacional de accesibilidad web, organizado en los principios POUR.", en: "Web Content Accessibility Guidelines: international web accessibility standard, organized around the POUR principles." }, chapter: "qaf-9" },
  { term: "POUR (Perceptible, Operable, Comprensible, Robusto)", def: { es: "Los cuatro principios en los que se organizan las WCAG: Perceptible, Operable, Comprensible y Robusto.", en: "The four principles WCAG is organized around: Perceivable, Operable, Understandable and Robust." }, chapter: "qaf-9" },

  /* ---------- QA Fundamentals — Módulo 10 (IA aplicada al QA) ---------- */
  { term: "IA generativa / Generative AI", def: { es: "Inteligencia artificial capaz de crear contenido nuevo (texto, código, datos) a partir de instrucciones (prompts).", en: "Artificial intelligence capable of creating new content (text, code, data) from instructions (prompts)." }, chapter: "qaf-10" },
  { term: "Prompt", def: { es: "Instrucción o conjunto de instrucciones dado a un modelo de IA para obtener una respuesta concreta.", en: "Instruction or set of instructions given to an AI model to obtain a specific response." }, chapter: "qaf-10" },
  { term: "Alucinación (IA) / Hallucination", def: { es: "Información plausible pero incorrecta o inventada generada por un modelo de IA.", en: "Plausible but incorrect or invented information generated by an AI model." }, chapter: "qaf-10" },
  { term: "'IA para QA' vs 'QA de IA' / 'AI for QA' vs 'QA of AI'", def: { es: "'IA para QA' usa la IA como herramienta para probar mejor; 'QA de IA' consiste en probar sistemas basados en IA.", en: "'AI for QA' uses AI as a tool to test better; 'QA of AI' means testing AI-based systems." }, chapter: "qaf-10" },
  { term: "Revisión humana / Human review", def: { es: "Verificación por parte de una persona del contenido generado por IA antes de usarlo; salvaguarda clave frente a alucinaciones y sesgos.", en: "A person's verification of AI-generated content before use; the key safeguard against hallucinations and bias." }, chapter: "qaf-10" },
  { term: "Dossier de QA / QA dossier", def: { es: "Conjunto de entregables de un proyecto de QA (análisis, casos, ejecución, defectos, informe) reunidos como evidencia del trabajo realizado.", en: "Set of deliverables from a QA project (analysis, cases, execution, defects, report) gathered as evidence of the work done." }, chapter: "qaf-10" },
];

export const CHAPTER_TITLES: Record<string, { es: string; en: string }> = {
  "1": { es: "Fundamentos del Testing", en: "Fundamentals of Testing" },
  "2": { es: "Testing a lo Largo del SDLC", en: "Testing Throughout the SDLC" },
  "3": { es: "Testing Estático", en: "Static Testing" },
  "4": { es: "Análisis y Diseño de Pruebas", en: "Test Analysis and Design" },
  "5": { es: "Gestión de Actividades de Prueba", en: "Managing Test Activities" },
  "6": { es: "Soporte de Herramientas al Testing", en: "Tool Support for Testing" },
  "qaf-1": { es: "QA Fundamentals — Introducción al QA", en: "QA Fundamentals — Introduction to QA" },
  "qaf-2": { es: "QA Fundamentals — Calidad de Software", en: "QA Fundamentals — Software Quality" },
  "qaf-3": { es: "QA Fundamentals — SDLC y STLC", en: "QA Fundamentals — SDLC and STLC" },
  "qaf-4": { es: "QA Fundamentals — Análisis de Requisitos", en: "QA Fundamentals — Requirements Analysis" },
  "qaf-5": { es: "QA Fundamentals — Diseño de Casos de Prueba", en: "QA Fundamentals — Test Case Design" },
  "qaf-6": { es: "QA Fundamentals — Ejecución y Gestión de Defectos", en: "QA Fundamentals — Test Execution and Defect Management" },
  "qaf-7": { es: "QA Fundamentals — Metodologías Ágiles", en: "QA Fundamentals — Agile Methodologies" },
  "qaf-8": { es: "QA Fundamentals — Herramientas de QA Manual", en: "QA Fundamentals — Manual QA Tools" },
  "qaf-9": { es: "QA Fundamentals — Testing Web y Mobile", en: "QA Fundamentals — Web and Mobile Testing" },
  "qaf-10": { es: "QA Fundamentals — IA aplicada al QA", en: "QA Fundamentals — AI Applied to QA" },
};
