/**
 * ISTQB CTFL — Banco de preguntas Módulo 1 (Fundamentos del Testing).
 * Cubre el Capítulo 1 del syllabus: qué es el testing, objetivos,
 * error/defecto/fallo, los 7 principios, actividades/testware/roles y habilidades.
 * Fuentes: ISTQB CTFL v4.0 Syllabus (cap. 1), ISTQB Glossary.
 */

import type { ExamQuestion } from "@/types/exam";
import { registerQuestions } from "@/lib/exam/scoring";

const M = ["istqb-fundamentals"];

const QUESTIONS: ExamQuestion[] = [
  {
    id: "istqb-m1-e1",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "Según el ISTQB, ¿cuál es un objetivo típico del testing?", en: "According to ISTQB, which is a typical objective of testing?" },
    options: [
      { id: "a", text: { es: "Demostrar que el software no tiene ningún defecto", en: "Prove the software has no defects at all" } },
      { id: "b", text: { es: "Evaluar la calidad y reducir el riesgo de fallos en operación", en: "Evaluate quality and reduce the risk of failures in operation" } },
      { id: "c", text: { es: "Corregir los defectos encontrados en el código", en: "Fix the defects found in the code" } },
      { id: "d", text: { es: "Sustituir las revisiones de requisitos", en: "Replace requirements reviews" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El testing evalúa la calidad y reduce el riesgo; no demuestra ausencia de defectos ni corrige el código (eso es debugging).", en: "Testing evaluates quality and reduces risk; it does not prove absence of defects nor fix code (that is debugging)." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m1-e2",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿En qué se diferencian el testing y la depuración (debugging)?", en: "How do testing and debugging differ?" },
    options: [
      { id: "a", text: { es: "Son sinónimos exactos", en: "They are exact synonyms" } },
      { id: "b", text: { es: "El testing provoca fallos; el debugging localiza y corrige el defecto que los causa", en: "Testing causes failures; debugging locates and fixes the defect that causes them" } },
      { id: "c", text: { es: "El debugging lo hace siempre el tester", en: "Debugging is always done by the tester" } },
      { id: "d", text: { es: "El testing solo se aplica a documentos", en: "Testing only applies to documents" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El testing dinámico puede revelar fallos causados por defectos; el debugging es la actividad de desarrollo para encontrar, analizar y corregir esos defectos.", en: "Dynamic testing can reveal failures caused by defects; debugging is the development activity to find, analyze and fix those defects." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m1-e3",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "Una persona comete una equivocación que introduce un problema en el código. ¿Cómo se llama ese problema en el código?", en: "A person makes a mistake that introduces a problem in the code. What is that problem in the code called?" },
    options: [
      { id: "a", text: { es: "Error", en: "Error" } },
      { id: "b", text: { es: "Defecto", en: "Defect" } },
      { id: "c", text: { es: "Fallo", en: "Failure" } },
      { id: "d", text: { es: "Anomalía de entorno", en: "Environmental anomaly" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El error (mistake) humano introduce un defecto (defect/bug) en el código; si ese defecto se ejecuta puede producir un fallo (failure).", en: "The human error (mistake) introduces a defect (bug) in the code; if executed, that defect may produce a failure." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m1-e4",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Cuántos principios del testing define el ISTQB?", en: "How many testing principles does ISTQB define?" },
    options: [
      { id: "a", text: { es: "5", en: "5" } },
      { id: "b", text: { es: "7", en: "7" } },
      { id: "c", text: { es: "9", en: "9" } },
      { id: "d", text: { es: "12", en: "12" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El syllabus v4.0 describe 7 principios del testing.", en: "The v4.0 syllabus describes 7 testing principles." },
    points: 1,
    timeEstimateSeconds: 30,
  },
  {
    id: "istqb-m1-e5",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Cuál de los siguientes es un ejemplo de testware?", en: "Which of the following is an example of testware?" },
    options: [
      { id: "a", text: { es: "El código fuente de la aplicación", en: "The application source code" } },
      { id: "b", text: { es: "Los casos de prueba y los datos de prueba", en: "Test cases and test data" } },
      { id: "c", text: { es: "El servidor de producción", en: "The production server" } },
      { id: "d", text: { es: "El contrato con el cliente", en: "The customer contract" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El testware son los productos de trabajo generados por las actividades de testing: planes, casos, datos, scripts, informes, etc.", en: "Testware are the work products produced by testing activities: plans, cases, data, scripts, reports, etc." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m1-e6",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "Un sistema sin defectos conocidos pero que no satisface las necesidades del usuario ilustra…", en: "A system with no known defects that still fails to meet user needs illustrates…" },
    options: [
      { id: "a", text: { es: "La paradoja del pesticida", en: "The pesticide paradox" } },
      { id: "b", text: { es: "La falacia de ausencia de errores", en: "The absence-of-errors fallacy" } },
      { id: "c", text: { es: "La agrupación de defectos", en: "Defect clustering" } },
      { id: "d", text: { es: "El testing exhaustivo", en: "Exhaustive testing" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "Principio 7: corregir muchos defectos no ayuda si el sistema es inusable o no cubre las necesidades reales.", en: "Principle 7: fixing many defects does not help if the system is unusable or fails to meet real needs." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m1-e7",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "Las pruebas se concentran donde históricamente aparecen más defectos. ¿Qué principio aplica?", en: "Testing focuses where defects historically cluster. Which principle applies?" },
    options: [
      { id: "a", text: { es: "Agrupación de defectos", en: "Defect clustering" } },
      { id: "b", text: { es: "Paradoja del pesticida", en: "Pesticide paradox" } },
      { id: "c", text: { es: "Testing temprano", en: "Early testing" } },
      { id: "d", text: { es: "El testing exhaustivo es imposible", en: "Exhaustive testing is impossible" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La agrupación de defectos (defect clustering): un pequeño número de módulos suele concentrar la mayoría de los defectos.", en: "Defect clustering: a small number of modules usually contains most of the defects." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m1-e8",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Por qué el principio de 'testing temprano' (shift-left) ahorra costes?", en: "Why does the 'early testing' (shift-left) principle save costs?" },
    options: [
      { id: "a", text: { es: "Porque permite probar menos", en: "Because it allows testing less" } },
      { id: "b", text: { es: "Porque corregir un defecto cuesta más cuanto más tarde se detecta", en: "Because fixing a defect costs more the later it is detected" } },
      { id: "c", text: { es: "Porque elimina la necesidad de pruebas dinámicas", en: "Because it removes the need for dynamic testing" } },
      { id: "d", text: { es: "Porque garantiza cero defectos", en: "Because it guarantees zero defects" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "Detectar y corregir defectos pronto (incluso en requisitos) es mucho más barato que hacerlo en producción.", en: "Finding and fixing defects early (even in requirements) is far cheaper than doing so in production." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m1-e9",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "En el enfoque de equipo completo (whole-team approach), ¿quién es responsable de la calidad?", en: "In the whole-team approach, who is responsible for quality?" },
    options: [
      { id: "a", text: { es: "Solo el equipo de testing", en: "Only the testing team" } },
      { id: "b", text: { es: "Solo el responsable de calidad", en: "Only the quality manager" } },
      { id: "c", text: { es: "Todo el equipo de forma compartida", en: "The whole team, as a shared responsibility" } },
      { id: "d", text: { es: "Solo el Product Owner", en: "Only the Product Owner" } },
    ],
    correctOptionIds: ["c"],
    explanation: { es: "El whole-team approach establece que cualquier miembro con el conocimiento adecuado puede realizar tareas de testing y que la calidad es responsabilidad compartida.", en: "The whole-team approach states that any member with the right knowledge can perform testing tasks and that quality is a shared responsibility." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m1-e10",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Cuál es un beneficio de la independencia del testing?", en: "What is a benefit of testing independence?" },
    options: [
      { id: "a", text: { es: "Reduce el coste a cero", en: "It reduces cost to zero" } },
      { id: "b", text: { es: "Permite reconocer tipos de defectos distintos a los que ve el autor por sus sesgos", en: "It helps recognize different defect types than the author would, due to author bias" } },
      { id: "c", text: { es: "Elimina la necesidad de comunicación", en: "It removes the need for communication" } },
      { id: "d", text: { es: "Garantiza que no haya regresiones", en: "It guarantees no regressions" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "Una mirada independiente reduce el sesgo del autor y suele encontrar defectos distintos, aunque puede aislar al tester del equipo si es excesiva.", en: "An independent view reduces author bias and often finds different defects, though excessive independence can isolate the tester from the team." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-m1-e11",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "El equipo repite siempre el mismo conjunto de pruebas y deja de encontrar defectos nuevos. ¿Qué recomienda el principio aplicable?", en: "The team keeps running the same test set and stops finding new defects. What does the applicable principle recommend?" },
    options: [
      { id: "a", text: { es: "Dejar de probar, ya no hay defectos", en: "Stop testing, there are no more defects" } },
      { id: "b", text: { es: "Revisar y actualizar los casos de prueba, y crear nuevos", en: "Review and update the test cases, and create new ones" } },
      { id: "c", text: { es: "Aumentar solo el número de ejecuciones", en: "Only increase the number of executions" } },
      { id: "d", text: { es: "Cambiar de herramienta de gestión", en: "Switch the management tool" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "La paradoja del pesticida: los casos repetidos dejan de hallar defectos nuevos; hay que renovarlos y diseñar pruebas nuevas para cubrir otras áreas.", en: "The pesticide paradox: repeated cases stop finding new defects; they must be revised and new tests designed to cover other areas." },
    points: 3,
    timeEstimateSeconds: 55,
  },
  {
    id: "istqb-m1-e12",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "¿Cuál de estas afirmaciones describe correctamente la relación verificación/validación?", en: "Which statement correctly describes the verification/validation relationship?" },
    options: [
      { id: "a", text: { es: "Verificación = '¿construimos el producto correcto?'; validación = '¿lo construimos correctamente?'", en: "Verification = 'are we building the right product?'; validation = 'are we building it right?'" } },
      { id: "b", text: { es: "Verificación = '¿lo construimos correctamente?'; validación = '¿construimos el producto correcto?'", en: "Verification = 'are we building it right?'; validation = 'are we building the right product?'" } },
      { id: "c", text: { es: "Ambas significan exactamente lo mismo", en: "Both mean exactly the same thing" } },
      { id: "d", text: { es: "Validación solo aplica al código, verificación solo a documentos", en: "Validation only applies to code, verification only to documents" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "Verificación comprueba que se cumplen los requisitos especificados ('construirlo bien'); validación comprueba que se satisfacen las necesidades reales del usuario ('construir lo correcto').", en: "Verification checks that specified requirements are met ('building it right'); validation checks that real user needs are satisfied ('building the right thing')." },
    points: 3,
    timeEstimateSeconds: 60,
  },
];

registerQuestions(QUESTIONS);

export default QUESTIONS;
