/**
 * ISTQB CTFL — Banco de preguntas Módulo 5 (Gestión de Actividades de Prueba).
 * Cubre el Capítulo 5 del syllabus: planificación, criterios de entrada/salida,
 * estimación, priorización, gestión de riesgos, monitoreo/control/completitud,
 * gestión de la configuración y gestión de defectos.
 * Fuentes: ISTQB CTFL v4.0 Syllabus (cap. 5), ISTQB Glossary.
 */

import type { ExamQuestion } from "@/types/exam";
import { registerQuestions } from "@/lib/exam/scoring";

const M = ["istqb-management"];

const QUESTIONS: ExamQuestion[] = [
  {
    id: "istqb-m5-e1",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Cuál es el propósito principal de un plan de pruebas?", en: "What is the main purpose of a test plan?" },
    options: [
      { id: "a", text: { es: "Documentar los objetivos, alcance, enfoque y recursos del testing", en: "Document the objectives, scope, approach and resources of testing" } },
      { id: "b", text: { es: "Escribir el código de la aplicación", en: "Write the application code" } },
      { id: "c", text: { es: "Reemplazar los casos de prueba", en: "Replace the test cases" } },
      { id: "d", text: { es: "Garantizar cero defectos", en: "Guarantee zero defects" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "El plan de pruebas describe objetivos, alcance, enfoque, recursos, cronograma y criterios; guía y comunica la estrategia de testing.", en: "The test plan describes objectives, scope, approach, resources, schedule and criteria; it guides and communicates the testing strategy." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m5-e2",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Qué definen los criterios de entrada (entry criteria) y de salida (exit criteria)?", en: "What do entry criteria and exit criteria define?" },
    options: [
      { id: "a", text: { es: "Las condiciones para empezar y para dar por terminada una actividad de prueba", en: "The conditions to start and to consider a test activity complete" } },
      { id: "b", text: { es: "El número exacto de defectos permitidos", en: "The exact number of allowed defects" } },
      { id: "c", text: { es: "El presupuesto del proyecto", en: "The project budget" } },
      { id: "d", text: { es: "El lenguaje de programación a usar", en: "The programming language to use" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Los criterios de entrada (definition of ready) marcan cuándo se puede empezar; los de salida (definition of done) cuándo se puede considerar finalizada.", en: "Entry criteria (definition of ready) mark when to start; exit criteria (definition of done) mark when an activity can be considered finished." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m5-e3",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "Según el ISTQB, el nivel de riesgo se determina por…", en: "According to ISTQB, the level of risk is determined by…" },
    options: [
      { id: "a", text: { es: "La probabilidad de que ocurra y el impacto (daño) si ocurre", en: "The likelihood of occurrence and the impact (harm) if it occurs" } },
      { id: "b", text: { es: "Solo el coste del proyecto", en: "Only the project cost" } },
      { id: "c", text: { es: "El número de testers", en: "The number of testers" } },
      { id: "d", text: { es: "La cantidad de líneas de código", en: "The number of lines of code" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Riesgo = probabilidad × impacto. El testing basado en riesgos prioriza según ese nivel.", en: "Risk = likelihood × impact. Risk-based testing prioritizes according to that level." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m5-e4",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "Un retraso del proveedor que amenaza el cronograma es un ejemplo de…", en: "A supplier delay that threatens the schedule is an example of…" },
    options: [
      { id: "a", text: { es: "Riesgo de proyecto", en: "Project risk" } },
      { id: "b", text: { es: "Riesgo de producto", en: "Product risk" } },
      { id: "c", text: { es: "Defecto de código", en: "Code defect" } },
      { id: "d", text: { es: "Criterio de salida", en: "Exit criterion" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Los riesgos de proyecto afectan a la capacidad de gestionar el proyecto (plazos, recursos, proveedores); los de producto afectan a la calidad del producto.", en: "Project risks affect the ability to manage the project (schedule, resources, suppliers); product risks affect the product's quality." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m5-e5",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Qué información NO debería faltar en un buen reporte de defecto?", en: "What information should a good defect report NOT lack?" },
    options: [
      { id: "a", text: { es: "Pasos para reproducir, resultado esperado y resultado real", en: "Steps to reproduce, expected result and actual result" } },
      { id: "b", text: { es: "El salario del desarrollador", en: "The developer's salary" } },
      { id: "c", text: { es: "El número de testers del equipo", en: "The number of testers on the team" } },
      { id: "d", text: { es: "El presupuesto anual", en: "The annual budget" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Un reporte útil incluye identificador, pasos para reproducir, resultado esperado vs. real, severidad/prioridad y entorno.", en: "A useful report includes an identifier, steps to reproduce, expected vs. actual result, severity/priority and environment." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m5-e6",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿En qué consiste el testing basado en riesgos?", en: "What does risk-based testing involve?" },
    options: [
      { id: "a", text: { es: "Usar el nivel de riesgo para priorizar y asignar el esfuerzo de pruebas", en: "Using the risk level to prioritize and allocate the test effort" } },
      { id: "b", text: { es: "Probar siempre todo por igual", en: "Always testing everything equally" } },
      { id: "c", text: { es: "Eliminar las pruebas de las áreas críticas", en: "Removing testing from critical areas" } },
      { id: "d", text: { es: "Probar solo lo que pide el desarrollador", en: "Testing only what the developer requests" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "El risk-based testing concentra el esfuerzo donde el riesgo (probabilidad × impacto) es mayor, optimizando recursos limitados.", en: "Risk-based testing concentrates effort where risk (likelihood × impact) is highest, optimizing limited resources." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m5-e7",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "Según la pirámide de pruebas, ¿qué nivel debería tener MÁS pruebas?", en: "According to the test pyramid, which level should have the MOST tests?" },
    options: [
      { id: "a", text: { es: "Pruebas unitarias / de componente (base)", en: "Unit / component tests (base)" } },
      { id: "b", text: { es: "Pruebas de UI end-to-end (cima)", en: "End-to-end UI tests (top)" } },
      { id: "c", text: { es: "Pruebas manuales exploratorias", en: "Manual exploratory tests" } },
      { id: "d", text: { es: "Todas por igual", en: "All equally" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La pirámide propone muchas pruebas unitarias rápidas en la base y pocas pruebas de UI lentas en la cima.", en: "The pyramid proposes many fast unit tests at the base and few slow UI tests at the top." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m5-e8",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Cuál es una técnica de estimación del esfuerzo de pruebas reconocida por el ISTQB?", en: "Which is a test effort estimation technique recognized by ISTQB?" },
    options: [
      { id: "a", text: { es: "Estimación basada en métricas y estimación basada en expertos", en: "Metrics-based and expert-based estimation" } },
      { id: "b", text: { es: "Adivinación aleatoria sin datos", en: "Random guessing with no data" } },
      { id: "c", text: { es: "Copiar el plan de otro proyecto sin ajustarlo", en: "Copying another project's plan without adjusting it" } },
      { id: "d", text: { es: "No estimar nunca", en: "Never estimating" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "El syllabus menciona la estimación basada en métricas (datos históricos) y basada en expertos (juicio del equipo), entre otras.", en: "The syllabus mentions metrics-based (historical data) and expert-based (team judgment) estimation, among others." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m5-e9",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Cuál es la diferencia entre monitoreo y control de pruebas?", en: "What is the difference between test monitoring and test control?" },
    options: [
      { id: "a", text: { es: "El monitoreo recoge información del progreso; el control toma acciones correctivas a partir de ella", en: "Monitoring gathers progress information; control takes corrective actions based on it" } },
      { id: "b", text: { es: "Son exactamente lo mismo", en: "They are exactly the same" } },
      { id: "c", text: { es: "El control recoge datos y el monitoreo no hace nada", en: "Control gathers data and monitoring does nothing" } },
      { id: "d", text: { es: "Ambos solo ocurren al final del proyecto", en: "Both only happen at the end of the project" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "El monitoreo mide el progreso frente al plan; el control usa esa información para decidir acciones (re-priorizar, ajustar alcance, etc.).", en: "Monitoring measures progress against the plan; control uses that information to decide actions (re-prioritize, adjust scope, etc.)." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-m5-e10",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Cuál es el propósito de la gestión de la configuración en testing?", en: "What is the purpose of configuration management in testing?" },
    options: [
      { id: "a", text: { es: "Identificar y controlar versiones del testware y de los elementos de prueba para garantizar trazabilidad", en: "Identify and control versions of testware and test items to ensure traceability" } },
      { id: "b", text: { es: "Eliminar la necesidad de planes de prueba", en: "Remove the need for test plans" } },
      { id: "c", text: { es: "Decidir el sueldo del equipo", en: "Decide the team's salary" } },
      { id: "d", text: { es: "Ejecutar las pruebas automáticamente", en: "Run the tests automatically" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La gestión de la configuración mantiene la integridad y trazabilidad de los productos de trabajo (testware, builds, entornos) a lo largo del proyecto.", en: "Configuration management maintains the integrity and traceability of work products (testware, builds, environments) throughout the project." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-m5-e11",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Cuál es la diferencia entre severidad y prioridad de un defecto?", en: "What is the difference between a defect's severity and priority?" },
    options: [
      { id: "a", text: { es: "La severidad mide el impacto técnico; la prioridad, la urgencia de corregirlo desde el negocio", en: "Severity measures the technical impact; priority measures how urgent it is to fix from the business view" } },
      { id: "b", text: { es: "Son sinónimos", en: "They are synonyms" } },
      { id: "c", text: { es: "La prioridad mide el impacto técnico y la severidad la urgencia", en: "Priority measures technical impact and severity measures urgency" } },
      { id: "d", text: { es: "Ninguna se usa en la gestión de defectos", en: "Neither is used in defect management" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Severidad = gravedad del impacto en el sistema; prioridad = urgencia/orden de corrección desde la perspectiva de negocio. Pueden no coincidir.", en: "Severity = how serious the impact on the system is; priority = urgency/order of fixing from the business perspective. They may differ." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-m5-e12",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "Un fallo de seguridad permite ver datos de otros usuarios, pero ocurre en una pantalla casi nunca usada. ¿Cómo se clasifican severidad y prioridad?", en: "A security flaw exposes other users' data, but occurs on a rarely used screen. How are severity and priority classified?" },
    options: [
      { id: "a", text: { es: "Severidad alta (impacto grave) y prioridad alta (riesgo de seguridad, debe corregirse pronto)", en: "High severity (serious impact) and high priority (security risk, must be fixed soon)" } },
      { id: "b", text: { es: "Severidad baja y prioridad baja, porque casi nadie la usa", en: "Low severity and low priority, because almost nobody uses it" } },
      { id: "c", text: { es: "Severidad baja y prioridad alta", en: "Low severity and high priority" } },
      { id: "d", text: { es: "No es un defecto", en: "It is not a defect" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La exposición de datos es de severidad alta por su impacto; aunque la pantalla se use poco, el riesgo de seguridad justifica prioridad alta de corrección.", en: "Data exposure is high severity for its impact; even if the screen is rarely used, the security risk justifies a high fix priority." },
    points: 3,
    timeEstimateSeconds: 60,
  },
  {
    id: "istqb-m5-e13",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "El plan dice 'finalizar cuando el 95% de los casos críticos pasen y no queden defectos abiertos de severidad alta'. ¿Qué representa esa frase?", en: "The plan says 'finish when 95% of critical cases pass and no high-severity defects remain open'. What does that phrase represent?" },
    options: [
      { id: "a", text: { es: "Criterios de salida (exit criteria)", en: "Exit criteria" } },
      { id: "b", text: { es: "Criterios de entrada (entry criteria)", en: "Entry criteria" } },
      { id: "c", text: { es: "Un riesgo de proyecto", en: "A project risk" } },
      { id: "d", text: { es: "Una técnica de caja blanca", en: "A white-box technique" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Definen cuándo se puede dar por completada la actividad de prueba: son criterios de salida medibles.", en: "They define when the test activity can be considered complete: they are measurable exit criteria." },
    points: 3,
    timeEstimateSeconds: 55,
  },
  {
    id: "istqb-m5-e14",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "¿Qué afirmación sobre la priorización de casos de prueba es correcta?", en: "Which statement about test case prioritization is correct?" },
    options: [
      { id: "a", text: { es: "Permite ejecutar primero los casos de mayor valor/riesgo cuando el tiempo es limitado", en: "It lets you run the highest-value/risk cases first when time is limited" } },
      { id: "b", text: { es: "Obliga a ejecutar siempre todos los casos en orden alfabético", en: "It forces running all cases in alphabetical order" } },
      { id: "c", text: { es: "Solo aplica a pruebas unitarias", en: "It only applies to unit tests" } },
      { id: "d", text: { es: "Elimina la necesidad de gestión de riesgos", en: "It removes the need for risk management" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Estrategias como priorización por riesgo, por cobertura o por requisitos aseguran que, si falta tiempo, ya se ejecutó lo más importante.", en: "Strategies like risk-based, coverage-based or requirements-based prioritization ensure that, if time runs out, the most important cases already ran." },
    points: 3,
    timeEstimateSeconds: 55,
  },
];

registerQuestions(QUESTIONS);

export default QUESTIONS;
