/**
 * ISTQB CTFL — Banco general ampliado (preguntas adicionales para los simulacros).
 * Cada pregunta está etiquetada a su capítulo real del syllabus v4.0, por lo que
 * también enriquece el examen por módulo correspondiente. Aporta una mezcla de
 * dificultades (easy/medium/hard) para equilibrar la distribución de los simulacros.
 * Fuentes: ISTQB CTFL v4.0 Syllabus, ISTQB Glossary.
 */

import type { ExamQuestion } from "@/types/exam";
import { registerQuestions } from "@/lib/exam/scoring";

const FUND = ["istqb-fundamentals"];      // Cap. 1 — Fundamentos del Testing
const SDLC = ["istqb-sdlc"];              // Cap. 2 — Testing a lo Largo del SDLC
const STATIC = ["istqb-static-testing"];  // Cap. 3 — Testing Estático
const ANALYSIS = ["istqb-test-analysis"]; // Cap. 4 — Análisis y Diseño de Pruebas
const MGMT = ["istqb-management"];        // Cap. 5 — Gestión de Actividades de Prueba
const TOOLS = ["istqb-tools"];            // Cap. 6 — Soporte de Herramientas

const QUESTIONS: ExamQuestion[] = [
  // ───────────────────────── Capítulo 1 — Fundamentos ─────────────────────────
  {
    id: "istqb-x1",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: FUND,
    question: { es: "El principio 'el testing exhaustivo es imposible' implica que…", en: "The principle 'exhaustive testing is impossible' implies that…" },
    options: [
      { id: "a", text: { es: "Debemos priorizar pruebas según riesgo y prioridades en lugar de probarlo todo", en: "We must prioritize tests by risk and priorities instead of testing everything" } },
      { id: "b", text: { es: "Probar todo es siempre obligatorio", en: "Testing everything is always mandatory" } },
      { id: "c", text: { es: "El testing no aporta valor", en: "Testing adds no value" } },
      { id: "d", text: { es: "Solo se prueban las funciones nuevas", en: "Only new features are tested" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Salvo casos triviales, probar todas las combinaciones de entradas y condiciones es inviable; se usa el análisis de riesgos y la priorización para enfocar el esfuerzo.", en: "Except for trivial cases, testing all input and condition combinations is infeasible; risk analysis and prioritization focus the effort." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-x2",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: FUND,
    question: { es: "El principio 'la ausencia de errores es una falacia' significa que…", en: "The 'absence-of-errors fallacy' principle means that…" },
    options: [
      { id: "a", text: { es: "Un sistema sin defectos puede aún ser inútil si no satisface las necesidades del usuario", en: "A defect-free system can still be useless if it does not meet user needs" } },
      { id: "b", text: { es: "Encontrar todos los defectos garantiza el éxito", en: "Finding all defects guarantees success" } },
      { id: "c", text: { es: "Los errores no existen", en: "Errors do not exist" } },
      { id: "d", text: { es: "La calidad no depende del usuario", en: "Quality does not depend on the user" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Encontrar y corregir muchos defectos no asegura el éxito: si el producto no cubre las necesidades y expectativas del usuario, sigue fallando en su propósito.", en: "Finding and fixing many defects does not ensure success: if the product does not meet user needs and expectations, it still fails its purpose." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-x3",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: FUND,
    question: { es: "¿Cuál es la diferencia entre verificación y validación?", en: "What is the difference between verification and validation?" },
    options: [
      { id: "a", text: { es: "Verificación: ¿construimos el producto correctamente? Validación: ¿construimos el producto correcto?", en: "Verification: are we building the product right? Validation: are we building the right product?" } },
      { id: "b", text: { es: "Son sinónimos exactos", en: "They are exact synonyms" } },
      { id: "c", text: { es: "La validación solo la hacen los desarrolladores", en: "Validation is done only by developers" } },
      { id: "d", text: { es: "La verificación solo aplica en producción", en: "Verification applies only in production" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Verificación comprueba que se cumplen los requisitos/especificaciones (construir bien); validación comprueba que se satisfacen las necesidades reales del usuario (construir lo correcto).", en: "Verification checks that requirements/specifications are met (build right); validation checks that real user needs are satisfied (build the right thing)." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-x4",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: FUND,
    question: { es: "Un equipo concentra todas las pruebas en el módulo donde históricamente aparecían defectos, y ahora aparecen en otro módulo intacto. ¿Qué principio lo explica mejor?", en: "A team focuses all testing on the module where defects historically appeared, and now defects show up in an untouched module. Which principle best explains this?" },
    options: [
      { id: "a", text: { es: "La paradoja del pesticida: repetir las mismas pruebas deja de encontrar defectos nuevos", en: "The pesticide paradox: repeating the same tests stops finding new defects" } },
      { id: "b", text: { es: "Agrupación de defectos exclusivamente", en: "Defect clustering only" } },
      { id: "c", text: { es: "El testing exhaustivo", en: "Exhaustive testing" } },
      { id: "d", text: { es: "La ausencia de errores", en: "Absence of errors" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La paradoja del pesticida indica que las pruebas repetidas pierden eficacia; hay que revisarlas y diseñar nuevas. La agrupación de defectos describe la concentración inicial, pero el síntoma descrito (dejar de hallar) corresponde a la paradoja del pesticida.", en: "The pesticide paradox states that repeated tests lose effectiveness; they must be reviewed and new ones designed. Defect clustering describes the initial concentration, but the described symptom (no longer finding defects) maps to the pesticide paradox." },
    points: 3,
    timeEstimateSeconds: 60,
  },
  // ───────────────────────── Capítulo 2 — SDLC ─────────────────────────
  {
    id: "istqb-x5",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: SDLC,
    question: { es: "El enfoque 'shift-left' en testing promueve…", en: "The 'shift-left' approach in testing promotes…" },
    options: [
      { id: "a", text: { es: "Comenzar las actividades de prueba lo antes posible en el ciclo de desarrollo", en: "Starting test activities as early as possible in the development cycle" } },
      { id: "b", text: { es: "Probar solo al final, antes del despliegue", en: "Testing only at the end, before deployment" } },
      { id: "c", text: { es: "Eliminar las pruebas unitarias", en: "Removing unit tests" } },
      { id: "d", text: { es: "Mover las pruebas a producción", en: "Moving testing to production" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Shift-left busca involucrar el testing temprano (revisión de requisitos, pruebas estáticas, TDD) para detectar defectos cuando corregirlos es más barato.", en: "Shift-left aims to involve testing early (requirements review, static testing, TDD) to detect defects when fixing them is cheaper." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-x6",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: SDLC,
    question: { es: "Las pruebas de aceptación (acceptance testing) se realizan principalmente para…", en: "Acceptance testing is performed mainly to…" },
    options: [
      { id: "a", text: { es: "Establecer confianza en que el sistema está listo para su uso y cumple las necesidades del negocio/usuario", en: "Establish confidence that the system is ready for use and meets business/user needs" } },
      { id: "b", text: { es: "Encontrar el mayor número de defectos de código", en: "Find the maximum number of code defects" } },
      { id: "c", text: { es: "Probar componentes individuales aislados", en: "Test isolated individual components" } },
      { id: "d", text: { es: "Verificar la integración entre dos módulos", en: "Verify integration between two modules" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La aceptación (UAT, operacional, contractual, regulatoria) valida la preparación para el uso y la adecuación a las necesidades, más que la búsqueda exhaustiva de defectos.", en: "Acceptance (UAT, operational, contractual, regulatory) validates readiness for use and fitness for needs, rather than exhaustive defect finding." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-x7",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: SDLC,
    question: { es: "Tras corregir un defecto, el tester vuelve a ejecutar el caso que falló y además ejecuta pruebas en áreas relacionadas no modificadas. ¿Qué dos tipos de prueba aplica?", en: "After fixing a defect, the tester re-runs the failed case and also runs tests in related unchanged areas. Which two test types apply?" },
    options: [
      { id: "a", text: { es: "Prueba de confirmación (re-test) y prueba de regresión", en: "Confirmation (re-)test and regression testing" } },
      { id: "b", text: { es: "Prueba de humo y prueba de carga", en: "Smoke testing and load testing" } },
      { id: "c", text: { es: "Prueba unitaria y prueba de aceptación", en: "Unit testing and acceptance testing" } },
      { id: "d", text: { es: "Prueba exploratoria y prueba de usabilidad", en: "Exploratory testing and usability testing" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La prueba de confirmación verifica que el defecto se corrigió; la de regresión comprueba que el cambio no introdujo nuevos defectos en áreas relacionadas no modificadas.", en: "Confirmation testing verifies the defect was fixed; regression testing checks that the change did not introduce new defects in related, unchanged areas." },
    points: 3,
    timeEstimateSeconds: 55,
  },
  // ───────────────────────── Capítulo 3 — Testing Estático ─────────────────────────
  {
    id: "istqb-x8",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: STATIC,
    question: { es: "¿Qué caracteriza al testing estático?", en: "What characterizes static testing?" },
    options: [
      { id: "a", text: { es: "Examina el trabajo (código, requisitos, diseño) sin ejecutar el software", en: "It examines work products (code, requirements, design) without executing the software" } },
      { id: "b", text: { es: "Siempre requiere ejecutar el sistema", en: "It always requires running the system" } },
      { id: "c", text: { es: "Solo se aplica en producción", en: "It applies only in production" } },
      { id: "d", text: { es: "Mide el rendimiento bajo carga", en: "It measures performance under load" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "El testing estático (revisiones y análisis estático) evalúa productos de trabajo sin ejecutarlos, detectando defectos de forma temprana y barata.", en: "Static testing (reviews and static analysis) evaluates work products without executing them, detecting defects early and cheaply." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-x9",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: STATIC,
    question: { es: "¿Cuál de estos tipos de revisión es el más formal y sigue un proceso definido con métricas?", en: "Which of these review types is the most formal and follows a defined process with metrics?" },
    options: [
      { id: "a", text: { es: "Inspección", en: "Inspection" } },
      { id: "b", text: { es: "Revisión informal", en: "Informal review" } },
      { id: "c", text: { es: "Walkthrough", en: "Walkthrough" } },
      { id: "d", text: { es: "Revisión por encima (over-the-shoulder)", en: "Over-the-shoulder review" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La inspección es la revisión más formal: roles definidos, criterios de entrada/salida, recogida de métricas y proceso documentado. El walkthrough y la revisión informal son menos formales.", en: "Inspection is the most formal review: defined roles, entry/exit criteria, metrics collection and documented process. Walkthrough and informal reviews are less formal." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-x10",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: STATIC,
    question: { es: "¿Por qué encontrar un defecto en una revisión de requisitos suele ser más valioso que encontrarlo en pruebas dinámicas?", en: "Why is finding a defect in a requirements review usually more valuable than finding it in dynamic testing?" },
    options: [
      { id: "a", text: { es: "Se detecta y corrige antes, evitando que se propague a diseño y código, donde corregirlo es más caro", en: "It is detected and fixed earlier, preventing propagation to design and code where fixing is more expensive" } },
      { id: "b", text: { es: "Las revisiones encuentran más defectos que cualquier prueba dinámica", en: "Reviews find more defects than any dynamic test" } },
      { id: "c", text: { es: "Los defectos de requisitos no afectan al producto", en: "Requirements defects do not affect the product" } },
      { id: "d", text: { es: "Las pruebas dinámicas no detectan defectos", en: "Dynamic tests do not detect defects" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "El coste de corregir un defecto crece a medida que avanza el ciclo; detectarlo en requisitos mediante revisión evita su propagación y el retrabajo en fases posteriores.", en: "The cost of fixing a defect grows as the cycle advances; catching it at the requirements stage via review avoids propagation and rework in later phases." },
    points: 3,
    timeEstimateSeconds: 60,
  },
  // ───────────────────────── Capítulo 4 — Análisis y Diseño ─────────────────────────
  {
    id: "istqb-x11",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: ANALYSIS,
    question: { es: "Las técnicas de caja negra (black-box) se basan en…", en: "Black-box techniques are based on…" },
    options: [
      { id: "a", text: { es: "La especificación o comportamiento esperado, sin mirar la estructura interna del código", en: "The specification or expected behavior, without looking at the internal code structure" } },
      { id: "b", text: { es: "La cobertura de sentencias del código fuente", en: "Source code statement coverage" } },
      { id: "c", text: { es: "El conocimiento de la estructura interna", en: "Knowledge of the internal structure" } },
      { id: "d", text: { es: "La experiencia del tester únicamente", en: "Only the tester's experience" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Las técnicas de caja negra (partición de equivalencia, valores límite, tabla de decisión, transición de estados) derivan casos de la especificación/comportamiento, no de la estructura interna.", en: "Black-box techniques (equivalence partitioning, boundary value, decision table, state transition) derive cases from the specification/behavior, not the internal structure." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-x12",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: ANALYSIS,
    question: { es: "Un campo acepta edades de 18 a 65. Con análisis de valores límite (BVA de 2 valores), ¿qué conjunto de valores es el más adecuado para los límites?", en: "A field accepts ages from 18 to 65. With boundary value analysis (2-value BVA), which set best covers the boundaries?" },
    options: [
      { id: "a", text: { es: "17, 18, 65, 66", en: "17, 18, 65, 66" } },
      { id: "b", text: { es: "0, 18, 65, 100", en: "0, 18, 65, 100" } },
      { id: "c", text: { es: "18, 30, 50, 65", en: "18, 30, 50, 65" } },
      { id: "d", text: { es: "1, 2, 3, 4", en: "1, 2, 3, 4" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "El BVA de 2 valores prueba justo en cada límite y el valor inválido adyacente: 17/18 en el límite inferior y 65/66 en el superior.", en: "2-value BVA tests right at each boundary and the adjacent invalid value: 17/18 at the lower boundary and 65/66 at the upper one." },
    points: 2,
    timeEstimateSeconds: 55,
  },
  {
    id: "istqb-x13",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: ANALYSIS,
    question: { es: "¿Cuándo es especialmente útil una tabla de decisión?", en: "When is a decision table especially useful?" },
    options: [
      { id: "a", text: { es: "Cuando el comportamiento depende de combinaciones de varias condiciones/reglas de negocio", en: "When behavior depends on combinations of several conditions/business rules" } },
      { id: "b", text: { es: "Cuando solo hay una única entrada numérica continua", en: "When there is only a single continuous numeric input" } },
      { id: "c", text: { es: "Cuando el sistema no tiene reglas", en: "When the system has no rules" } },
      { id: "d", text: { es: "Solo para pruebas de rendimiento", en: "Only for performance testing" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La tabla de decisión modela combinaciones de condiciones y sus acciones resultantes; es ideal para lógica de negocio con múltiples reglas que interactúan.", en: "A decision table models combinations of conditions and their resulting actions; it is ideal for business logic with multiple interacting rules." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-x14",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: ANALYSIS,
    question: { es: "La cobertura de ramas (branch coverage) garantiza que…", en: "Branch coverage guarantees that…" },
    options: [
      { id: "a", text: { es: "Cada decisión se evalúa tanto verdadera como falsa al menos una vez", en: "Each decision is evaluated both true and false at least once" } },
      { id: "b", text: { es: "Cada línea de código se escribe sin errores", en: "Each line of code is written without errors" } },
      { id: "c", text: { es: "Todas las entradas posibles se prueban", en: "All possible inputs are tested" } },
      { id: "d", text: { es: "El rendimiento es óptimo", en: "Performance is optimal" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La cobertura de ramas/decisiones exige ejercitar cada resultado de cada decisión (verdadero y falso). Es más fuerte que la cobertura de sentencias.", en: "Branch/decision coverage requires exercising each outcome of every decision (true and false). It is stronger than statement coverage." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-x15",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: ANALYSIS,
    question: { es: "¿Qué afirmación describe correctamente la relación entre cobertura de sentencias y de ramas?", en: "Which statement correctly describes the relationship between statement and branch coverage?" },
    options: [
      { id: "a", text: { es: "El 100% de cobertura de ramas implica el 100% de cobertura de sentencias, pero no al revés", en: "100% branch coverage implies 100% statement coverage, but not vice versa" } },
      { id: "b", text: { es: "El 100% de cobertura de sentencias implica el 100% de cobertura de ramas", en: "100% statement coverage implies 100% branch coverage" } },
      { id: "c", text: { es: "Ambas son siempre equivalentes", en: "Both are always equivalent" } },
      { id: "d", text: { es: "No tienen ninguna relación entre sí", en: "They have no relationship with each other" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Cubrir todas las ramas obliga a recorrer todas las sentencias, así que rama⇒sentencia. Lo contrario no se cumple: se pueden ejecutar todas las sentencias sin tomar ambas salidas de cada decisión.", en: "Covering all branches forces traversing all statements, so branch⇒statement. The reverse does not hold: all statements can run without taking both outcomes of every decision." },
    points: 3,
    timeEstimateSeconds: 65,
  },
  {
    id: "istqb-x16",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: ANALYSIS,
    question: { es: "La 'adivinación de errores' (error guessing) es una técnica basada en…", en: "'Error guessing' is a technique based on…" },
    options: [
      { id: "a", text: { es: "La experiencia del tester para anticipar dónde es probable que haya defectos", en: "The tester's experience to anticipate where defects are likely" } },
      { id: "b", text: { es: "La cobertura formal del código", en: "Formal code coverage" } },
      { id: "c", text: { es: "Una especificación detallada de entradas", en: "A detailed input specification" } },
      { id: "d", text: { es: "Generación aleatoria pura de datos", en: "Purely random data generation" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La adivinación de errores es una técnica basada en la experiencia: el tester usa su conocimiento de defectos típicos y zonas frágiles para diseñar pruebas dirigidas.", en: "Error guessing is an experience-based technique: the tester uses knowledge of typical defects and fragile areas to design targeted tests." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  // ───────────────────────── Capítulo 5 — Gestión ─────────────────────────
  {
    id: "istqb-x17",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: MGMT,
    question: { es: "El nivel de riesgo se determina habitualmente combinando…", en: "Risk level is usually determined by combining…" },
    options: [
      { id: "a", text: { es: "La probabilidad de que ocurra y el impacto si ocurre", en: "The likelihood of occurrence and the impact if it occurs" } },
      { id: "b", text: { es: "El número de testers y el presupuesto", en: "The number of testers and the budget" } },
      { id: "c", text: { es: "El tamaño del equipo de desarrollo", en: "The size of the development team" } },
      { id: "d", text: { es: "La cantidad de líneas de código", en: "The number of lines of code" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Riesgo = probabilidad × impacto. La probabilidad mide cuán factible es que se materialice y el impacto el daño asociado; juntos priorizan el esfuerzo de prueba.", en: "Risk = likelihood × impact. Likelihood measures how probable it is and impact the associated harm; together they prioritize test effort." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-x18",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: MGMT,
    question: { es: "¿Qué describe mejor unos criterios de salida (exit criteria / definition of done)?", en: "What best describes exit criteria (definition of done)?" },
    options: [
      { id: "a", text: { es: "Condiciones que deben cumplirse para considerar terminada una actividad o nivel de prueba", en: "Conditions that must be met to consider a test activity or level complete" } },
      { id: "b", text: { es: "Las condiciones para empezar a probar", en: "The conditions to start testing" } },
      { id: "c", text: { es: "La lista de defectos abiertos", en: "The list of open defects" } },
      { id: "d", text: { es: "El presupuesto del proyecto", en: "The project budget" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Los criterios de salida (cobertura alcanzada, defectos pendientes, etc.) definen cuándo se puede dar por completada una actividad de prueba; los de entrada definen cuándo empezar.", en: "Exit criteria (coverage achieved, remaining defects, etc.) define when a test activity can be deemed complete; entry criteria define when to start." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-x19",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: MGMT,
    question: { es: "En un informe de defecto, ¿qué información es esencial para que sea accionable?", en: "In a defect report, which information is essential for it to be actionable?" },
    options: [
      { id: "a", text: { es: "Pasos para reproducir, resultado esperado y resultado real", en: "Steps to reproduce, expected result and actual result" } },
      { id: "b", text: { es: "Únicamente el nombre de quien lo reporta", en: "Only the reporter's name" } },
      { id: "c", text: { es: "El color de la interfaz", en: "The interface color" } },
      { id: "d", text: { es: "El presupuesto del sprint", en: "The sprint budget" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Un buen informe de defecto incluye pasos de reproducción, resultado esperado vs. real, severidad/prioridad y entorno, para que el equipo pueda diagnosticar y corregir.", en: "A good defect report includes reproduction steps, expected vs. actual result, severity/priority and environment, so the team can diagnose and fix it." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-x20",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: MGMT,
    question: { es: "Con tiempo limitado, un equipo prueba primero las funciones de pago (alto impacto, fallos frecuentes) y deja para el final una pantalla de ayuda estática. ¿Qué estrategia aplica?", en: "With limited time, a team tests payment features first (high impact, frequent failures) and leaves a static help screen for last. Which strategy is this?" },
    options: [
      { id: "a", text: { es: "Testing basado en riesgos", en: "Risk-based testing" } },
      { id: "b", text: { es: "Testing exhaustivo", en: "Exhaustive testing" } },
      { id: "c", text: { es: "Testing aleatorio sin criterio", en: "Random testing with no criteria" } },
      { id: "d", text: { es: "Testing solo de regresión", en: "Regression-only testing" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "El testing basado en riesgos prioriza qué probar y con cuánta profundidad según el nivel de riesgo (probabilidad × impacto), enfocando el esfuerzo en lo más crítico.", en: "Risk-based testing prioritizes what to test and how deeply according to risk level (likelihood × impact), focusing effort on the most critical areas." },
    points: 3,
    timeEstimateSeconds: 55,
  },
  // ───────────────────────── Capítulo 6 — Herramientas ─────────────────────────
  {
    id: "istqb-x21",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: TOOLS,
    question: { es: "Una herramienta de gestión de configuración en el contexto de testing sirve para…", en: "A configuration management tool in the testing context is used to…" },
    options: [
      { id: "a", text: { es: "Controlar versiones de testware y mantener la trazabilidad de los elementos de prueba", en: "Version-control testware and keep traceability of test items" } },
      { id: "b", text: { es: "Medir el rendimiento de la base de datos", en: "Measure database performance" } },
      { id: "c", text: { es: "Diseñar la interfaz gráfica", en: "Design the graphical interface" } },
      { id: "d", text: { es: "Sustituir al gestor de pruebas", en: "Replace the test manager" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Las herramientas de gestión de configuración versionan y trazan los productos de trabajo (scripts, datos, casos), asegurando reproducibilidad y control de cambios.", en: "Configuration management tools version and trace work products (scripts, data, cases), ensuring reproducibility and change control." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-x22",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: TOOLS,
    question: { es: "Un proyecto adopta una herramienta de automatización pero subestima el esfuerzo de mantener los scripts. ¿Cuál es la consecuencia más probable?", en: "A project adopts an automation tool but underestimates the effort to maintain the scripts. What is the most likely consequence?" },
    options: [
      { id: "a", text: { es: "Los scripts se vuelven obsoletos, generan falsos fallos y el ROI esperado no se materializa", en: "Scripts become obsolete, produce false failures and the expected ROI does not materialize" } },
      { id: "b", text: { es: "La calidad mejora automáticamente sin esfuerzo", en: "Quality improves automatically with no effort" } },
      { id: "c", text: { es: "Los defectos desaparecen por completo", en: "Defects disappear entirely" } },
      { id: "d", text: { es: "El mantenimiento deja de ser necesario", en: "Maintenance is no longer needed" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Subestimar el mantenimiento es un riesgo clásico de la automatización: sin actualización, los scripts fallan en falso, pierden confianza y el coste supera al beneficio previsto.", en: "Underestimating maintenance is a classic automation risk: without updates, scripts give false failures, lose trust and cost outweighs the expected benefit." },
    points: 3,
    timeEstimateSeconds: 60,
  },
];

registerQuestions(QUESTIONS);

export default QUESTIONS;
