/**
 * ISTQB CTFL — Banco de preguntas Módulo 4 (Análisis y Diseño de Pruebas).
 * Cubre el Capítulo 4 del syllabus: técnicas de caja negra (partición de
 * equivalencia, valores límite, tabla de decisión, transición de estados),
 * caja blanca (sentencias, ramas) y basadas en experiencia/colaboración.
 * Fuentes: ISTQB CTFL v4.0 Syllabus (cap. 4), ISTQB Glossary.
 */

import type { ExamQuestion } from "@/types/exam";
import { registerQuestions } from "@/lib/exam/scoring";

const M = ["istqb-test-analysis"];

const QUESTIONS: ExamQuestion[] = [
  {
    id: "istqb-m4-e1",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿En qué consiste la partición de equivalencia?", en: "What is equivalence partitioning?" },
    options: [
      { id: "a", text: { es: "Dividir los datos de entrada en grupos que se espera se traten igual, y probar uno por grupo", en: "Divide input data into groups expected to be treated the same, and test one per group" } },
      { id: "b", text: { es: "Probar todos los valores posibles", en: "Test every possible value" } },
      { id: "c", text: { es: "Revisar el código línea a línea", en: "Review the code line by line" } },
      { id: "d", text: { es: "Ejecutar el sistema bajo carga", en: "Run the system under load" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La partición de equivalencia agrupa entradas que deberían procesarse de igual forma; basta un representante por partición para reducir casos sin perder cobertura.", en: "Equivalence partitioning groups inputs expected to be processed alike; one representative per partition reduces cases without losing coverage." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m4-e2",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "El análisis de valores límite (BVA) se centra en…", en: "Boundary value analysis (BVA) focuses on…" },
    options: [
      { id: "a", text: { es: "Los valores en los bordes de las particiones de equivalencia", en: "The values at the edges of equivalence partitions" } },
      { id: "b", text: { es: "Los valores centrales de cada partición", en: "The central values of each partition" } },
      { id: "c", text: { es: "La estructura interna del código", en: "The internal structure of the code" } },
      { id: "d", text: { es: "Los tiempos de respuesta", en: "Response times" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "BVA prueba los límites de las particiones (mínimos/máximos y sus valores adyacentes), donde es más probable que aparezcan defectos.", en: "BVA tests partition boundaries (min/max and adjacent values), where defects are most likely to occur." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m4-e3",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "Las técnicas de caja negra se basan principalmente en…", en: "Black-box techniques are mainly based on…" },
    options: [
      { id: "a", text: { es: "La estructura interna y el código", en: "The internal structure and code" } },
      { id: "b", text: { es: "La especificación y el comportamiento esperado", en: "The specification and expected behavior" } },
      { id: "c", text: { es: "La experiencia personal del tester sin base documental", en: "The tester's personal experience with no documentation" } },
      { id: "d", text: { es: "La cobertura de ramas", en: "Branch coverage" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "Las técnicas de caja negra (basadas en especificación) derivan pruebas del comportamiento esperado sin mirar el código.", en: "Black-box (specification-based) techniques derive tests from expected behavior without looking at the code." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m4-e4",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "Las técnicas de caja blanca se basan en…", en: "White-box techniques are based on…" },
    options: [
      { id: "a", text: { es: "La estructura interna del software (código, flujo de control)", en: "The internal structure of the software (code, control flow)" } },
      { id: "b", text: { es: "La opinión del cliente", en: "The customer's opinion" } },
      { id: "c", text: { es: "Solo la documentación de requisitos", en: "Only the requirements documentation" } },
      { id: "d", text: { es: "La intuición del tester", en: "The tester's intuition" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Las técnicas de caja blanca (basadas en estructura) derivan pruebas de la estructura interna: sentencias, ramas, caminos.", en: "White-box (structure-based) techniques derive tests from internal structure: statements, branches, paths." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m4-e5",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "La 'adivinación de errores' (error guessing) es una técnica…", en: "'Error guessing' is a technique that is…" },
    options: [
      { id: "a", text: { es: "Basada en la experiencia", en: "Experience-based" } },
      { id: "b", text: { es: "De caja blanca", en: "White-box" } },
      { id: "c", text: { es: "De tabla de decisión", en: "Decision table" } },
      { id: "d", text: { es: "De cobertura de sentencias", en: "Statement coverage" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La adivinación de errores es una técnica basada en la experiencia: el tester anticipa defectos probables a partir de su conocimiento.", en: "Error guessing is an experience-based technique: the tester anticipates likely defects from prior knowledge." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m4-e6",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "El testing basado en listas de comprobación (checklist-based) consiste en…", en: "Checklist-based testing consists of…" },
    options: [
      { id: "a", text: { es: "Diseñar y ejecutar pruebas guiándose por una lista de condiciones a verificar", en: "Designing and running tests guided by a list of conditions to verify" } },
      { id: "b", text: { es: "Medir la cobertura de código", en: "Measuring code coverage" } },
      { id: "c", text: { es: "Ejecutar pruebas sin ningún registro", en: "Running tests with no record at all" } },
      { id: "d", text: { es: "Probar únicamente los límites", en: "Testing only the boundaries" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Es una técnica basada en experiencia donde una checklist recoge condiciones, riesgos o áreas a cubrir derivadas de experiencia previa.", en: "It is an experience-based technique where a checklist captures conditions, risks or areas to cover derived from prior experience." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m4-e7",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Cuándo es MÁS apropiada una tabla de decisión?", en: "When is a decision table MOST appropriate?" },
    options: [
      { id: "a", text: { es: "Cuando el comportamiento depende de combinaciones de condiciones y reglas de negocio", en: "When behavior depends on combinations of conditions and business rules" } },
      { id: "b", text: { es: "Cuando solo importa el orden de los eventos", en: "When only the order of events matters" } },
      { id: "c", text: { es: "Cuando se mide cobertura de código", en: "When measuring code coverage" } },
      { id: "d", text: { es: "Cuando no hay especificación", en: "When there is no specification" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La tabla de decisión modela combinaciones de condiciones y sus acciones resultantes; ideal para reglas de negocio.", en: "A decision table models combinations of conditions and their resulting actions; ideal for business rules." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-m4-e8",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Cuándo es MÁS apropiada la prueba de transición de estados?", en: "When is state transition testing MOST appropriate?" },
    options: [
      { id: "a", text: { es: "Cuando el sistema reacciona de forma distinta según su estado actual y los eventos recibidos", en: "When the system reacts differently depending on its current state and received events" } },
      { id: "b", text: { es: "Cuando solo hay que probar valores numéricos límite", en: "When only numeric boundary values must be tested" } },
      { id: "c", text: { es: "Cuando se revisa el código fuente", en: "When reviewing source code" } },
      { id: "d", text: { es: "Cuando no existen estados", en: "When there are no states" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La transición de estados modela estados, eventos, transiciones y acciones; útil cuando el comportamiento depende del historial/estado.", en: "State transition testing models states, events, transitions and actions; useful when behavior depends on history/state." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-m4-e9",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Qué afirma correctamente sobre cobertura de sentencias y de ramas?", en: "Which statement about statement and branch coverage is correct?" },
    options: [
      { id: "a", text: { es: "El 100% de cobertura de ramas implica el 100% de cobertura de sentencias", en: "100% branch coverage implies 100% statement coverage" } },
      { id: "b", text: { es: "El 100% de cobertura de sentencias implica el 100% de cobertura de ramas", en: "100% statement coverage implies 100% branch coverage" } },
      { id: "c", text: { es: "Ambas son independientes y no se relacionan", en: "They are independent and unrelated" } },
      { id: "d", text: { es: "La cobertura de sentencias es siempre más fuerte que la de ramas", en: "Statement coverage is always stronger than branch coverage" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La cobertura de ramas es más fuerte: alcanzar el 100% de ramas garantiza el 100% de sentencias, pero no al revés.", en: "Branch coverage is stronger: achieving 100% branch coverage guarantees 100% statement coverage, but not the other way around." },
    points: 2,
    timeEstimateSeconds: 55,
  },
  {
    id: "istqb-m4-e10",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Cuál es una característica del testing exploratorio?", en: "What is a characteristic of exploratory testing?" },
    options: [
      { id: "a", text: { es: "El diseño, la ejecución y el aprendizaje ocurren de forma simultánea", en: "Design, execution and learning happen simultaneously" } },
      { id: "b", text: { es: "Requiere casos de prueba totalmente escritos antes de empezar", en: "It requires fully scripted test cases before starting" } },
      { id: "c", text: { es: "No aporta valor en sistemas poco documentados", en: "It adds no value on poorly documented systems" } },
      { id: "d", text: { es: "Mide cobertura de ramas automáticamente", en: "It automatically measures branch coverage" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "En el testing exploratorio el tester diseña y ejecuta pruebas mientras aprende del sistema; suele organizarse con session-based test management.", en: "In exploratory testing the tester designs and runs tests while learning about the system; it is often organized with session-based test management." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-m4-e11",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "En un enfoque colaborativo basado en ATDD, los criterios de aceptación se definen…", en: "In a collaboration-based ATDD approach, acceptance criteria are defined…" },
    options: [
      { id: "a", text: { es: "Colaborativamente entre negocio, desarrollo y testing antes de implementar", en: "Collaboratively between business, development and testing before implementing" } },
      { id: "b", text: { es: "Solo por el desarrollador tras codificar", en: "Only by the developer after coding" } },
      { id: "c", text: { es: "Solo por el tester al final del sprint", en: "Only by the tester at the end of the sprint" } },
      { id: "d", text: { es: "Nunca, ATDD no los usa", en: "Never, ATDD does not use them" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "ATDD (Acceptance Test-Driven Development) define los criterios de aceptación de forma colaborativa (las 'tres amigas') antes de desarrollar.", en: "ATDD (Acceptance Test-Driven Development) defines acceptance criteria collaboratively (the 'three amigos') before development." },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "istqb-m4-e12",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "Un campo acepta enteros de 1 a 100. Con valores límite de 2 valores, ¿qué conjunto es correcto para los bordes inferior y superior?", en: "A field accepts integers from 1 to 100. With 2-value boundary analysis, which set is correct for the lower and upper edges?" },
    options: [
      { id: "a", text: { es: "0, 1 (inferior) y 100, 101 (superior)", en: "0, 1 (lower) and 100, 101 (upper)" } },
      { id: "b", text: { es: "1, 50, 100", en: "1, 50, 100" } },
      { id: "c", text: { es: "Solo 1 y 100", en: "Only 1 and 100" } },
      { id: "d", text: { es: "-1 y 102", en: "-1 and 102" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "En BVA de 2 valores se prueban el límite y su valor adyacente fuera de la partición válida: 0/1 abajo y 100/101 arriba.", en: "In 2-value BVA you test the boundary and its adjacent value outside the valid partition: 0/1 below and 100/101 above." },
    points: 3,
    timeEstimateSeconds: 60,
  },
  {
    id: "istqb-m4-e13",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "Una tabla de decisión tiene 3 condiciones booleanas independientes. ¿Cuántas reglas (columnas) tiene la tabla completa?", en: "A decision table has 3 independent boolean conditions. How many rules (columns) does the full table have?" },
    options: [
      { id: "a", text: { es: "3", en: "3" } },
      { id: "b", text: { es: "6", en: "6" } },
      { id: "c", text: { es: "8", en: "8" } },
      { id: "d", text: { es: "9", en: "9" } },
    ],
    correctOptionIds: ["c"],
    explanation: { es: "Con n condiciones booleanas, la tabla completa tiene 2^n combinaciones: 2^3 = 8 reglas.", en: "With n boolean conditions, the full table has 2^n combinations: 2^3 = 8 rules." },
    points: 3,
    timeEstimateSeconds: 55,
  },
  {
    id: "istqb-m4-e14",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "¿Cuál es la principal ventaja de combinar técnicas de caja negra, caja blanca y basadas en experiencia?", en: "What is the main advantage of combining black-box, white-box and experience-based techniques?" },
    options: [
      { id: "a", text: { es: "Cubren aspectos distintos (comportamiento, estructura y conocimiento tácito), aumentando la eficacia global", en: "They cover different aspects (behavior, structure and tacit knowledge), increasing overall effectiveness" } },
      { id: "b", text: { es: "Permiten eliminar por completo el testing dinámico", en: "They allow fully removing dynamic testing" } },
      { id: "c", text: { es: "Garantizan el 100% de detección de defectos", en: "They guarantee 100% defect detection" } },
      { id: "d", text: { es: "Hacen innecesaria la gestión de riesgos", en: "They make risk management unnecessary" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Cada familia de técnicas detecta defectos distintos; combinarlas mejora la cobertura, aunque ninguna garantiza detección total.", en: "Each technique family detects different defects; combining them improves coverage, though none guarantees total detection." },
    points: 3,
    timeEstimateSeconds: 60,
  },
];

registerQuestions(QUESTIONS);

export default QUESTIONS;
