/**
 * ISTQB CTFL — Banco de preguntas Módulo 2 (Testing a lo Largo del SDLC).
 * Cubre el Capítulo 2 del syllabus: modelos de SDLC, buenas prácticas,
 * niveles de prueba, tipos de prueba, confirmación/regresión y mantenimiento.
 * Fuentes: ISTQB CTFL v4.0 Syllabus (cap. 2), ISTQB Glossary.
 */

import type { ExamQuestion } from "@/types/exam";
import { registerQuestions } from "@/lib/exam/scoring";

const M = ["istqb-sdlc"];

const QUESTIONS: ExamQuestion[] = [
  {
    id: "istqb-m2-e1",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Cuántos niveles de prueba define típicamente el ISTQB?", en: "How many test levels does ISTQB typically define?" },
    options: [
      { id: "a", text: { es: "2", en: "2" } },
      { id: "b", text: { es: "3", en: "3" } },
      { id: "c", text: { es: "4", en: "4" } },
      { id: "d", text: { es: "6", en: "6" } },
    ],
    correctOptionIds: ["c"],
    explanation: { es: "Cuatro niveles: pruebas de componente (unitarias), de integración, de sistema y de aceptación.", en: "Four levels: component (unit), integration, system and acceptance testing." },
    points: 1,
    timeEstimateSeconds: 35,
  },
  {
    id: "istqb-m2-e2",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "Probar una función o clase de forma aislada corresponde al nivel…", en: "Testing a single function or class in isolation corresponds to the level…" },
    options: [
      { id: "a", text: { es: "De componente (unitario)", en: "Component (unit)" } },
      { id: "b", text: { es: "De integración", en: "Integration" } },
      { id: "c", text: { es: "De sistema", en: "System" } },
      { id: "d", text: { es: "De aceptación", en: "Acceptance" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "Las pruebas de componente (o unitarias) verifican componentes individuales aislados.", en: "Component (unit) testing verifies individual components in isolation." },
    points: 1,
    timeEstimateSeconds: 35,
  },
  {
    id: "istqb-m2-e3",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "Las pruebas de aceptación de usuario (UAT) buscan principalmente…", en: "User acceptance testing (UAT) mainly aims to…" },
    options: [
      { id: "a", text: { es: "Verificar la estructura interna del código", en: "Verify the internal code structure" } },
      { id: "b", text: { es: "Validar que el sistema satisface las necesidades del usuario/negocio", en: "Validate that the system meets user/business needs" } },
      { id: "c", text: { es: "Medir la cobertura de sentencias", en: "Measure statement coverage" } },
      { id: "d", text: { es: "Comprobar la integración entre dos módulos", en: "Check integration between two modules" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "La aceptación valida la aptitud para el uso y la confianza para liberar; UAT la realizan usuarios/clientes.", en: "Acceptance validates fitness for use and confidence to release; UAT is performed by users/customers." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m2-e4",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Cuál de estas es una prueba NO funcional?", en: "Which of these is a NON-functional test?" },
    options: [
      { id: "a", text: { es: "Comprobar que el login acepta credenciales válidas", en: "Checking that login accepts valid credentials" } },
      { id: "b", text: { es: "Medir el tiempo de respuesta bajo 1000 usuarios concurrentes", en: "Measuring response time under 1000 concurrent users" } },
      { id: "c", text: { es: "Verificar que el cálculo del total es correcto", en: "Verifying the total calculation is correct" } },
      { id: "d", text: { es: "Comprobar que el botón 'Guardar' persiste los datos", en: "Checking the 'Save' button persists data" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El rendimiento (response time, carga) es una característica no funcional; las demás opciones evalúan qué hace el sistema (funcional).", en: "Performance (response time, load) is a non-functional characteristic; the other options test what the system does (functional)." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m2-e5",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "Tras corregir un defecto, se vuelve a ejecutar el caso que lo detectó. ¿Qué tipo de prueba es?", en: "After fixing a defect, the case that found it is re-run. What type of testing is this?" },
    options: [
      { id: "a", text: { es: "Prueba de confirmación (re-test)", en: "Confirmation testing (re-test)" } },
      { id: "b", text: { es: "Prueba de regresión", en: "Regression testing" } },
      { id: "c", text: { es: "Prueba de humo", en: "Smoke testing" } },
      { id: "d", text: { es: "Prueba exploratoria", en: "Exploratory testing" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La prueba de confirmación verifica que el defecto se corrigió realmente reejecutando el caso fallido.", en: "Confirmation testing verifies the defect was actually fixed by re-running the failed case." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "istqb-m2-e6",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Qué busca la prueba de regresión?", en: "What does regression testing look for?" },
    options: [
      { id: "a", text: { es: "Confirmar que un defecto concreto se corrigió", en: "Confirm a specific defect was fixed" } },
      { id: "b", text: { es: "Detectar que un cambio rompió funcionalidad que antes funcionaba", en: "Detect that a change broke previously working functionality" } },
      { id: "c", text: { es: "Medir el rendimiento del sistema", en: "Measure system performance" } },
      { id: "d", text: { es: "Validar la aptitud para el uso por el cliente", en: "Validate fitness for use by the customer" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "La regresión comprueba que los cambios (correcciones o nuevas features) no han introducido efectos colaterales en lo que ya funcionaba.", en: "Regression checks that changes (fixes or new features) have not introduced side effects in what already worked." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m2-e7",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Qué significa 'shift-left' en el contexto del testing?", en: "What does 'shift-left' mean in the testing context?" },
    options: [
      { id: "a", text: { es: "Posponer las pruebas hasta el final del proyecto", en: "Postpone testing until the end of the project" } },
      { id: "b", text: { es: "Involucrar las actividades de testing lo más pronto posible en el ciclo de vida", en: "Involve testing activities as early as possible in the lifecycle" } },
      { id: "c", text: { es: "Mover el equipo de pruebas a otro departamento", en: "Move the test team to another department" } },
      { id: "d", text: { es: "Automatizar el 100% de las pruebas", en: "Automate 100% of the tests" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "Shift-left consiste en adelantar las pruebas (incluido el testing estático de requisitos) para detectar defectos cuanto antes.", en: "Shift-left means moving testing earlier (including static testing of requirements) to find defects as soon as possible." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m2-e8",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "Probar la interacción entre dos componentes recién integrados corresponde a…", en: "Testing the interaction between two newly integrated components corresponds to…" },
    options: [
      { id: "a", text: { es: "Integración de componentes", en: "Component integration testing" } },
      { id: "b", text: { es: "Pruebas de aceptación", en: "Acceptance testing" } },
      { id: "c", text: { es: "Pruebas de componente", en: "Component testing" } },
      { id: "d", text: { es: "Pruebas de humo en producción", en: "Smoke testing in production" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La integración de componentes prueba las interfaces e interacciones entre componentes; la integración de sistemas prueba interfaces entre sistemas.", en: "Component integration testing tests interfaces and interactions between components; system integration testing tests interfaces between systems." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m2-e9",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Cuál es un disparador típico de las pruebas de mantenimiento?", en: "Which is a typical trigger for maintenance testing?" },
    options: [
      { id: "a", text: { es: "El arranque inicial del proyecto", en: "The initial project kick-off" } },
      { id: "b", text: { es: "Una modificación, migración o retirada del sistema", en: "A modification, migration or retirement of the system" } },
      { id: "c", text: { es: "La primera redacción de los requisitos", en: "The first drafting of requirements" } },
      { id: "d", text: { es: "El diseño de la arquitectura", en: "The architecture design" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El mantenimiento se dispara por modificaciones (correctivas/adaptativas/perfectivas), migraciones o retirada del sistema.", en: "Maintenance is triggered by modifications (corrective/adaptive/perfective), migrations or system retirement." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m2-e10",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "En un modelo de desarrollo iterativo/ágil, las actividades de testing…", en: "In an iterative/agile development model, testing activities…" },
    options: [
      { id: "a", text: { es: "Se realizan una sola vez al final", en: "Are done only once at the end" } },
      { id: "b", text: { es: "Se realizan de forma continua en cada iteración", en: "Are performed continuously in each iteration" } },
      { id: "c", text: { es: "No son necesarias", en: "Are not necessary" } },
      { id: "d", text: { es: "Solo las hace el cliente", en: "Are only done by the customer" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "En modelos iterativos/incrementales el testing es continuo y cada incremento se prueba a medida que se desarrolla.", en: "In iterative/incremental models testing is continuous and each increment is tested as it is developed." },
    points: 2,
    timeEstimateSeconds: 45,
  },
  {
    id: "istqb-m2-e11",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "Una prueba de seguridad que verifica que el sistema resiste accesos no autorizados se clasifica como…", en: "A security test verifying the system resists unauthorized access is classified as…" },
    options: [
      { id: "a", text: { es: "Prueba funcional de bajo nivel", en: "Low-level functional test" } },
      { id: "b", text: { es: "Prueba no funcional (característica de seguridad)", en: "Non-functional test (security characteristic)" } },
      { id: "c", text: { es: "Prueba de confirmación", en: "Confirmation test" } },
      { id: "d", text: { es: "Prueba de componente", en: "Component test" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "La seguridad es una característica de calidad no funcional (ISO 25010); evalúa cómo se comporta el sistema, no qué función ejecuta.", en: "Security is a non-functional quality characteristic (ISO 25010); it evaluates how the system behaves, not what function it performs." },
    points: 3,
    timeEstimateSeconds: 55,
  },
  {
    id: "istqb-m2-e12",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "¿Cuál de estas NO es una forma reconocida de pruebas de aceptación?", en: "Which of these is NOT a recognized form of acceptance testing?" },
    options: [
      { id: "a", text: { es: "Pruebas de aceptación de usuario (UAT)", en: "User acceptance testing (UAT)" } },
      { id: "b", text: { es: "Pruebas de aceptación operacional (OAT)", en: "Operational acceptance testing (OAT)" } },
      { id: "c", text: { es: "Pruebas de aceptación contractuales y regulatorias", en: "Contractual and regulatory acceptance testing" } },
      { id: "d", text: { es: "Pruebas de aceptación de cobertura de ramas", en: "Branch-coverage acceptance testing" } },
    ],
    correctOptionIds: ["d"],
    explanation: { es: "Las formas de aceptación incluyen UAT, OAT, contractual/regulatoria y alfa/beta. La 'cobertura de ramas' es una métrica de caja blanca, no un tipo de aceptación.", en: "Acceptance forms include UAT, OAT, contractual/regulatory and alpha/beta. 'Branch coverage' is a white-box metric, not an acceptance type." },
    points: 3,
    timeEstimateSeconds: 60,
  },
];

registerQuestions(QUESTIONS);

export default QUESTIONS;
