/**
 * Exam question bank — Module 8: CI/CD and Reporting.
 *
 * 25 questions (10 easy, 10 medium, 5 hard) covering:
 *   - HTML Reporter: anatomy of a failed report (trace, screenshot, video), show-report,
 *     why it's superior to reading raw terminal output
 *   - GitHub Actions: workflow anatomy (on/jobs/runs-on/steps), caching dependencies and
 *     browsers, why uploading the report artifact with if: always() is critical
 *   - Trace Viewer in CI: why trace: 'on-first-retry' is the sweet spot, uploading/viewing
 *     traces as CI artifacts, what a trace captures that a screenshot doesn't
 *   - Allure Reporter: value over the native HTML reporter (history, trends, categorization),
 *     basic installation/configuration
 *   - Capstone exercise: full pipeline (checkout -> setup-node -> install deps -> install
 *     browsers -> run tests -> upload report), why step order matters
 */

import type { ExamQuestion } from "@/types/exam";
import { registerQuestions } from "@/lib/exam/scoring";

const M8 = "m8-cicd-reporting";

const QUESTIONS: ExamQuestion[] = [
  /* ================================================================== */
  /*  EASY (10 questions)                                                */
  /* ================================================================== */

  {
    id: "m8-e1",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: [M8],
    question: {
      es: "¿Qué necesitas instalar para usar el HTML reporter de Playwright?",
      en: "What do you need to install to use Playwright's HTML reporter?",
    },
    options: [
      { id: "a", text: { es: "Nada extra — viene incluido con Playwright, sin dependencias adicionales", en: "Nothing extra — it comes bundled with Playwright, no additional dependencies" } },
      { id: "b", text: { es: "El paquete npm `playwright-html-reporter` por separado", en: "The `playwright-html-reporter` npm package separately" } },
      { id: "c", text: { es: "Una extensión de VS Code llamada Playwright Reports", en: "A VS Code extension called Playwright Reports" } },
      { id: "d", text: { es: "allure-playwright, ya que el HTML reporter depende internamente de Allure", en: "allure-playwright, since the HTML reporter internally depends on Allure" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "El HTML reporter viene incluido con Playwright desde su instalación base — no requiere instalar ningún paquete adicional ni configurar nada para empezar a usarlo. Esto lo diferencia de Allure, que sí requiere instalar `allure-playwright` y la CLI de Allure por separado. No existe ningún paquete `playwright-html-reporter` ni extensión de VS Code necesaria, y el HTML reporter no depende de Allure (es justo al revés conceptualmente: son reporters independientes y alternativos).",
      en: "The HTML reporter ships with Playwright's base installation — it requires no additional package or setup to start using it. This sets it apart from Allure, which does require installing `allure-playwright` and the Allure CLI separately. There's no `playwright-html-reporter` package or required VS Code extension, and the HTML reporter doesn't depend on Allure (conceptually it's the other way around: they're independent, alternative reporters).",
    },
    points: 1,
    timeEstimateSeconds: 25,
  },
  {
    id: "m8-e2",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: [M8],
    question: {
      es: "¿Qué comando abre el reporte HTML más reciente generado por Playwright?",
      en: "Which command opens the most recent HTML report generated by Playwright?",
    },
    options: [
      { id: "a", text: { es: "npx playwright show-report", en: "npx playwright show-report" } },
      { id: "b", text: { es: "npx playwright open-html", en: "npx playwright open-html" } },
      { id: "c", text: { es: "npx playwright report --open", en: "npx playwright report --open" } },
      { id: "d", text: { es: "npm run html-report", en: "npm run html-report" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "`npx playwright show-report` abre el reporte HTML más reciente en tu navegador por defecto. Si moviste el reporte a otra carpeta o usaste un `outputFolder` personalizado, puedes pasarle la ruta como argumento: `npx playwright show-report ./mis-reportes`. Los otros comandos no existen en la CLI de Playwright.",
      en: "`npx playwright show-report` opens the most recent HTML report in your default browser. If you moved the report to another folder or used a custom `outputFolder`, you can pass the path as an argument: `npx playwright show-report ./my-reports`. The other commands don't exist in the Playwright CLI.",
    },
    points: 1,
    timeEstimateSeconds: 25,
  },
  {
    id: "m8-e3",
    type: "multiple_choice",
    difficulty: "easy",
    moduleIds: [M8],
    question: {
      es: "¿Qué artefactos puede incluir el reporte HTML de Playwright para un test fallido? (Selecciona todas las correctas)",
      en: "Which artifacts can Playwright's HTML report include for a failed test? (Select all that apply)",
    },
    options: [
      { id: "a", text: { es: "Screenshot del momento del fallo", en: "A screenshot of the failure moment" } },
      { id: "b", text: { es: "Video de la sesión completa", en: "A video of the full session" } },
      { id: "c", text: { es: "Enlace directo para abrir la traza en Trace Viewer", en: "A direct link to open the trace in Trace Viewer" } },
      { id: "d", text: { es: "Un dump completo de la base de datos del backend", en: "A full dump of the backend database" } },
    ],
    correctOptionIds: ["a", "b", "c"],
    explanation: {
      es: "El reporte HTML puede adjuntar screenshots automáticos del momento del fallo, videos de la sesión completa, y enlaces directos para abrir la traza en Trace Viewer — junto con la línea de tiempo de pasos y los mensajes de error con code frames. No incluye ni puede incluir un dump de la base de datos del backend; eso está completamente fuera del alcance de lo que Playwright observa (solo ve lo que ocurre en el navegador y en la red, no el estado interno del servidor).",
      en: "The HTML report can attach automatic screenshots of the failure moment, full-session videos, and direct links to open the trace in Trace Viewer — along with the step timeline and error messages with code frames. It cannot include a backend database dump; that's entirely outside what Playwright observes (it only sees what happens in the browser and over the network, not the server's internal state).",
    },
    points: 1,
    timeEstimateSeconds: 35,
  },
  {
    id: "m8-e4",
    type: "true_false",
    difficulty: "easy",
    moduleIds: [M8],
    question: {
      es: "Según el módulo, leer solo el resumen de pasados/fallados del reporte HTML es suficiente para diagnosticar por qué falló un test — no es necesario revisar la traza, el screenshot ni el video.",
      en: "According to the module, reading only the pass/fail summary of the HTML report is enough to diagnose why a test failed — there's no need to check the trace, screenshot, or video.",
    },
    options: [
      { id: "true", text: { es: "Verdadero", en: "True" } },
      { id: "false", text: { es: "Falso", en: "False" } },
    ],
    correctOptionIds: ["false"],
    explanation: {
      es: "Falso. El módulo señala explícitamente que la mayoría de QAs solo miran el resumen de pasados/fallados, perdiéndose una herramienta de debugging extraordinaria: la línea de tiempo paso a paso, snapshots del DOM, errores con code frames, y artefactos como screenshots, videos y trazas. El resumen te dice QUÉ falló, pero solo investigando esos artefactos descubres POR QUÉ falló.",
      en: "False. The module explicitly points out that most QAs only glance at the pass/fail summary, missing an extraordinary debugging tool: the step-by-step timeline, DOM snapshots, errors with code frames, and artifacts like screenshots, videos, and traces. The summary tells you WHAT failed, but only investigating those artifacts reveals WHY it failed.",
    },
    points: 1,
    timeEstimateSeconds: 30,
  },
  {
    id: "m8-e5",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: [M8],
    question: {
      es: "¿Dónde debe vivir el archivo de workflow de GitHub Actions para Playwright?",
      en: "Where must the GitHub Actions workflow file for Playwright live?",
    },
    options: [
      { id: "a", text: { es: ".github/workflows/", en: ".github/workflows/" } },
      { id: "b", text: { es: ".ci/playwright/", en: ".ci/playwright/" } },
      { id: "c", text: { es: "playwright/workflows/", en: "playwright/workflows/" } },
      { id: "d", text: { es: "En cualquier carpeta, GitHub la detecta automáticamente por el nombre del archivo", en: "In any folder, GitHub detects it automatically by file name" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "Los workflows de GitHub Actions deben vivir en `.github/workflows/` dentro del repositorio — es una convención obligatoria de la plataforma, no opcional. GitHub escanea esa carpeta específica buscando archivos YAML; un archivo de workflow colocado en cualquier otra ruta simplemente no será detectado ni ejecutado.",
      en: "GitHub Actions workflows must live in `.github/workflows/` within the repository — it's a mandatory platform convention, not optional. GitHub scans that specific folder for YAML files; a workflow file placed in any other path simply won't be detected or run.",
    },
    points: 1,
    timeEstimateSeconds: 25,
  },
  {
    id: "m8-e6",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: [M8],
    question: {
      es: "En la sintaxis de un workflow de GitHub Actions, ¿qué controla la clave `on:`?",
      en: "In GitHub Actions workflow syntax, what does the `on:` key control?",
    },
    options: [
      { id: "a", text: { es: "Cuándo se ejecuta el workflow (ej. push, pull_request)", en: "When the workflow runs (e.g. push, pull_request)" } },
      { id: "b", text: { es: "Qué máquina virtual ejecuta los jobs", en: "Which virtual machine runs the jobs" } },
      { id: "c", text: { es: "Cuántos minutos puede durar el job como máximo", en: "How many minutes the job can run at most" } },
      { id: "d", text: { es: "Qué versión de Node.js se instala", en: "Which Node.js version gets installed" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "`on:` define los triggers — CUÁNDO se ejecuta el workflow, como en cada `push` a una rama o en cada `pull_request`. La máquina virtual se controla con `runs-on:`, el límite de tiempo con `timeout-minutes:`, y la versión de Node con el step `actions/setup-node` y su parámetro `node-version`.",
      en: "`on:` defines the triggers — WHEN the workflow runs, such as on every `push` to a branch or on every `pull_request`. The virtual machine is controlled with `runs-on:`, the time limit with `timeout-minutes:`, and the Node version with the `actions/setup-node` step and its `node-version` parameter.",
    },
    points: 1,
    timeEstimateSeconds: 30,
  },
  {
    id: "m8-e7",
    type: "true_false",
    difficulty: "easy",
    moduleIds: [M8],
    question: {
      es: "`ubuntu-latest` es el runner más común para ejecutar tests de Playwright en GitHub Actions.",
      en: "`ubuntu-latest` is the most common runner for executing Playwright tests in GitHub Actions.",
    },
    options: [
      { id: "true", text: { es: "Verdadero", en: "True" } },
      { id: "false", text: { es: "Falso", en: "False" } },
    ],
    correctOptionIds: ["true"],
    explanation: {
      es: "Correcto. El módulo lo señala directamente: `ubuntu-latest` es el runner más común para Playwright. Es rápido de provisionar, gratuito en los límites estándar de GitHub Actions para repos públicos, y Playwright instala sus navegadores sin problemas sobre Linux con `--with-deps`.",
      en: "Correct. The module states this directly: `ubuntu-latest` is the most common runner for Playwright. It provisions quickly, is free within GitHub Actions' standard limits for public repos, and Playwright installs its browsers smoothly on Linux with `--with-deps`.",
    },
    points: 1,
    timeEstimateSeconds: 25,
  },
  {
    id: "m8-e8",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: [M8],
    question: {
      es: "¿Qué es una traza (trace) de Playwright?",
      en: "What is a Playwright trace?",
    },
    options: [
      { id: "a", text: { es: "Un registro que captura acciones, snapshots del DOM, peticiones de red, consola y screenshots de toda la ejecución de un test", en: "A record that captures actions, DOM snapshots, network requests, console output, and screenshots across a test's entire run" } },
      { id: "b", text: { es: "Un simple log de texto con los nombres de los tests ejecutados", en: "A simple text log with the names of the tests that ran" } },
      { id: "c", text: { es: "Un archivo de configuración que define qué navegadores usar", en: "A configuration file that defines which browsers to use" } },
      { id: "d", text: { es: "Un reemplazo directo del reporte HTML que lo sustituye por completo", en: "A direct replacement for the HTML report that fully substitutes it" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "Una traza captura CADA interacción que Playwright tuvo con la página: acciones con timestamps, snapshots del DOM antes/después de cada acción, peticiones de red con headers y cuerpos, mensajes de consola, y screenshots. No es un simple log de texto ni un archivo de configuración, y no sustituye al reporte HTML — son complementarios: el HTML reporter te muestra el resumen y enlaza a la traza para el detalle profundo.",
      en: "A trace captures EVERY interaction Playwright had with the page: actions with timestamps, DOM snapshots before/after each action, network requests with headers and bodies, console messages, and screenshots. It isn't a plain text log or a config file, and it doesn't replace the HTML report — they're complementary: the HTML reporter shows you the summary and links to the trace for deep detail.",
    },
    points: 1,
    timeEstimateSeconds: 30,
  },
  {
    id: "m8-e9",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: [M8],
    question: {
      es: "¿Qué comando genera el reporte HTML de Allure a partir de los resultados de una ejecución?",
      en: "Which command generates the Allure HTML report from a run's results?",
    },
    options: [
      { id: "a", text: { es: "npx allure generate ./allure-results --clean", en: "npx allure generate ./allure-results --clean" } },
      { id: "b", text: { es: "npx playwright allure-build", en: "npx playwright allure-build" } },
      { id: "c", text: { es: "npm run build-allure-report", en: "npm run build-allure-report" } },
      { id: "d", text: { es: "npx allure-playwright export", en: "npx allure-playwright export" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "`npx allure generate ./allure-results --clean` toma los resultados crudos generados por el reporter `allure-playwright` (en la carpeta `allure-results`) y construye el reporte HTML interactivo. El flag `--clean` limpia la carpeta de salida antes de generar. Los demás comandos no existen en el flujo de Allure + Playwright descrito en el módulo.",
      en: "`npx allure generate ./allure-results --clean` takes the raw results generated by the `allure-playwright` reporter (in the `allure-results` folder) and builds the interactive HTML report. The `--clean` flag wipes the output folder before generating. The other commands don't exist in the Allure + Playwright flow described in the module.",
    },
    points: 1,
    timeEstimateSeconds: 30,
  },
  {
    id: "m8-e10",
    type: "true_false",
    difficulty: "easy",
    moduleIds: [M8],
    question: {
      es: "Es seguro escribir contraseñas y API keys directamente como texto plano en un archivo de workflow YAML que se sube al repositorio.",
      en: "It's safe to write passwords and API keys directly as plain text in a workflow YAML file pushed to the repository.",
    },
    options: [
      { id: "true", text: { es: "Verdadero", en: "True" } },
      { id: "false", text: { es: "Falso", en: "False" } },
    ],
    correctOptionIds: ["false"],
    explanation: {
      es: "Falso. Las credenciales hardcodeadas en archivos YAML son visibles para cualquiera que lea el repositorio, incluso en repos privados para cualquiera con acceso de lectura. El módulo es explícito: usa siempre `${{ secrets.NOMBRE }}` para valores sensibles, configurados en GitHub Settings > Secrets and variables > Actions. Los secretos se enmascaran automáticamente en los logs.",
      en: "False. Hardcoded credentials in YAML files are visible to anyone who reads the repository, even in private repos to anyone with read access. The module is explicit: always use `${{ secrets.NAME }}` for sensitive values, configured under GitHub Settings > Secrets and variables > Actions. Secrets are automatically masked in logs.",
    },
    points: 1,
    timeEstimateSeconds: 30,
  },

  /* ================================================================== */
  /*  MEDIUM (10 questions)                                              */
  /* ================================================================== */

  {
    id: "m8-m1",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: [M8],
    question: {
      es: "Tu equipo necesita feedback rápido en los logs de CI Y un reporte rico para debuggeo humano posterior. ¿Qué combinación de reporters es la correcta?",
      en: "Your team needs fast feedback in CI logs AND a rich report for later human debugging. Which reporter combination is correct?",
    },
    options: [
      { id: "a", text: { es: "['list'] para los logs de CI en tiempo real + ['html'] para el debuggeo posterior, ejecutados simultáneamente", en: "['list'] for real-time CI logs + ['html'] for later debugging, run simultaneously" } },
      { id: "b", text: { es: "Solo ['html'] — contiene toda la información necesaria para ambos casos", en: "Only ['html'] — it contains all the information needed for both cases" } },
      { id: "c", text: { es: "Solo ['dot'] — es el más rápido y suficiente para cualquier necesidad", en: "Only ['dot'] — it's the fastest and sufficient for any need" } },
      { id: "d", text: { es: "['junit'] para CI y ['line'] para debuggeo, porque junit es más rápido que list", en: "['junit'] for CI and ['line'] for debugging, because junit is faster than list" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "Playwright permite ejecutar múltiples reporters a la vez. `list` da feedback inmediato en los logs de CI (una línea por test, progreso en tiempo real); `html` genera el reporte interactivo completo para investigar fallos después. `html` solo no da visibilidad en tiempo real durante la ejecución; `dot` es demasiado minimalista; `junit` genera un XML para dashboards de CI pero no sustituye al feedback de línea por línea que da `list` en los logs.",
      en: "Playwright lets you run multiple reporters at once. `list` gives immediate feedback in CI logs (one line per test, real-time progress); `html` generates the full interactive report to investigate failures afterward. `html` alone gives no real-time visibility during the run; `dot` is too minimal; `junit` generates XML for CI dashboards but doesn't replace the line-by-line feedback `list` gives in logs.",
    },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "m8-m2",
    type: "code_output",
    difficulty: "medium",
    moduleIds: [M8],
    question: {
      es: "En este step de un workflow, ¿qué ocurre si la build anterior cacheó los navegadores correctamente?",
      en: "In this workflow step, what happens if the previous build correctly cached the browsers?",
    },
    codeSnippet: `- name: Cache Playwright browsers
  uses: actions/cache@v4
  id: pw-cache
  with:
    path: ~/.cache/ms-playwright
    key: playwright-browsers-\${{ runner.os }}-\${{ hashFiles('package-lock.json') }}

- name: Install Playwright browsers
  if: steps.pw-cache.outputs.cache-hit != 'true'
  run: npx playwright install --with-deps`,
    options: [
      { id: "a", text: { es: "El step 'Install Playwright browsers' se omite (skip) porque cache-hit es 'true', ahorrando el tiempo de descargar ~400 MB de navegadores", en: "The 'Install Playwright browsers' step is skipped because cache-hit is 'true', saving the time of downloading ~400 MB of browsers" } },
      { id: "b", text: { es: "El step se ejecuta de todas formas porque la condición if siempre evalúa a true", en: "The step runs anyway because the if condition always evaluates to true" } },
      { id: "c", text: { es: "actions/cache@v4 falla si la caché ya existe, deteniendo el workflow", en: "actions/cache@v4 fails if the cache already exists, halting the workflow" } },
      { id: "d", text: { es: "El cache-hit se ignora; npx playwright install siempre descarga los navegadores de nuevo", en: "cache-hit is ignored; npx playwright install always re-downloads the browsers" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "`actions/cache@v4` restaura la caché en la ruta `~/.cache/ms-playwright` si encuentra una coincidencia con la `key` dada, y expone `steps.pw-cache.outputs.cache-hit` como 'true' cuando hay un hit exacto. La condición `if: steps.pw-cache.outputs.cache-hit != 'true'` hace que el step de instalación se SALTE precisamente cuando la caché ya tiene los navegadores, evitando descargar de nuevo los ~400 MB. Si no hubiera cache-hit (ej. tras actualizar Playwright, lo que cambia el hash de package-lock.json), la condición sería true y el step sí se ejecutaría.",
      en: "`actions/cache@v4` restores the cache at the `~/.cache/ms-playwright` path if it finds a match for the given `key`, and exposes `steps.pw-cache.outputs.cache-hit` as 'true' on an exact hit. The condition `if: steps.pw-cache.outputs.cache-hit != 'true'` makes the install step SKIP precisely when the cache already has the browsers, avoiding re-downloading the ~400 MB. If there were no cache hit (e.g. after updating Playwright, which changes package-lock.json's hash), the condition would be true and the step would run.",
    },
    points: 2,
    timeEstimateSeconds: 65,
  },
  {
    id: "m8-m3",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: [M8],
    question: {
      es: "¿Por qué la clave de caché de navegadores incluye `hashFiles('package-lock.json')`?",
      en: "Why does the browser cache key include `hashFiles('package-lock.json')`?",
    },
    options: [
      { id: "a", text: { es: "Para que la caché se invalide automáticamente cuando se actualiza la versión de Playwright (el hash de package-lock.json cambia), forzando la reinstalación de los navegadores correctos", en: "So the cache invalidates automatically when the Playwright version is updated (package-lock.json's hash changes), forcing reinstallation of the correct browsers" } },
      { id: "b", text: { es: "Para evitar que GitHub Actions detecte cambios en el código fuente de los tests", en: "To prevent GitHub Actions from detecting changes in the test source code" } },
      { id: "c", text: { es: "Es un requisito sintáctico de actions/cache@v4 sin ningún efecto funcional", en: "It's a syntactic requirement of actions/cache@v4 with no functional effect" } },
      { id: "d", text: { es: "Para acelerar el hash y que la caché se restaure más rápido", en: "To speed up hashing so the cache restores faster" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "Incluir el hash de `package-lock.json` en la clave de caché significa que la clave cambia automáticamente cada vez que cambian las dependencias del proyecto, incluida la versión de Playwright. Si actualizas Playwright, el hash cambia, la clave de caché ya no coincide con ninguna entrada existente, y el step de instalación se ejecuta de nuevo para descargar la versión correcta de los navegadores — evitando el bug de usar binarios de navegador obsoletos con una versión más nueva de Playwright.",
      en: "Including `package-lock.json`'s hash in the cache key means the key automatically changes whenever the project's dependencies change, including the Playwright version. If you update Playwright, the hash changes, the cache key no longer matches any existing entry, and the install step runs again to download the correct browser version — avoiding the bug of using stale browser binaries with a newer Playwright version.",
    },
    points: 2,
    timeEstimateSeconds: 55,
  },
  {
    id: "m8-m4",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: [M8],
    question: {
      es: "¿Cuál es la diferencia funcional entre `trace: 'on-first-retry'` y `trace: 'on'` en `playwright.config.ts`?",
      en: "What's the functional difference between `trace: 'on-first-retry'` and `trace: 'on'` in `playwright.config.ts`?",
    },
    options: [
      { id: "a", text: { es: "'on-first-retry' solo graba traza cuando un test falla y se reintenta (cero overhead en verde); 'on' graba SIEMPRE, generando archivos enormes en cada build", en: "'on-first-retry' only records a trace when a test fails and retries (zero overhead on green); 'on' ALWAYS records, generating huge files on every build" } },
      { id: "b", text: { es: "Son exactamente equivalentes, solo cambia el nombre de la opción", en: "They're exactly equivalent, only the option's name differs" } },
      { id: "c", text: { es: "'on' es más rápido porque no necesita reintentos para activarse", en: "'on' is faster because it doesn't need retries to activate" } },
      { id: "d", text: { es: "'on-first-retry' deshabilita por completo la grabación de trazas en CI", en: "'on-first-retry' completely disables trace recording in CI" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "`on-first-retry` es el punto dulce: en builds verdes (todo pasa) no se graba nada, cero impacto en rendimiento; en builds rojas, la traza se graba en el primer reintento, dándote datos completos justo cuando los necesitas. `trace: 'on'` graba SIEMPRE, en cada test de cada build, generando cientos de MB que rara vez se revisan. No son equivalentes, 'on' no es más rápido (es más lento por el overhead constante), y 'on-first-retry' no deshabilita las trazas — las habilita selectivamente.",
      en: "`on-first-retry` is the sweet spot: on green builds (everything passes) nothing is recorded, zero performance impact; on red builds, the trace is recorded on the first retry, giving you full data exactly when you need it. `trace: 'on'` ALWAYS records, on every test of every build, generating hundreds of MB rarely reviewed. They aren't equivalent, 'on' isn't faster (it's slower due to constant overhead), and 'on-first-retry' doesn't disable traces — it enables them selectively.",
    },
    points: 2,
    timeEstimateSeconds: 55,
  },
  {
    id: "m8-m5",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: [M8],
    question: {
      es: "Un test falló en CI por una llamada a la API que devolvió un código inesperado. ¿Qué panel del Trace Viewer revela esto directamente?",
      en: "A test failed in CI because of an API call that returned an unexpected status code. Which Trace Viewer panel reveals this directly?",
    },
    options: [
      { id: "a", text: { es: "El panel 'Network', que muestra todas las llamadas HTTP con sus códigos de estado, headers y cuerpos", en: "The 'Network' panel, which shows all HTTP calls with their status codes, headers, and bodies" } },
      { id: "b", text: { es: "El panel 'Console', que solo muestra console.log del navegador", en: "The 'Console' panel, which only shows browser console.log output" } },
      { id: "c", text: { es: "El panel 'Actions', que solo muestra clicks y fills, sin información de red", en: "The 'Actions' panel, which only shows clicks and fills, without network info" } },
      { id: "d", text: { es: "No es posible ver llamadas de red en una traza; hay que revisar logs del servidor", en: "It's not possible to see network calls in a trace; you must check server logs" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "El panel 'Network' de la traza revela todas las llamadas HTTP que hizo la página, incluyendo headers, cuerpo y código de estado de cada respuesta. Si un test falla porque la API devolvió 500 en lugar de 200, ese panel lo muestra directamente. El panel 'Console' expone errores de JavaScript del frontend, no llamadas de red. El panel 'Actions' muestra comandos de Playwright (clicks, fills, expects), no detalles de red. No es necesario acceder a logs del servidor — la traza ya captura la conversación HTTP completa desde el lado del navegador.",
      en: "The trace's 'Network' panel reveals all HTTP calls the page made, including headers, body, and status code for each response. If a test fails because the API returned 500 instead of 200, that panel shows it directly. The 'Console' panel exposes frontend JavaScript errors, not network calls. The 'Actions' panel shows Playwright commands (clicks, fills, expects), not network details. There's no need to access server logs — the trace already captures the full HTTP conversation from the browser's side.",
    },
    points: 2,
    timeEstimateSeconds: 55,
  },
  {
    id: "m8-m6",
    type: "code_output",
    difficulty: "medium",
    moduleIds: [M8],
    question: {
      es: "Dada esta configuración de reporters, ¿qué carpetas/archivos se generan tras ejecutar los tests, y para qué audiencia sirve cada uno?",
      en: "Given this reporter configuration, what folders/files are generated after running the tests, and which audience does each serve?",
    },
    codeSnippet: `export default defineConfig({
  reporter: [
    ['html', { open: 'never' }],
    ['list'],
    ['junit', { outputFile: 'test-results/junit.xml' }],
    ['json', { outputFile: 'test-results/results.json' }],
  ],
});`,
    options: [
      { id: "a", text: { es: "html genera playwright-report/ (humanos debuggeando), list imprime en terminal (CI logs), junit genera junit.xml (Jenkins/GitLab/Azure DevOps), json genera results.json (dashboards programáticos)", en: "html generates playwright-report/ (humans debugging), list prints to terminal (CI logs), junit generates junit.xml (Jenkins/GitLab/Azure DevOps), json generates results.json (programmatic dashboards)" } },
      { id: "b", text: { es: "Solo se genera un archivo, porque Playwright no permite más de un reporter activo a la vez", en: "Only one file is generated, because Playwright doesn't allow more than one active reporter at a time" } },
      { id: "c", text: { es: "junit y json son redundantes y Playwright ignora uno de los dos automáticamente", en: "junit and json are redundant and Playwright automatically ignores one of the two" } },
      { id: "d", text: { es: "open: 'never' impide que se genere cualquier archivo HTML", en: "open: 'never' prevents any HTML file from being generated" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "Playwright permite múltiples reporters simultáneos, cada uno generando su propia salida sin interferir entre sí: `html` (con `open: 'never'` para no abrir el navegador automáticamente) genera la carpeta `playwright-report/` para debug humano; `list` solo imprime en la terminal sin generar archivos, ideal para logs de CI en tiempo real; `junit` genera el XML estándar que leen Jenkins/GitLab/Azure DevOps; `json` genera datos estructurados para dashboards personalizados. No son redundantes ni se excluyen — cada uno sirve a una audiencia distinta, y `open: 'never'` solo evita la apertura automática del navegador, no la generación del archivo.",
      en: "Playwright allows multiple simultaneous reporters, each generating its own output without interfering: `html` (with `open: 'never'` to avoid auto-opening the browser) generates the `playwright-report/` folder for human debugging; `list` only prints to the terminal without generating files, ideal for real-time CI logs; `junit` generates the standard XML that Jenkins/GitLab/Azure DevOps read; `json` generates structured data for custom dashboards. They aren't redundant or mutually exclusive — each serves a different audience, and `open: 'never'` only prevents auto-opening the browser, not generating the file.",
    },
    points: 2,
    timeEstimateSeconds: 65,
  },
  {
    id: "m8-m7",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: [M8],
    question: {
      es: "¿Qué aporta el `strategy.matrix` en un workflow de GitHub Actions con `browser: [chromium, firefox, webkit]`?",
      en: "What does `strategy.matrix` provide in a GitHub Actions workflow with `browser: [chromium, firefox, webkit]`?",
    },
    options: [
      { id: "a", text: { es: "Ejecuta el job 3 veces, una vez por cada navegador, en paralelo por defecto", en: "It runs the job 3 times, once per browser, in parallel by default" } },
      { id: "b", text: { es: "Ejecuta el job una sola vez, probando los 3 navegadores secuencialmente dentro del mismo runner", en: "It runs the job only once, testing the 3 browsers sequentially within the same runner" } },
      { id: "c", text: { es: "Solo funciona si fail-fast está en true", en: "It only works if fail-fast is set to true" } },
      { id: "d", text: { es: "matrix es exclusivo de proyectos que no usan Playwright", en: "matrix is exclusive to projects that don't use Playwright" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "`strategy.matrix` con `browser: [chromium, firefox, webkit]` instruye a GitHub Actions a ejecutar el job una vez POR CADA valor de la matriz — en este caso, 3 ejecuciones independientes, una por navegador, en runners separados que corren en paralelo por defecto. `fail-fast: false` (mostrado en el ejemplo del módulo) evita que un fallo en un navegador cancele los demás; no es un requisito para que matrix funcione, sino una opción adicional. matrix es una característica genérica de GitHub Actions, no algo exclusivo o ajeno a Playwright.",
      en: "`strategy.matrix` with `browser: [chromium, firefox, webkit]` instructs GitHub Actions to run the job once PER matrix value — in this case, 3 independent runs, one per browser, on separate runners that execute in parallel by default. `fail-fast: false` (shown in the module's example) prevents a failure on one browser from cancelling the others; it isn't a requirement for matrix to work, just an additional option. matrix is a generic GitHub Actions feature, not something exclusive to or incompatible with Playwright.",
    },
    points: 2,
    timeEstimateSeconds: 55,
  },
  {
    id: "m8-m8",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: [M8],
    question: {
      es: "Según el módulo, ¿cuándo conviene migrar de solo HTML reporter a Allure?",
      en: "According to the module, when does it make sense to migrate from only the HTML reporter to Allure?",
    },
    options: [
      { id: "a", text: { es: "Cuando el equipo crece y necesita tendencias históricas entre builds, categorización por severidad/feature, y dashboards multi-suite", en: "When the team grows and needs historical trends across builds, severity/feature categorization, and multi-suite dashboards" } },
      { id: "b", text: { es: "Inmediatamente al empezar cualquier proyecto, sin importar el tamaño del equipo o la suite", en: "Immediately when starting any project, regardless of team size or suite size" } },
      { id: "c", text: { es: "Nunca — Allure no aporta nada que el HTML reporter nativo no tenga ya", en: "Never — Allure adds nothing the native HTML reporter doesn't already have" } },
      { id: "d", text: { es: "Solo si el equipo usa exclusivamente Jenkins como plataforma de CI", en: "Only if the team exclusively uses Jenkins as their CI platform" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "El módulo da una regla explícita: empieza con HTML reporter; migra a Allure cuando sientas el dolor de no tener histórico. Allure brilla con 50+ builds de historia, mostrando tendencias, categorización por severidad/feature y dashboards multi-suite. Para un equipo de 2-3 personas con 50 tests, Allure es 'probablemente overkill'. No es algo a adoptar desde el día uno ni algo atado a una plataforma de CI específica como Jenkins.",
      en: "The module gives an explicit rule: start with HTML reporter; migrate to Allure when you feel the pain of not having history. Allure shines with 50+ builds of history, showing trends, severity/feature categorization, and multi-suite dashboards. For a 2-3 person team with 50 tests, Allure is 'probably overkill'. It isn't something to adopt from day one, nor is it tied to a specific CI platform like Jenkins.",
    },
    points: 2,
    timeEstimateSeconds: 50,
  },
  {
    id: "m8-m9",
    type: "code_output",
    difficulty: "medium",
    moduleIds: [M8],
    question: {
      es: "¿Qué hace esta anotación de Allure dentro de un test, y dónde aparecerá en el reporte generado?",
      en: "What does this Allure annotation inside a test do, and where will it appear in the generated report?",
    },
    codeSnippet: `test('checkout with invalid coupon', async ({ page }) => {
  await allure.severity('critical');
  await allure.tag('checkout');
  await allure.issue(
    'https://github.com/team/playqa/issues/42',
    'BUG-42: Coupon validation returns 500'
  );
  // ...
});`,
    options: [
      { id: "a", text: { es: "Marca el test con severidad 'critical', lo etiqueta como 'checkout' para filtrado, y añade un enlace clicable al issue de GitHub directamente en el reporte de Allure", en: "It marks the test with 'critical' severity, tags it as 'checkout' for filtering, and adds a clickable link to the GitHub issue directly in the Allure report" } },
      { id: "b", text: { es: "Estas llamadas no tienen ningún efecto visible; son solo comentarios de documentación interna", en: "These calls have no visible effect; they're just internal documentation comments" } },
      { id: "c", text: { es: "allure.issue() crea automáticamente un nuevo issue en GitHub si no existe", en: "allure.issue() automatically creates a new GitHub issue if it doesn't exist" } },
      { id: "d", text: { es: "Estas anotaciones solo funcionan si el test usa el reporter HTML, no con Allure", en: "These annotations only work if the test uses the HTML reporter, not Allure" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "`allure.severity('critical')` categoriza el test por severidad, `allure.tag('checkout')` permite filtrar por etiqueta en el dashboard, y `allure.issue(url, descripcion)` añade un enlace clicable al ticket de GitHub/JIRA directamente en el reporte — el desarrollador hace clic y va directo al ticket. Estas llamadas SÍ tienen efecto visible en el reporte de Allure generado (no son solo comentarios), `allure.issue()` solo enlaza, no crea issues automáticamente, y estas anotaciones son específicas del reporter `allure-playwright`, no del HTML reporter nativo.",
      en: "`allure.severity('critical')` categorizes the test by severity, `allure.tag('checkout')` allows filtering by tag in the dashboard, and `allure.issue(url, description)` adds a clickable link to the GitHub/JIRA ticket directly in the report — the developer clicks and goes straight to the ticket. These calls DO have a visible effect on the generated Allure report (they aren't just comments), `allure.issue()` only links, it doesn't auto-create issues, and these annotations are specific to the `allure-playwright` reporter, not the native HTML reporter.",
    },
    points: 2,
    timeEstimateSeconds: 60,
  },
  {
    id: "m8-m10",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: [M8],
    question: {
      es: "En el workflow del ejercicio capstone, ¿por qué el step 'Install dependencies' (`npm ci`) debe ejecutarse ANTES del step 'Install Playwright browsers'?",
      en: "In the capstone exercise workflow, why must the 'Install dependencies' step (`npm ci`) run BEFORE the 'Install Playwright browsers' step?",
    },
    options: [
      { id: "a", text: { es: "Porque el comando `npx playwright install` requiere que el paquete @playwright/test ya esté instalado en node_modules para resolver la CLI", en: "Because `npx playwright install` requires the @playwright/test package to already be installed in node_modules to resolve the CLI" } },
      { id: "b", text: { es: "El orden no importa, ambos steps son completamente independientes entre sí", en: "The order doesn't matter, both steps are completely independent of each other" } },
      { id: "c", text: { es: "Porque GitHub Actions ejecuta los steps en orden alfabético, no en el orden declarado", en: "Because GitHub Actions runs steps in alphabetical order, not the order declared" } },
      { id: "d", text: { es: "Porque npm ci necesita los navegadores de Playwright ya descargados para validar el package-lock.json", en: "Because npm ci needs Playwright's browsers already downloaded to validate package-lock.json" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "`npx playwright install` (o `npx playwright install --with-deps`) necesita resolver el paquete `@playwright/test` (o `playwright`) desde `node_modules` para saber qué versión de navegadores instalar y ejecutar la CLI correspondiente. Si `npm ci` no se ha ejecutado todavía, ese paquete no existe en el proyecto y el comando falla. GitHub Actions ejecuta los steps en el orden EXACTO en que están declarados en el YAML (no alfabético), por lo que invertir el orden rompería el pipeline.",
      en: "`npx playwright install` (or `npx playwright install --with-deps`) needs to resolve the `@playwright/test` (or `playwright`) package from `node_modules` to know which browser version to install and run the matching CLI. If `npm ci` hasn't run yet, that package doesn't exist in the project and the command fails. GitHub Actions runs steps in the EXACT order they're declared in the YAML (not alphabetically), so reversing the order would break the pipeline.",
    },
    points: 2,
    timeEstimateSeconds: 60,
  },

  /* ================================================================== */
  /*  HARD (5 questions)                                                 */
  /* ================================================================== */

  {
    id: "m8-h1",
    type: "code_output",
    difficulty: "hard",
    moduleIds: [M8],
    question: {
      es: "Este workflow tiene un defecto crítico para depurar fallos. ¿Cuál es, y qué consecuencia tiene cuando los tests fallan en CI?",
      en: "This workflow has a critical flaw for debugging failures. What is it, and what's the consequence when tests fail in CI?",
    },
    codeSnippet: `jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/`,
    options: [
      { id: "a", text: { es: "Falta `if: always()` en el step de upload: si `npx playwright test` falla, GitHub Actions detiene la ejecución de steps posteriores y el reporte HTML NUNCA se sube, dejando al equipo sin forma de diagnosticar el fallo", en: "It's missing `if: always()` on the upload step: if `npx playwright test` fails, GitHub Actions stops running subsequent steps and the HTML report is NEVER uploaded, leaving the team with no way to diagnose the failure" } },
      { id: "b", text: { es: "El workflow está completo y correcto; no hace falta ninguna condición especial en el upload", en: "The workflow is complete and correct; no special condition is needed on the upload" } },
      { id: "c", text: { es: "El problema es que falta una matriz de navegadores, sin la cual upload-artifact no funciona", en: "The problem is the missing browser matrix, without which upload-artifact doesn't work" } },
      { id: "d", text: { es: "actions/upload-artifact@v4 sube el reporte automáticamente sin necesidad de declarar ningún step, así que el problema está en otro lado", en: "actions/upload-artifact@v4 uploads the report automatically without needing a declared step, so the problem lies elsewhere" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "Por defecto, GitHub Actions detiene la ejecución de steps posteriores en cuanto un step falla. Si `npx playwright test` falla (que es exactamente cuando más necesitas el reporte), el step 'Upload HTML report' nunca se ejecuta porque carece de `if: always()`. El resultado es que en cada build roja, el equipo no tiene ningún reporte HTML, screenshot, video ni traza para investigar — exactamente el escenario que el módulo advierte como crítico de evitar. La matriz de navegadores es independiente de este problema, y upload-artifact no se ejecuta automáticamente: requiere un step explícito que, en este caso, sí está declarado pero nunca se alcanza tras un fallo.",
      en: "By default, GitHub Actions stops running subsequent steps as soon as one fails. If `npx playwright test` fails (exactly when you need the report most), the 'Upload HTML report' step never runs because it lacks `if: always()`. The result is that on every red build, the team has no HTML report, screenshot, video, or trace to investigate — exactly the critical scenario the module warns against. The browser matrix is unrelated to this problem, and upload-artifact doesn't run automatically: it requires an explicit step which, in this case, is declared but never reached after a failure.",
    },
    points: 3,
    timeEstimateSeconds: 100,
  },
  {
    id: "m8-h2",
    type: "code_output",
    difficulty: "hard",
    moduleIds: [M8],
    question: {
      es: "Este workflow tiene un orden de steps que rompe la estrategia de caché de navegadores. ¿Cuál es el problema?",
      en: "This workflow's step order breaks the browser caching strategy. What's the problem?",
    },
    codeSnippet: `steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-node@v4
    with:
      node-version: 20
      cache: 'npm'

  - name: Install Playwright browsers
    run: npx playwright install --with-deps

  - name: Cache Playwright browsers
    uses: actions/cache@v4
    id: pw-cache
    with:
      path: ~/.cache/ms-playwright
      key: playwright-\${{ runner.os }}-\${{ hashFiles('package-lock.json') }}

  - run: npm ci
  - run: npx playwright test`,
    options: [
      { id: "a", text: { es: "El step de 'Cache' se registra DESPUÉS de instalar los navegadores, así que la primera ejecución no se beneficia de la caché para evitar la instalación, y además npm ci se ejecuta después de instalar los navegadores, lo cual es ilógico ya que install necesita el paquete de Playwright resuelto desde node_modules", en: "The 'Cache' step is registered AFTER installing the browsers, so the first run doesn't benefit from the cache to skip installation, and additionally npm ci runs after installing the browsers, which is illogical since install needs the Playwright package resolved from node_modules" } },
      { id: "b", text: { es: "El workflow es funcionalmente idéntico a poner cache antes de install; el orden de steps nunca afecta el comportamiento de actions/cache", en: "The workflow is functionally identical to placing cache before install; step order never affects actions/cache's behavior" } },
      { id: "c", text: { es: "El único problema es que falta timeout-minutes, el resto del orden es correcto", en: "The only problem is the missing timeout-minutes, the rest of the order is correct" } },
      { id: "d", text: { es: "actions/cache@v4 reordena automáticamente los steps en tiempo de ejecución para optimizar el pipeline", en: "actions/cache@v4 automatically reorders steps at runtime to optimize the pipeline" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "Hay dos problemas de orden aquí. Primero: 'Install Playwright browsers' se ejecuta ANTES de que exista el step de 'Cache' — el patrón correcto es cachear/restaurar primero, y luego condicionar la instalación con `if: steps.pw-cache.outputs.cache-hit != 'true'`; tal como está, siempre se instalan los navegadores sin aprovechar nunca la caché para saltarse ese paso. Segundo, y más grave: `npx playwright install --with-deps` se ejecuta ANTES de `npm ci`, pero ese comando necesita resolver el paquete `playwright`/`@playwright/test` desde `node_modules`, que todavía no existe porque las dependencias no se han instalado — esto haría fallar el step de instalación de navegadores directamente. GitHub Actions ejecuta los steps estrictamente en el orden declarado; no hay reordenamiento automático.",
      en: "There are two ordering problems here. First: 'Install Playwright browsers' runs BEFORE the 'Cache' step even exists — the correct pattern is to cache/restore first, then gate the install with `if: steps.pw-cache.outputs.cache-hit != 'true'`; as written, browsers are always installed, never benefiting from the cache to skip that step. Second, and more severe: `npx playwright install --with-deps` runs BEFORE `npm ci`, but that command needs to resolve the `playwright`/`@playwright/test` package from `node_modules`, which doesn't exist yet because dependencies haven't been installed — this would make the browser install step fail outright. GitHub Actions runs steps strictly in declared order; there's no automatic reordering.",
    },
    points: 3,
    timeEstimateSeconds: 110,
  },
  {
    id: "m8-h3",
    type: "code_output",
    difficulty: "hard",
    moduleIds: [M8],
    question: {
      es: "Esta configuración de reporters mezcla HTML y Allure de forma incorrecta. ¿Cuál es el defecto?",
      en: "This reporter configuration mixes HTML and Allure incorrectly. What's the flaw?",
    },
    codeSnippet: `export default defineConfig({
  reporter: [
    ['html', { open: 'never' }],
    ['allure-playwright', { outputFolder: 'playwright-report' }],
  ],
});`,
    options: [
      { id: "a", text: { es: "Ambos reporters usan la misma carpeta de salida ('playwright-report'), por lo que el HTML reporter y Allure escriben/sobrescriben archivos en la misma ruta, corrompiendo potencialmente ambos reportes", en: "Both reporters use the same output folder ('playwright-report'), so the HTML reporter and Allure write/overwrite files in the same path, potentially corrupting both reports" } },
      { id: "b", text: { es: "No se puede usar 'html' y 'allure-playwright' en el mismo array de reporters bajo ninguna circunstancia", en: "You can't use 'html' and 'allure-playwright' in the same reporters array under any circumstances" } },
      { id: "c", text: { es: "open: 'never' es incompatible con allure-playwright y provoca un error de configuración", en: "open: 'never' is incompatible with allure-playwright and causes a configuration error" } },
      { id: "d", text: { es: "El problema es que falta 'list' en el array; sin él, ningún reporter de la lista se ejecuta", en: "The problem is the missing 'list' in the array; without it, no reporter in the list runs" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "El `outputFolder` de `html` y el `outputFolder` de `allure-playwright` están apuntando ambos a `'playwright-report'`. Cada reporter escribe su propia estructura de archivos en esa carpeta (el HTML reporter genera su bundle de assets e index.html; Allure genera archivos `.json` y `.txt` de resultados crudos), y al compartir la misma ruta corren el riesgo de pisarse archivos entre sí o de que herramientas posteriores (como `allure generate`) lean una carpeta contaminada con archivos que no son suyos. El módulo sí permite combinar `html` y `allure-playwright` simultáneamente — el error está específicamente en reutilizar la misma carpeta de salida; la corrección es darle a Allure su propia carpeta, típicamente `'allure-results'`.",
      en: "Both `html`'s `outputFolder` and `allure-playwright`'s `outputFolder` point to `'playwright-report'`. Each reporter writes its own file structure into that folder (the HTML reporter generates its asset bundle and index.html; Allure generates raw `.json` and `.txt` result files), and sharing the same path risks files overwriting each other or downstream tools (like `allure generate`) reading a folder polluted with files that aren't theirs. The module does allow combining `html` and `allure-playwright` simultaneously — the error specifically lies in reusing the same output folder; the fix is to give Allure its own folder, typically `'allure-results'`.",
    },
    points: 3,
    timeEstimateSeconds: 105,
  },
  {
    id: "m8-h4",
    type: "multiple_choice",
    difficulty: "hard",
    moduleIds: [M8],
    question: {
      es: "Revisando este workflow incompleto, ¿cuáles de las siguientes afirmaciones sobre sus defectos son correctas? (Selecciona todas las correctas)",
      en: "Reviewing this incomplete workflow, which of the following statements about its flaws are correct? (Select all that apply)",
    },
    codeSnippet: `name: Playwright Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/`,
    options: [
      { id: "a", text: { es: "Falta el trigger `pull_request`: los tests solo se ejecutan en push a main, no validan PRs antes de hacer merge", en: "It's missing the `pull_request` trigger: tests only run on push to main, they don't validate PRs before merging" } },
      { id: "b", text: { es: "Falta `timeout-minutes` en el job: un workflow colgado podría correr indefinidamente (o hasta el límite por defecto de GitHub, mucho mayor a lo razonable)", en: "It's missing `timeout-minutes` on the job: a hung workflow could run indefinitely (or up to GitHub's much larger default limit)" } },
      { id: "c", text: { es: "Falta `if: always()` en el step de upload-artifact: si los tests fallan, el reporte nunca se sube", en: "It's missing `if: always()` on the upload-artifact step: if tests fail, the report never uploads" } },
      { id: "d", text: { es: "El workflow está completo y no le falta nada relevante", en: "The workflow is complete and nothing relevant is missing" } },
    ],
    correctOptionIds: ["a", "b", "c"],
    explanation: {
      es: "Tres defectos reales: (a) sin trigger `pull_request`, los tests no se ejecutan al abrir o actualizar un PR, perdiendo la protección de detectar regresiones ANTES del merge — solo se entera el equipo después de que el código ya está en main; (b) sin `timeout-minutes`, un test colgado (ej. esperando un selector que nunca aparece) puede consumir minutos de cómputo de CI sin límite explícito del equipo; (c) sin `if: always()` en el upload, exactamente como advierte el módulo, el reporte HTML no se sube cuando los tests fallan, que es cuando más se necesita para diagnosticar. (d) es incorrecta porque sí hay defectos identificables y corregibles.",
      en: "Three real flaws: (a) without the `pull_request` trigger, tests don't run when a PR is opened or updated, losing the protection of catching regressions BEFORE the merge — the team only finds out after the code is already in main; (b) without `timeout-minutes`, a hung test (e.g. waiting on a selector that never appears) can consume CI compute time with no explicit limit set by the team; (c) without `if: always()` on the upload, exactly as the module warns, the HTML report doesn't upload when tests fail, which is exactly when it's needed most to diagnose. (d) is incorrect because there are identifiable, fixable flaws.",
    },
    points: 3,
    timeEstimateSeconds: 120,
  },
  {
    id: "m8-h5",
    type: "code_output",
    difficulty: "hard",
    moduleIds: [M8],
    question: {
      es: "Este step de caché de navegadores tiene un defecto sutil que hace que la caché nunca funcione correctamente entre builds. ¿Cuál es?",
      en: "This browser cache step has a subtle flaw that makes the cache never work correctly across builds. What is it?",
    },
    codeSnippet: `- name: Cache Playwright browsers
  uses: actions/cache@v4
  id: pw-cache
  with:
    path: ~/.cache/ms-playwright
    key: playwright-browsers-\${{ github.run_id }}

- name: Install Playwright browsers
  if: steps.pw-cache.outputs.cache-hit != 'true'
  run: npx playwright install --with-deps`,
    options: [
      { id: "a", text: { es: "La clave usa `github.run_id`, que es ÚNICO en cada ejecución del workflow; por lo tanto, ninguna build futura coincidirá jamás con una clave anterior, y cache-hit siempre será falso, forzando la reinstalación completa en cada build", en: "The key uses `github.run_id`, which is UNIQUE on every workflow run; therefore no future build will ever match a previous key, and cache-hit will always be false, forcing a full reinstall on every build" } },
      { id: "b", text: { es: "El path `~/.cache/ms-playwright` es incorrecto; Playwright nunca guarda navegadores ahí", en: "The path `~/.cache/ms-playwright` is wrong; Playwright never stores browsers there" } },
      { id: "c", text: { es: "El id 'pw-cache' es una palabra reservada en GitHub Actions y causa un error de sintaxis", en: "The id 'pw-cache' is a reserved word in GitHub Actions and causes a syntax error" } },
      { id: "d", text: { es: "No hay ningún problema: run_id es la mejor práctica recomendada para claves de caché de navegadores", en: "There's no problem: run_id is the recommended best practice for browser cache keys" } },
    ],
    correctOptionIds: ["a"],
    explanation: {
      es: "`github.run_id` es un identificador único para CADA ejecución del workflow — nunca se repite entre builds. Como la clave de caché incluye ese valor único, ninguna build posterior podrá generar la MISMA clave que una build anterior, así que `actions/cache` jamás encontrará una coincidencia: `cache-hit` será siempre `'false'` o vacío, y el step de instalación se ejecutará en CADA build, descargando los ~400 MB de navegadores cada vez — exactamente el escenario que la caché está diseñada para evitar. La clave correcta debe ser estable entre builds y cambiar solo cuando las dependencias cambian, como `hashFiles('package-lock.json')`. El path y el id no son el problema; ambos son válidos.",
      en: "`github.run_id` is a unique identifier for EACH workflow run — it never repeats across builds. Since the cache key includes that unique value, no later build can ever generate the SAME key as an earlier build, so `actions/cache` will never find a match: `cache-hit` will always be `'false'` or empty, and the install step will run on EVERY build, downloading the ~400 MB of browsers each time — exactly the scenario caching is meant to prevent. The correct key should be stable across builds and only change when dependencies change, like `hashFiles('package-lock.json')`. The path and id aren't the problem; both are valid.",
    },
    points: 3,
    timeEstimateSeconds: 110,
  },
];

/* ------------------------------------------------------------------ */
/*  Registration                                                       */
/* ------------------------------------------------------------------ */

registerQuestions(QUESTIONS);
