/**
 * QA Fundamentals — Banco de preguntas Módulo 1
 * (Introducción al QA y al Testing de Software).
 * Fuentes: ISTQB CTFL v4.0 (cap. 1), ISTQB Glossary.
 */

import type { ExamQuestion } from "@/types/exam";
import { registerQuestions } from "@/lib/exam/scoring";

const M = ["qaf-m1"];

const QUESTIONS: ExamQuestion[] = [
  {
    id: "qaf-m1-e1",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Cuál es el objetivo principal del testing de software?", en: "What is the main objective of software testing?" },
    options: [
      { id: "a", text: { es: "Demostrar que el software no tiene defectos", en: "Prove the software has no defects" } },
      { id: "b", text: { es: "Evaluar la calidad y reducir el riesgo de fallos", en: "Evaluate quality and reduce the risk of failures" } },
      { id: "c", text: { es: "Reemplazar al equipo de desarrollo", en: "Replace the development team" } },
      { id: "d", text: { es: "Escribir el código de la aplicación", en: "Write the application code" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El testing evalúa la calidad y reduce riesgos; no puede demostrar la ausencia de defectos.", en: "Testing evaluates quality and reduces risk; it cannot prove the absence of defects." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "qaf-m1-e2",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Qué describe MEJOR el aseguramiento de calidad (QA)?", en: "What BEST describes quality assurance (QA)?" },
    options: [
      { id: "a", text: { es: "Una actividad para ejecutar casos de prueba", en: "An activity to run test cases" } },
      { id: "b", text: { es: "Un enfoque orientado al proceso para prevenir defectos", en: "A process-oriented approach to prevent defects" } },
      { id: "c", text: { es: "La corrección de defectos en el código", en: "Fixing defects in the code" } },
      { id: "d", text: { es: "El despliegue del software a producción", en: "Deploying software to production" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "QA se orienta al proceso para prevenir defectos; el testing es una actividad concreta dentro de QA.", en: "QA is process-oriented to prevent defects; testing is a concrete activity within QA." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "qaf-m1-e3",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "Un desarrollador teclea '+' donde debía ir '-'. ¿Cómo se clasifica esa acción humana?", en: "A developer types '+' where '-' was needed. How is that human action classified?" },
    options: [
      { id: "a", text: { es: "Error", en: "Error" } },
      { id: "b", text: { es: "Defecto", en: "Defect" } },
      { id: "c", text: { es: "Fallo", en: "Failure" } },
      { id: "d", text: { es: "Riesgo", en: "Risk" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La acción humana incorrecta es un error (mistake), que introduce un defecto en el código.", en: "The incorrect human action is an error (mistake), which introduces a defect in the code." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "qaf-m1-e4",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "El usuario ve un total equivocado en la factura. Eso es un…", en: "The user sees a wrong total on the invoice. That is a…" },
    options: [
      { id: "a", text: { es: "Error", en: "Error" } },
      { id: "b", text: { es: "Defecto", en: "Defect" } },
      { id: "c", text: { es: "Fallo", en: "Failure" } },
      { id: "d", text: { es: "Causa raíz", en: "Root cause" } },
    ],
    correctOptionIds: ["c"],
    explanation: { es: "El comportamiento observable incorrecto en ejecución es un fallo (failure).", en: "The incorrect observable behavior at runtime is a failure." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "qaf-m1-e5",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Qué principio dice que el testing exhaustivo es imposible?", en: "Which principle says exhaustive testing is impossible?" },
    options: [
      { id: "a", text: { es: "Principio 1", en: "Principle 1" } },
      { id: "b", text: { es: "Principio 2", en: "Principle 2" } },
      { id: "c", text: { es: "Principio 4", en: "Principle 4" } },
      { id: "d", text: { es: "Principio 7", en: "Principle 7" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El principio 2 establece que probar todas las combinaciones es inviable; hay que priorizar.", en: "Principle 2 states that testing all combinations is infeasible; prioritization is needed." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "qaf-m1-e6",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "Los casos de prueba repetidos dejan de encontrar defectos nuevos. ¿Qué principio es?", en: "Repeated test cases stop finding new defects. Which principle is this?" },
    options: [
      { id: "a", text: { es: "Agrupación de defectos", en: "Defect clustering" } },
      { id: "b", text: { es: "Paradoja del pesticida", en: "Pesticide paradox" } },
      { id: "c", text: { es: "Testing temprano", en: "Early testing" } },
      { id: "d", text: { es: "Testing depende del contexto", en: "Context-dependent testing" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "La paradoja del pesticida: hay que renovar los casos para seguir encontrando defectos.", en: "The pesticide paradox: cases must be refreshed to keep finding defects." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "qaf-m1-e7",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "Un software sin defectos pero que no sirve para lo que el usuario necesita ilustra…", en: "Defect-free software that is useless for what the user needs illustrates…" },
    options: [
      { id: "a", text: { es: "La falacia de ausencia de errores", en: "The absence-of-errors fallacy" } },
      { id: "b", text: { es: "La agrupación de defectos", en: "Defect clustering" } },
      { id: "c", text: { es: "El testing exhaustivo", en: "Exhaustive testing" } },
      { id: "d", text: { es: "El testing temprano", en: "Early testing" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "El principio 7: encontrar y corregir defectos no ayuda si el sistema no satisface las necesidades.", en: "Principle 7: finding and fixing defects does not help if the system fails to meet needs." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "qaf-m1-e8",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Cuál de estas afirmaciones sobre QC (control de calidad) es correcta?", en: "Which statement about QC (quality control) is correct?" },
    options: [
      { id: "a", text: { es: "Se orienta al proceso para prevenir defectos", en: "It is process-oriented to prevent defects" } },
      { id: "b", text: { es: "Se orienta al producto para detectar defectos", en: "It is product-oriented to detect defects" } },
      { id: "c", text: { es: "Es sinónimo exacto de QA", en: "It is an exact synonym of QA" } },
      { id: "d", text: { es: "No tiene relación con la calidad", en: "It is unrelated to quality" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "QC se orienta al producto y busca detectar defectos; QA se orienta al proceso (prevención).", en: "QC is product-oriented and detects defects; QA is process-oriented (prevention)." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "qaf-m1-e9",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Cuál es una habilidad esencial del QA tester manual?", en: "Which is an essential skill of the manual QA tester?" },
    options: [
      { id: "a", text: { es: "Evitar comunicarse con el equipo", en: "Avoid communicating with the team" } },
      { id: "b", text: { es: "Pensamiento crítico y atención al detalle", en: "Critical thinking and attention to detail" } },
      { id: "c", text: { es: "Confiar en que todo funciona", en: "Trust that everything works" } },
      { id: "d", text: { es: "Probar solo lo más fácil", en: "Test only the easiest things" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El pensamiento crítico y la atención al detalle son centrales en la mentalidad de testing.", en: "Critical thinking and attention to detail are central to the testing mindset." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "qaf-m1-e10",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Por qué 'no haber observado fallos' no significa 'no hay defectos'?", en: "Why does 'no failures observed' not mean 'there are no defects'?" },
    options: [
      { id: "a", text: { es: "Porque los defectos no existen", en: "Because defects do not exist" } },
      { id: "b", text: { es: "Porque un defecto solo falla si su código se ejecuta en ciertas condiciones", en: "Because a defect only fails if its code runs under certain conditions" } },
      { id: "c", text: { es: "Porque el testing es exhaustivo", en: "Because testing is exhaustive" } },
      { id: "d", text: { es: "Porque QA y QC son lo mismo", en: "Because QA and QC are the same" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "Un defecto latente puede no producir fallo si no se ejecuta el camino afectado.", en: "A latent defect may not produce a failure if the affected path is not executed." },
    points: 1,
    timeEstimateSeconds: 50,
  },
  {
    id: "qaf-m1-e11",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Qué afirma el primer principio del testing del ISTQB?", en: "What does the ISTQB's first testing principle state?" },
    options: [
      { id: "a", text: { es: "El testing demuestra la ausencia de defectos", en: "Testing proves the absence of defects" } },
      { id: "b", text: { es: "El testing muestra la presencia de defectos, pero no puede demostrar su ausencia", en: "Testing shows the presence of defects, but cannot prove their absence" } },
      { id: "c", text: { es: "El testing exhaustivo es posible con suficiente tiempo", en: "Exhaustive testing is possible with enough time" } },
      { id: "d", text: { es: "Los defectos se distribuyen siempre por igual", en: "Defects are always evenly distributed" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El principio 1 dice que el testing puede mostrar que hay defectos (presencia), pero nunca probar que no quedan (ausencia). Pasar todas las pruebas reduce el riesgo, no garantiza un software perfecto.", en: "Principle 1 states that testing can show that defects exist (presence), but never prove that none remain (absence). Passing all tests reduces risk; it does not guarantee perfect software." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "qaf-m1-e12",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "El principio de 'testing temprano' recomienda involucrar el testing desde el inicio (incluso revisando requisitos). ¿Cuál es su justificación principal?", en: "The 'early testing' principle recommends involving testing from the start (even reviewing requirements). What is its main rationale?" },
    options: [
      { id: "a", text: { es: "Tener más reuniones de equipo", en: "Having more team meetings" } },
      { id: "b", text: { es: "Corregir un defecto cuesta más cuanto más tarde se detecta en el ciclo de vida", en: "Fixing a defect costs more the later it is detected in the lifecycle" } },
      { id: "c", text: { es: "Así se evita tener que escribir casos de prueba", en: "It avoids having to write test cases" } },
      { id: "d", text: { es: "El testing temprano elimina la necesidad de testing dinámico", en: "Early testing removes the need for dynamic testing" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El testing temprano (shift-left) detecta defectos lo antes posible —incluso en requisitos y diseño mediante testing estático— porque el coste de corregir crece a lo largo del ciclo de vida: un error en requisitos es mucho más barato de arreglar que el mismo error ya en producción.", en: "Early testing (shift-left) detects defects as soon as possible — even in requirements and design via static testing — because the cost to fix grows along the lifecycle: a requirements error is far cheaper to fix than the same error already in production." },
    points: 1,
    timeEstimateSeconds: 50,
  },
  {
    id: "qaf-m1-e13",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "En un proyecto, el 80% de los fallos se concentran en 3 de los 20 módulos. Según el principio de 'agrupación de defectos', ¿qué estrategia es la más sensata?", en: "In a project, 80% of failures concentrate in 3 of 20 modules. Per the 'defect clustering' principle, which strategy is wisest?" },
    options: [
      { id: "a", text: { es: "Repartir el esfuerzo de prueba por igual entre los 20 módulos", en: "Spread test effort evenly across all 20 modules" } },
      { id: "b", text: { es: "Concentrar más esfuerzo en los módulos con más defectos detectados, sin abandonar el resto", en: "Focus more effort on the modules with the most detected defects, without abandoning the rest" } },
      { id: "c", text: { es: "Dejar de probar los 3 módulos problemáticos porque ya se conocen sus fallos", en: "Stop testing the 3 problematic modules because their failures are already known" } },
      { id: "d", text: { es: "Probar solo los 17 módulos restantes", en: "Test only the remaining 17 modules" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "La agrupación de defectos (principio 4) observa que unos pocos módulos suelen concentrar la mayoría de los defectos. Lo razonable es priorizar el esfuerzo donde se concentran los problemas (análisis de riesgos) sin dejar de cubrir el resto, y combinarlo con la paradoja del pesticida para no estancarse.", en: "Defect clustering (principle 4) observes that a few modules usually concentrate most defects. The sensible approach is to prioritize effort where problems cluster (risk analysis) while still covering the rest, combined with the pesticide paradox to avoid stagnation." },
    points: 1,
    timeEstimateSeconds: 55,
  },
  {
    id: "qaf-m1-e14",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "Se prueba con mucho más rigor el software de un marcapasos que el de un blog personal. ¿Qué principio del testing lo explica?", en: "A pacemaker's software is tested far more rigorously than a personal blog's. Which testing principle explains this?" },
    options: [
      { id: "a", text: { es: "El testing exhaustivo es imposible", en: "Exhaustive testing is impossible" } },
      { id: "b", text: { es: "El testing depende del contexto", en: "Testing is context-dependent" } },
      { id: "c", text: { es: "La paradoja del pesticida", en: "The pesticide paradox" } },
      { id: "d", text: { es: "La agrupación de defectos", en: "Defect clustering" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El principio 'el testing depende del contexto' establece que la intensidad, las técnicas y los criterios se adaptan al riesgo y al dominio: un sistema crítico de seguridad (marcapasos) exige mucho más rigor que un sitio de bajo riesgo (blog).", en: "The 'testing is context-dependent' principle states that intensity, techniques, and criteria adapt to risk and domain: a safety-critical system (pacemaker) demands far more rigor than a low-risk site (blog)." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "qaf-m1-e15",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "'¿Estamos construyendo el producto correctamente?' frente a '¿Estamos construyendo el producto correcto?'. ¿A qué corresponden, respectivamente?", en: "'Are we building the product right?' vs 'Are we building the right product?'. What do these correspond to, respectively?" },
    options: [
      { id: "a", text: { es: "Validación y verificación", en: "Validation and verification" } },
      { id: "b", text: { es: "Verificación y validación", en: "Verification and validation" } },
      { id: "c", text: { es: "Ambas son verificación", en: "Both are verification" } },
      { id: "d", text: { es: "Ambas son validación", en: "Both are validation" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "La verificación comprueba que el producto se construye conforme a sus especificaciones ('correctamente'); la validación comprueba que satisface las necesidades reales del usuario ('el producto correcto'). Un sistema puede pasar la verificación y aun así fallar la validación (ligado a la falacia de ausencia de errores).", en: "Verification checks that the product is built according to its specifications ('right'); validation checks that it meets the user's real needs ('the right product'). A system can pass verification and still fail validation (related to the absence-of-errors fallacy)." },
    points: 1,
    timeEstimateSeconds: 50,
  },
];

registerQuestions(QUESTIONS);

export default QUESTIONS;
