/**
 * QA Fundamentals — Banco de preguntas Módulo 2
 * (Fundamentos de Calidad de Software).
 * Fuentes: ISO/IEC 25010:2023, ISTQB CTFL v4.0.
 */

import type { ExamQuestion } from "@/types/exam";
import { registerQuestions } from "@/lib/exam/scoring";

const M = ["qaf-m2"];

const QUESTIONS: ExamQuestion[] = [
  {
    id: "qaf-m2-e1",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Qué es la calidad del software?", en: "What is software quality?" },
    options: [
      { id: "a", text: { es: "Que el código tenga muchos comentarios", en: "That the code has many comments" } },
      { id: "b", text: { es: "El grado en que satisface las necesidades declaradas e implícitas de las partes interesadas", en: "The degree to which it satisfies stated and implied stakeholder needs" } },
      { id: "c", text: { es: "Que no tenga ninguna línea de código duplicada", en: "That it has no duplicated lines of code" } },
      { id: "d", text: { es: "Que se haya desarrollado rápido", en: "That it was developed quickly" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "La calidad es el grado en que se satisfacen las necesidades declaradas e implícitas.", en: "Quality is the degree to which stated and implied needs are satisfied." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "qaf-m2-e2",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "Un sistema cumple los requisitos escritos pero es tan lento que nadie lo usa. ¿Tiene calidad?", en: "A system meets the written requirements but is so slow nobody uses it. Does it have quality?" },
    options: [
      { id: "a", text: { es: "Sí, cumple lo escrito", en: "Yes, it meets what is written" } },
      { id: "b", text: { es: "No, falla en las necesidades implícitas", en: "No, it fails the implied needs" } },
      { id: "c", text: { es: "La velocidad no es parte de la calidad", en: "Speed is not part of quality" } },
      { id: "d", text: { es: "Solo desarrollo puede decidirlo", en: "Only development can decide" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "El rendimiento es una necesidad implícita; no satisfacerlo reduce la calidad.", en: "Performance is an implied need; failing it reduces quality." },
    points: 1,
    timeEstimateSeconds: 50,
  },
  {
    id: "qaf-m2-e3",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Qué norma define el modelo de calidad de producto de software (SQuaRE)?", en: "Which standard defines the software product quality model (SQuaRE)?" },
    options: [
      { id: "a", text: { es: "ISO/IEC 25010", en: "ISO/IEC 25010" } },
      { id: "b", text: { es: "Scrum Guide", en: "Scrum Guide" } },
      { id: "c", text: { es: "Agile Manifesto", en: "Agile Manifesto" } },
      { id: "d", text: { es: "BABOK", en: "BABOK" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "ISO/IEC 25010, de la familia SQuaRE, define el modelo de calidad de producto.", en: "ISO/IEC 25010, from the SQuaRE family, defines the product quality model." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "qaf-m2-e4",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "El usuario no logra aprender a usar la app sin ayuda constante. ¿Qué característica falla?", en: "The user cannot learn the app without constant help. Which characteristic fails?" },
    options: [
      { id: "a", text: { es: "Usabilidad", en: "Usability" } },
      { id: "b", text: { es: "Seguridad", en: "Security" } },
      { id: "c", text: { es: "Portabilidad", en: "Portability" } },
      { id: "d", text: { es: "Mantenibilidad", en: "Maintainability" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La facilidad de aprendizaje y uso forma parte de la usabilidad.", en: "Ease of learning and use is part of usability." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "qaf-m2-e5",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "'El sistema debe permitir exportar un informe a PDF' es un requisito…", en: "'The system must allow exporting a report to PDF' is a requirement that is…" },
    options: [
      { id: "a", text: { es: "No funcional", en: "Non-functional" } },
      { id: "b", text: { es: "Funcional", en: "Functional" } },
      { id: "c", text: { es: "De rendimiento", en: "Performance" } },
      { id: "d", text: { es: "De seguridad", en: "Security" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "Describe qué hace el sistema: es un requisito funcional.", en: "It describes what the system does: a functional requirement." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "qaf-m2-e6",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "'El sistema debe soportar 1000 usuarios simultáneos' es un requisito…", en: "'The system must support 1000 concurrent users' is a requirement that is…" },
    options: [
      { id: "a", text: { es: "Funcional", en: "Functional" } },
      { id: "b", text: { es: "No funcional", en: "Non-functional" } },
      { id: "c", text: { es: "De negocio", en: "Business" } },
      { id: "d", text: { es: "Una historia de usuario", en: "A user story" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "Describe cómo se comporta (rendimiento/escalabilidad): requisito no funcional.", en: "It describes how it behaves (performance/scalability): a non-functional requirement." },
    points: 1,
    timeEstimateSeconds: 45,
  },
  {
    id: "qaf-m2-e7",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Qué significa 'shift-left' en QA?", en: "What does 'shift-left' mean in QA?" },
    options: [
      { id: "a", text: { es: "Probar solo al final del proyecto", en: "Test only at the end of the project" } },
      { id: "b", text: { es: "Mover las actividades de calidad a fases tempranas", en: "Move quality activities to early phases" } },
      { id: "c", text: { es: "Eliminar la documentación", en: "Remove documentation" } },
      { id: "d", text: { es: "Automatizar todas las pruebas", en: "Automate all tests" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "Shift-left adelanta el testing y la calidad para detectar defectos pronto.", en: "Shift-left moves testing and quality earlier to detect defects sooner." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "qaf-m2-e8",
    type: "single_choice",
    difficulty: "medium",
    moduleIds: M,
    question: { es: "¿Por qué conviene detectar defectos lo antes posible?", en: "Why is it best to detect defects as early as possible?" },
    options: [
      { id: "a", text: { es: "Porque corregirlos más tarde suele costar más", en: "Because fixing them later usually costs more" } },
      { id: "b", text: { es: "Porque los defectos tempranos no importan", en: "Because early defects do not matter" } },
      { id: "c", text: { es: "Porque así no hay que documentar", en: "Because then there is no need to document" } },
      { id: "d", text: { es: "Porque elimina la necesidad de testing", en: "Because it removes the need for testing" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "El coste de corregir crece a lo largo del ciclo de vida; de ahí el valor del shift-left.", en: "The cost to fix grows along the lifecycle; hence the value of shift-left." },
    points: 1,
    timeEstimateSeconds: 50,
  },
  {
    id: "qaf-m2-e9",
    type: "single_choice",
    difficulty: "easy",
    moduleIds: M,
    question: { es: "¿Cuál de las siguientes es una de las características de calidad de producto del modelo ISO/IEC 25010?", en: "Which of the following is one of the product quality characteristics in the ISO/IEC 25010 model?" },
    options: [
      { id: "a", text: { es: "Rentabilidad", en: "Profitability" } },
      { id: "b", text: { es: "Fiabilidad", en: "Reliability" } },
      { id: "c", text: { es: "Popularidad", en: "Popularity" } },
      { id: "d", text: { es: "Antigüedad", en: "Age" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "ISO/IEC 25010 define ocho características de calidad de producto: adecuación funcional, eficiencia de desempeño, compatibilidad, usabilidad, fiabilidad, seguridad, mantenibilidad y portabilidad. La rentabilidad, la popularidad y la antigüedad no forman parte del modelo.", en: "ISO/IEC 25010 defines eight product quality characteristics: functional suitability, performance efficiency, compatibility, usability, reliability, security, maintainability, and portability. Profitability, popularity, and age are not part of the model." },
    points: 1,
    timeEstimateSeconds: 40,
  },
  {
    id: "qaf-m2-e10",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "Una app debe seguir funcionando correctamente aunque la red se caiga de forma intermitente, recuperándose sola. ¿Qué característica de ISO/IEC 25010 se evalúa principalmente?", en: "An app must keep working correctly even if the network drops intermittently, recovering on its own. Which ISO/IEC 25010 characteristic is primarily evaluated?" },
    options: [
      { id: "a", text: { es: "Usabilidad", en: "Usability" } },
      { id: "b", text: { es: "Fiabilidad (incluye tolerancia a fallos y recuperabilidad)", en: "Reliability (includes fault tolerance and recoverability)" } },
      { id: "c", text: { es: "Portabilidad", en: "Portability" } },
      { id: "d", text: { es: "Compatibilidad", en: "Compatibility" } },
    ],
    correctOptionIds: ["b"],
    explanation: { es: "La fiabilidad agrupa subcaracterísticas como madurez, disponibilidad, tolerancia a fallos y capacidad de recuperación. Mantener el comportamiento correcto ante caídas de red y recuperarse solo es tolerancia a fallos/recuperabilidad, parte de la fiabilidad.", en: "Reliability groups subcharacteristics such as maturity, availability, fault tolerance, and recoverability. Keeping correct behavior under network drops and recovering on its own is fault tolerance/recoverability, part of reliability." },
    points: 1,
    timeEstimateSeconds: 55,
  },
  {
    id: "qaf-m2-e11",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "Un equipo necesita poder migrar su aplicación de AWS a Azure con cambios mínimos. ¿Qué característica de calidad prioriza?", en: "A team needs to migrate their app from AWS to Azure with minimal changes. Which quality characteristic does this prioritize?" },
    options: [
      { id: "a", text: { es: "Portabilidad", en: "Portability" } },
      { id: "b", text: { es: "Seguridad", en: "Security" } },
      { id: "c", text: { es: "Usabilidad", en: "Usability" } },
      { id: "d", text: { es: "Adecuación funcional", en: "Functional suitability" } },
    ],
    correctOptionIds: ["a"],
    explanation: { es: "La portabilidad mide la facilidad para transferir el software a otro entorno (hardware, software, plataforma). Migrar entre proveedores cloud con cambios mínimos corresponde a adaptabilidad/instalabilidad, subcaracterísticas de la portabilidad.", en: "Portability measures how easily software can be transferred to another environment (hardware, software, platform). Migrating between cloud providers with minimal changes corresponds to adaptability/installability, subcharacteristics of portability." },
    points: 1,
    timeEstimateSeconds: 50,
  },
  {
    id: "qaf-m2-e12",
    type: "single_choice",
    difficulty: "hard",
    moduleIds: M,
    question: { es: "Un cliente reporta un bug ya en producción y el equipo gasta tiempo en corregirlo y enviar un parche. En el modelo de coste de la calidad, ¿qué tipo de coste es?", en: "A customer reports a bug already in production and the team spends time fixing it and shipping a patch. In the cost-of-quality model, what type of cost is this?" },
    options: [
      { id: "a", text: { es: "Coste de prevención", en: "Prevention cost" } },
      { id: "b", text: { es: "Coste de evaluación (appraisal)", en: "Appraisal cost" } },
      { id: "c", text: { es: "Coste de fallo externo", en: "External failure cost" } },
      { id: "d", text: { es: "Coste de fallo interno", en: "Internal failure cost" } },
    ],
    correctOptionIds: ["c"],
    explanation: { es: "El coste de la calidad se divide en prevención (evitar defectos), evaluación (detectarlos: revisiones, testing), fallo interno (defectos hallados antes de entregar) y fallo externo (defectos que llegan al cliente/producción). Un bug reportado por el cliente en producción es un coste de fallo externo, el más caro de todos.", en: "Cost of quality splits into prevention (avoiding defects), appraisal (detecting them: reviews, testing), internal failure (defects found before delivery), and external failure (defects that reach the customer/production). A bug reported by the customer in production is an external failure cost, the most expensive of all." },
    points: 1,
    timeEstimateSeconds: 55,
  },
];

registerQuestions(QUESTIONS);

export default QUESTIONS;
